<?php

namespace Database\Seeders\knowledge;

class BotKnowledgeProsedurSistem
{
    public function getProsedur(): array
    {
        return [
            [
                'kunci' => 'pros-001',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan surat keterangan di SIG-Udeung?',
                'kata_kunci' => ['surat keterangan', 'pengajuan surat', 'surat', 'keterangan'],
                'jawaban_atau_konten' => 'Untuk mengajukan surat keterangan di SIG-Udeung, ikuti langkah berikut: 1) Login ke portal warga SIG-Udeung menggunakan NIK dan Nomor Kartu Keluarga. 2) Pilih menu "Pengajuan Surat" di dashboard. 3) Pilih jenis surat yang dibutuhkan, misalnya surat keterangan tidak mampu, surat keterangan usaha, atau surat keterangan domisili. 4) Lengkapi data yang diminta seperti alamat, keperluan surat, dan lampiran dokumen pendukung. 5) Klik "Kirim Pengajuan". 6) Tunggu proses verifikasi dari admin gampong, biasanya 1-3 hari kerja. 7) Setelah disetujui, Anda akan menerima notifikasi dan bisa mengunduh surat dalam format PDF dari menu "Pengajuan Saya".',
            ],
            [
                'kunci' => 'pros-002',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan penduduk baru di SIG-Udeung?',
                'kata_kunci' => ['penduduk baru', 'pendaftaran penduduk', 'pendatang baru', 'warga baru'],
                'jawaban_atau_konten' => 'Pendaftaran penduduk baru di SIG-Udeung dilakukan oleh perangkat gampong: 1) Datang ke kantor gampong membawa dokumen asli seperti KTP, KK, dan surat pengantar dari desa asal. 2) Petugas admin gampong akan mengakses panel admin SIG-Udeung. 3) Pilih menu "Penduduk" lalu "Tambah Penduduk Baru". 4) Isi data lengkap sesuai dokumen: NIK, nama lengkap, tanggal lahir, jenis kelamin, alamat, dan status hubungan dalam keluarga. 5) Unggah scan dokumen pendukung. 6) Simpan data. 7) Data akan otomatis tercatat dalam database kependudukan gampong dan dapat diakses melalui fitur pencarian penduduk.',
            ],
            [
                'kunci' => 'pros-003',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengurus pendaftaran penduduk pindah di SIG-Udeung?',
                'kata_kunci' => ['penduduk pindah', 'pindah domisili', 'pindah keluar', 'mutasi penduduk'],
                'jawaban_atau_konten' => 'Untuk mengurus pindah penduduk: 1) Ajukan permohonan pindah melalui portal warga SIG-Udeung atau datang langsung ke kantor gampong. 2) Isi form pindah yang mencakup data diri, alamat tujuan pindah, dan alasan pindah. 3) Lampirkan dokumen pendukung seperti KTP tujuan pindah atau surat keterangan diterima di daerah tujuan. 4) Petugas admin akan memproses data pindah di panel admin. 5) Status penduduk akan diubah menjadi "Pindah Keluar". 6) Data akan otomatis terintegrasi dengan sistem kependudukan tingkat kecamatan. 7) Anda akan menerima surat keterangan pindah sebagai bukti resmi.',
            ],
            [
                'kunci' => 'pros-004',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan bantuan sosial melalui SIG-Udeung?',
                'kata_kunci' => ['bantuan sosial', 'banos', 'bansos', 'pengajuan bantuan', 'bantuan warga'],
                'jawaban_atau_konten' => 'Cara mengajukan bantuan sosial: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Bantuan Sosial". 3) Klik "Ajukan Bantuan Baru". 4) Pilih jenis bantuan yang tersedia seperti bantuan pangan, bantuan sembako, atau bantuan biaya pendidikan. 5) Isi data diri lengkap dan jelaskan kondisi sosial ekonomi Anda. 6) Lampirkan dokumen pendukung seperti KTP, KK, surat keterangan tidak mampu dari RT/RW, atau slip gaji jika ada. 7) Kirim pengajuan. 8) Pengajuan akan diverifikasi oleh admin gampong dan diteruskan ke dinas terkait. 9) Pantau status pengajuan melalui menu "Pengajuan Saya" di dashboard.',
            ],
            [
                'kunci' => 'pros-005',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara melaporkan kematian melalui SIG-Udeung?',
                'kata_kunci' => ['lapor kematian', 'kematian', 'meninggal dunia', 'lapor meninggal'],
                'jawaban_atau_konten' => 'Untuk melaporkan kematian: 1) Buka portal warga SIG-Udeung. 2) Pilih menu "Pelaporan Penduduk". 3) Pilih submenu "Laporan Kematian". 4) Isi data orang yang meninggal: NIK, nama lengkap, tanggal kematian, dan tempat kematian. 5) Lampirkan surat kematian dari rumah sakit atau dokter yang merawat, serta salinan KTP almarhum/almarhumah. 6) Isi data pelapor: nama, hubungan dengan almarhum, dan kontak yang bisa dihubungi. 7) Kirim laporan. 8) Petugas admin akan memproses penghapusan data kependudukan aktif dan mengubah status menjadi meninggal dunia. 9) Surat keterangan kematian akan tersedia untuk diunduh setelah proses selesai.',
            ],
            [
                'kunci' => 'pros-006',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara melaporkan kelahiran melalui SIG-Udeung?',
                'kata_kunci' => ['lapor kelahiran', 'kelahiran', 'bayi lahir', 'pendaftaran bayi', 'anak baru lahir'],
                'jawaban_atau_konten' => 'Cara melaporkan kelahiran: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Pelaporan Penduduk" lalu "Laporan Kelahiran". 3) Isi data bayi yang baru lahir: nama yang diusulkan, tanggal lahir, jenis kelamin, berat badan, dan panjang badan saat lahir. 4) Isi data orang tua: NIK ayah, NIK ibu, dan jumlah anak keberapa. 5) Lampirkan surat kelahiran dari rumah sakit atau bidan. 6) Kirim laporan. 7) Admin gampong akan memproses pendaftaran bayi sebagai penduduk baru. 8) NIK bayi akan dibuatkan dan data akan tercatat dalam database kependudukan. 9) Akta kelahiran bisa diambil di kantor gampong setelah proses selesai.',
            ],
            [
                'kunci' => 'pros-007',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan SKCK melalui SIG-Udeung?',
                'kata_kunci' => ['SKCK', 'surat keterangan catatan kepolisian', 'skck online'],
                'jawaban_atau_konten' => 'Untuk mengajukan SKCK melalui SIG-Udeung: 1) Login ke portal warga dengan NIK dan No KK. 2) Pilih menu "Pengajuan Surat" lalu cari opsi "Surat Keterangan Catatan Kepolisian". 3) Isi data diri lengkap: nama, alamat, pekerjaan, dan tujuan pengajuan SKCK. 4) Unggah foto berwarna terbaru dengan latar belakang merah (ukuran 3x4). 5) Lampirkan KTP dan KK asli yang sudah discan. 6) Kirim pengajuan. 7) Pengajuan akan diteruskan ke polsek atau polres terdekat. 8) Proses pembuatan SKCK biasanya memakan waktu 2-3 hari kerja. 9) Setelah selesai, Anda akan menerima notifikasi dan bisa mengambil SKCK di kantor polisi atau mengunduh salinan digitalnya.',
            ],
            [
                'kunci' => 'pros-008',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan surat nikah melalui SIG-Udeung?',
                'kata_kunci' => ['surat nikah', 'nikah', 'menikah', 'pengajuan nikah', 'surat pengantar nikah'],
                'jawaban_atau_konten' => 'Cara mengajukan surat nikah: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Pengajuan Surat" lalu "Surat Pengantar Nikah". 3) Isi data calon pengantin: NIK calon mempelai pria dan wanita, nama lengkap, tanggal lahir, agama, dan alamat. 4) Lampirkan KTP, KK, surat keterangan belum menikah dari RT/RW, surat keterangan beragama, foto copy akta kelahiran, dan foto berwarna 2 lembar ukuran 2x3 dan 4x6 masing-masing 3 lembar. 5) Isi data wali nikah jika ada. 6) Kirim pengajuan. 7) Admin gampong akan memproses dan menerbitkan surat pengantar nikah. 8) Surat pengantar nikah bisa diambil di kantor gampong dan digunakan untuk mendaftar ke KUA kecamatan.',
            ],
            [
                'kunci' => 'pros-009',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan diri ke BPJS Kesehatan melalui SIG-Udeung?',
                'kata_kunci' => ['BPJS', 'bpjs kesehatan', 'daftar bpjs', 'jaminan kesehatan', 'asuransi kesehatan'],
                'jawaban_atau_konten' => 'Untuk pendaftaran BPJS Kesehatan melalui SIG-Udeung: 1) Login ke portal warga. 2) Pilih menu "Layanan Kesehatan" lalu "Pendaftaran BPJS". 3) Pilih jenis kepesertaan: Pekerja Penerima Upah (PPU), Pekerja Bukan Penerima Upah (PBPU), atau Pekerja Pihak Ketiga. 4) Isi data diri: NIK, nama, alamat, tanggal lahir, dan golongan darah. 5) Lampirkan KTP, KK, dan rekening bank untuk auto-debet jika memilih PBPU. 6) Pilih fasilitas kesehatan tingkat pertama (puskesmas). 7) Kirim pendaftaran. 8) Data akan diteruskan ke BPJS Kesehatan untuk diproses. 9) Kartu BPJS bisa diambil di kantor BPJS terdekat atau diunduh dalam bentuk digital melalui aplikasi Mobile JKN.',
            ],
            [
                'kunci' => 'pros-010',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak sekolah melalui SIG-Udeung?',
                'kata_kunci' => ['daftar sekolah', 'pendaftaran sekolah', 'sekolah anak', 'pendidikan anak', 'ppdb'],
                'jawaban_atau_konten' => 'Cara mendaftarkan anak sekolah melalui SIG-Udeung: 1) Login ke portal warga. 2) Pilih menu "Pendidikan" lalu "Pendaftaran Sekolah". 3) Pilih jenjang sekolah: PAUD, TK, SD, atau SMP. 4) Isi data anak: NIK, nama lengkap, tanggal lahir, jenis kelamin, dan alamat. 5) Isi data orang tua: NIK orang tua, nama, pekerjaan, dan penghasilan bulanan. 6) Lampirkan akta kelahiran, KK, KTP orang tua, dan kartu vaksinasi. 7) Pilih sekolah tujuan dari daftar sekolah yang tersedia. 8) Kirim pendaftaran. 9) Status pendaftaran bisa dipantau melalui menu "Pengajuan Saya". 10) Jika diterima, Anda akan menerima notifikasi untuk melengkapi administrasi pendaftaran.',
            ],
            [
                'kunci' => 'pros-011',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan KUR (Kredit Usaha Rakyat) melalui SIG-Udeung?',
                'kata_kunci' => ['KUR', 'kredit usaha rakyat', 'pinjaman usaha', 'kredit usaha', 'modal usaha'],
                'jawaban_atau_konten' => 'Untuk mengajukan KUR: 1) Pastikan usaha Anda sudah terdaftar sebagai UMKM di SIG-Udeung. 2) Login ke portal warga. 3) Pilih menu "Layanan Ekonomi" lalu "Pengajuan KUR". 4) Pilih bank penyalur KUR yang bekerja sama. 5) Isi data usaha: nama usaha, jenis usaha, lama usaha berjalan, omzet bulanan, dan alamat usaha. 6) Isi data diri: NIK, nama, alamat, dan kontak yang bisa dihubungi. 7) Lampirkan KTP, KK, rekening koran 3 bulan terakhir, surat keterangan usaha dari gampong, dan foto usaha. 8) Kirim pengajuan. 9) Tim verifikasi bank akan menghubungi Anda untuk proses lebih lanjut. 10) Pantau status pengajuan melalui dashboard.',
            ],
            [
                'kunci' => 'pros-012',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan UMKM ke SIG-Udeung?',
                'kata_kunci' => ['daftar UMKM', 'UMKM', 'usaha kecil', 'usaha mikro', 'pendaftaran usaha'],
                'jawaban_atau_konten' => 'Cara mendaftarkan UMKM: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Ekonomi Desa" lalu "Daftar UMKM". 3) Klik "Tambah UMKM Baru". 4) Isi data usaha: nama usaha, jenis usaha, alamat usaha, nomor telepon, email, dan deskripsi singkat produk atau jasa. 5) Isi data pemilik: NIK, nama lengkap, dan alamat. 6) Unggah foto produk atau tempat usaha. 7) Lampirkan KTP, KK, dan surat izin usaha jika ada. 8) Kirim pendaftaran. 9) Admin gampong akan memverifikasi data usaha. 10) Setelah diverifikasi, UMKM Anda akan terdaftar di direktori UMKM desa dan dapat diakses oleh warga lain.',
            ],
            [
                'kunci' => 'pros-013',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara melaporkan bencana alam melalui SIG-Udeung?',
                'kata_kunci' => ['lapor bencana', 'bencana alam', 'banjir', 'longsor', 'kebakaran'],
                'jawaban_atau_konten' => 'Untuk melaporkan bencana alam: 1) Buka portal warga SIG-Udeung. 2) Pilih menu "Darurat" lalu "Laporan Bencana". 3) Pilih jenis bencana: banjir, longsor, kebakaran, angin kencang, atau jenis lainnya. 4) Isi lokasi kejadian secara detail: nama dusun, RT/RW, dan koordinat lokasi jika memungkinkan. 5) Jelaskan kronologi kejadian dan kondisi terkini. 6) Unggah foto atau video kondisi bencana jika ada. 7) Isi data pelapor: nama, kontak yang bisa dihubungi. 8) Kirim laporan. 9) Laporan akan langsung diteruskan ke tim tanggap darurat gampong dan kecamatan. 10) Anda akan menerima konfirmasi dan informasi langkah selanjutnya.',
            ],
            [
                'kunci' => 'pros-014',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara menyampaikan pengaduan warga melalui SIG-Udeung?',
                'kata_kunci' => ['pengaduan', 'aduan warga', 'keluhan', 'lapor masalah', 'saran'],
                'jawaban_atau_konten' => 'Cara menyampaikan pengaduan: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Pengaduan & Saran". 3) Klik "Buat Pengaduan Baru". 4) Pilih kategori pengaduan: infrastruktur, pelayanan publik, keamanan, lingkungan, atau lainnya. 5) Isi judul pengaduan yang ringkas dan jelas. 6) Jelaskan kronologi masalah secara detail dalam kolom deskripsi. 7) Lampirkan bukti berupa foto, video, atau dokumen pendukung. 8) Pilih tingkat prioritas: rendah, sedang, atau tinggi. 9) Kirim pengaduan. 10) Pantau status penanganan melalui menu "Pengajuan Saya" atau melalui notifikasi yang dikirim ke email dan WhatsApp Anda.',
            ],
            [
                'kunci' => 'pros-015',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan tanah melalui program PTSL di SIG-Udeung?',
                'kata_kunci' => ['PTSL', 'pendaftaran tanah', 'sertifikat tanah', 'tanah desa', 'legalitas tanah'],
                'jawaban_atau_konten' => 'Untuk pendaftaran tanah melalui PTSL: 1) Login ke portal warga. 2) Pilih menu "Pertanahan" lalu "Pendaftaran PTSL". 3) Isi data pemohon: NIK, nama lengkap, alamat, dan status kepemilikan tanah. 4) Isi data tanah: lokasi, luas tanah, batas-batas tanah, dan penggunaan tanah saat ini. 5) Lampirkan surat bukti kepemilikan tanah seperti letter C, akta jual beli, atau surat waris. 6) Unggah foto tanah dari beberapa sudut. 7) Pilih kantor pertanahan terdekat untuk proses verifikasi. 8) Kirim pendaftaran. 9) Tim PTSL akan melakukan pengukuran dan pemeriksaan data. 10) Sertifikat tanah akan diterbitkan dan bisa diambil di kantor pertanahan.',
            ],
            [
                'kunci' => 'pros-016',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan pemasangan listrik baru melalui SIG-Udeung?',
                'kata_kunci' => ['listrik baru', 'pasang listrik', 'PLN', 'sambungan listrik', 'daya listrik'],
                'jawaban_atau_konten' => 'Cara mengajukan pemasangan listrik baru: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Layanan Utilitas" lalu "Pengajuan Listrik Baru". 3) Isi data pemohon: NIK, nama lengkap, alamat lengkap, dan nomor telepon. 4) Isi data properti: jenis bangunan (rumah tinggal, toko, rumah makan), luas bangunan, dan daya listrik yang diinginkan (450VA, 900VA, 1300VA, atau 2200VA). 5) Lampirkan KTP, KK, dan surat bukti kepemilikan atau sewa properti. 6) Unggah foto properti dari depan. 7) Kirim pengajuan. 8) Data akan diteruskan ke PLN untuk proses survey lokasi. 9) Tim PLN akan menghubungi Anda untuk jadwal pemasangan. 10) Biaya pemasangan akan diinformasikan oleh PLN.',
            ],
            [
                'kunci' => 'pros-017',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan program air bersih di SIG-Udeung?',
                'kata_kunci' => ['air bersih', 'pam', 'air minum', 'sambungan air', 'pdam'],
                'jawaban_atau_konten' => 'Untuk pendaftaran air bersih: 1) Login ke portal warga. 2) Pilih menu "Layanan Utilitas" lalu "Pendaftaran Air Bersih". 3) Isi data diri: NIK, nama, alamat, dan nomor telepon. 4) Isi data properti: jumlah kamar mandi, jumlah anggota keluarga, dan perkiraan penggunaan air per hari. 5) Lampirkan KTP, KK, dan bukti kepemilikan rumah. 6) Pilih jenis sambungan: rumah tangga, usaha, atau instansi. 7) Kirim pendaftaran. 8) Petugas PDAM atau penyedia air akan melakukan survey lokasi. 9) Setelah survey, Anda akan menerima perkiraan biaya pemasangan dan langganan. 10) Setelah pembayaran, petugas akan memasang jaringan air ke rumah Anda.',
            ],
            [
                'kunci' => 'pros-018',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan pembuatan sumur bor melalui SIG-Udeung?',
                'kata_kunci' => ['sumur bor', 'sumur', 'air tanah', 'bor sumur', 'pengadaan air'],
                'jawaban_atau_konten' => 'Cara mengajukan pembuatan sumur bor: 1) Login ke portal warga SIG-Udeung. 2) Pilih menu "Layanan Utilitas" lalu "Pengajuan Sumur Bor". 3) Isi data pemohon: NIK, nama, alamat, dan kontak. 4) Jelaskan kondisi lokasi: jenis tanah, kedalaman air tanah yang diketahui, dan jarak dari sumber air terdekat. 5) Lampirkan KTP, KK, dan surat izin penggunaan tanah jika ada. 6) Pilih jenis sumur: sumur bor rumah tangga atau sumur bor komunal. 7) Kirim pengajuan. 8) Tim teknis gampong akan melakukan survey lokasi. 9) Jika disetujui, jadwal pembuatan sumur bor akan diinformasikan. 10) Biaya pembuatan dan perawatan akan dijelaskan saat survey.',
            ],
            [
                'kunci' => 'pros-019',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan pembangunan jalan gampong melalui SIG-Udeung?',
                'kata_kunci' => ['jalan gampong', 'jalan desa', 'infrastruktur jalan', 'perbaikan jalan', 'pembangunan jalan'],
                'jawaban_atau_konten' => 'Untuk mengajukan pembangunan jalan gampong: 1) Login ke portal warga. 2) Pilih menu "Infrastruktur" lalu "Pengajuan Jalan Gampong". 3) Isi data pemohon: NIK, nama, alamat, dan dusun tempat tinggal. 4) Isi data jalan yang diajukan: nama ruas jalan, panjang jalan, lebar jalan, dan kondisi saat ini. 5) Jelaskan urgensi pembangunan dan dampak bagi warga sekitar. 6) Lampirkan foto kondisi jalan saat ini. 7) Sertakan rekomendasi dari ketua RT/RW atau geuchik. 8) Kirim pengajuan. 9) Pengajuan akan dibahas dalam musyawarah gampong berikutnya. 10) Jika disetujui, pembangunan akan masuk dalam rencana anggaran gampong.',
            ],
            [
                'kunci' => 'pros-020',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan diri untuk mengikuti musyawarah gampong melalui SIG-Udeung?',
                'kata_kunci' => ['musyawarah gampong', 'musyawarah desa', 'musrenbangdes', 'rapat desa'],
                'jawaban_atau_konten' => 'Cara mendaftarkan diri mengikuti musyawarah gampong: 1) Login ke portal warga. 2) Pilih menu "Partisipasi Warga" lalu "Musyawarah Gampong". 3) Lihat jadwal musyawarah yang tersedia beserta agenda yang akan dibahas. 4) Klik "Daftar" pada musyawarah yang ingin diikuti. 5) Konfirmasi kehadiran Anda. 6) Anda juga bisa mengajukan usul atau aspirasi melalui form yang tersedia sebelum pelaksanaan musyawarah. 7) Setelah mendaftar, Anda akan menerima undangan digital dengan detail waktu dan tempat. 8) Hadir tepat waktu sesuai jadwal. 9) Hasil musyawarah akan diupload ke portal setelah acara selesai.',
            ],
            [
                'kunci' => 'pros-021',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana proses pemilihan keuchik di SIG-Udeung?',
                'kata_kunci' => ['pemilihan keuchik', 'pilkeuchik', 'keuchik', 'pemilihan kepala desa'],
                'jawaban_atau_konten' => 'Proses pemilihan keuchik di SIG-Udeung: 1) Pengumuman pemilihan keuchik akan ditampilkan di dashboard dan notifikasi dikirim ke semua warga. 2) Warga terdaftar bisa melihat profil dan visi misi calon keuchik di menu "Pemilihan Keuchik". 3) Masa kampanye calon akan ditampilkan dengan jadwal debat publik. 4) Pada hari pemilihan, warga login ke portal dan memilih calon favorit. 5) Setiap warga yang sudah terverifikasi hanya boleh memberikan satu suara. 6) Hasil pemilihan akan ditampilkan secara transparan setelah pemungutan suara ditutup. 7) Calon dengan suara terbanyak akan ditetapkan sebagai keuchik terpilih. 8) Berkas pelantikan akan diteruskan ke kecamatan.',
            ],
            [
                'kunci' => 'pros-022',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke TPA (Taman Pendidikan Al-Quran) melalui SIG-Udeung?',
                'kata_kunci' => ['daftar TPA', 'TPA', 'taman pendidikan al-quran', 'belajar mengaji', 'pendidikan agama'],
                'jawaban_atau_konten' => 'Cara mendaftarkan anak ke TPA: 1) Login ke portal warga. 2) Pilih menu "Pendidikan Agama" lalu "Pendaftaran TPA". 3) Isi data anak: NIK, nama lengkap, tanggal lahir, dan nama orang tua. 4) Pilih lokasi TPA yang tersedia di gampong. 5) Pilih jadwal belajar: pagi, sore, atau weekend. 6) Lampirkan akta kelahiran dan foto anak terbaru. 7) Kirim pendaftaran. 8) Pengurus TPA akan menghubungi Anda untuk konfirmasi dan penjadwalan uji baca tulis Al-Quran. 9) Setelah lolos seleksi, anak Anda resmi terdaftar. 10) Jadwal masuk dan informasi pembayaran SPP akan diinformasikan.',
            ],
            [
                'kunci' => 'pros-023',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke posyandu melalui SIG-Udeung?',
                'kata_kunci' => ['daftar posyandu', 'posyandu', 'imunisasi', 'balita', 'kesehatan anak'],
                'jawaban_atau_konten' => 'Untuk pendaftaran posyandu: 1) Login ke portal warga. 2) Pilih menu "Kesehatan" lalu "Pendaftaran Posyandu". 3) Isi data anak: NIK, nama lengkap, tanggal lahir, jenis kelamin, berat badan saat ini, dan tinggi badan. 4) Isi data ibu: NIK ibu, nama, dan nomor telepon. 5) Pilih posyandu terdekat dari lokasi rumah. 6) Lampirkan buku KIA (Kartu Ibu dan Anak) dan kartu vaksinasi. 7) Kirim pendaftaran. 8) Kader posyandu akan menghubungi Anda untuk jadwal penimbangan bulanan. 9) Anak Anda akan tercatat dalam database kesehatan gampong. 10) Reminder jadwal imunisasi dan penimbangan akan dikirim melalui notifikasi.',
            ],
            [
                'kunci' => 'pros-024',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan izin usaha melalui SIG-Udeung?',
                'kata_kunci' => ['izin usaha', 'izin', 'NIB', 'nomor induk berusaha', 'perizinan'],
                'jawaban_atau_konten' => 'Cara mengajukan izin usaha: 1) Login ke portal warga. 2) Pilih menu "Perizinan" lalu "Izin Usaha". 3) Pilih jenis izin: izin usaha mikro dan kecil (IUMK), izin gangguan (HO), atau izin tempat usaha. 4) Isi data usaha: nama usaha, bidang usaha, alamat usaha, dan jumlah tenaga kerja. 5) Isi data pemilik: NIK, nama lengkap, dan alamat. 6) Lampirkan KTP, KK, foto tempat usaha, dan surat sewa atau bukti kepemilikan tempat usaha. 7) Kirim pengajuan. 8) Admin gampong akan memverifikasi data dan meneruskan ke dinas terkait. 9) Proses perizinan biasanya memakan waktu 3-7 hari kerja. 10) Izin usaha bisa diunduh dari portal setelah disetujui.',
            ],
            [
                'kunci' => 'pros-025',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan koperasi melalui SIG-Udeung?',
                'kata_kunci' => ['daftar koperasi', 'koperasi', 'koperasi simpan pinjam', 'koperasi desa'],
                'jawaban_atau_konten' => 'Untuk pendaftaran koperasi: 1) Minimal 20 orang anggota harus mendaftar terlebih dahulu di portal warga. 2) Pilih menu "Ekonomi Desa" lalu "Pendaftaran Koperasi". 3) Isi data koperasi: nama koperasi, jenis koperasi (konsumsi, simpan pinjam, atau produksi), alamat kantor, dan rencana kegiatan. 4) Isi data pengurus: ketua, sekretaris, bendahara, dan anggota pengawas beserta NIK masing-masing. 5) Lampirkan AD/ART koperasi, daftar anggota, dan surat keterangan domisili kantor. 6) Kirim pendaftaran. 7) Admin gampong akan memverifikasi kelengkapan berkas. 8) Jika lengkap, pendaftaran akan diteruskan ke dinas koperasi untuk penerbitan badan hukum. 9) Status pendaftaran bisa dipantau melalui portal.',
            ],
            [
                'kunci' => 'pros-026',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan bantuan bedah rumah melalui SIG-Udeung?',
                'kata_kunci' => ['bedah rumah', 'renovasi rumah', 'bantuan rumah', 'perbaikan rumah'],
                'jawaban_atau_konten' => 'Cara mengajukan bantuan bedah rumah: 1) Login ke portal warga. 2) Pilih menu "Bantuan Sosial" lalu "Pengajuan Bedah Rumah". 3) Isi data pemohon: NIK, nama, alamat, dan kondisi rumah saat ini. 4) Jelaskan kondisi rumah: atap bocor, dinding rusak, lantai tanah, atau kerusakan lainnya. 5) Unggah foto rumah dari beberapa sudut yang memperlihatkan kerusakan. 6) Lampirkan KTP, KK, surat keterangan tidak mampu, dan surat bukti kepemilikan rumah. 7) Sertakan rekomendasi dari ketua RT/RW. 8) Kirim pengajuan. 9) Tim verifikasi akan melakukan survei lokasi. 10) Jika disetujui, renovasi akan dilakukan berdasarkan anggaran yang tersedia.',
            ],
            [
                'kunci' => 'pros-027',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan program PKK melalui SIG-Udeung?',
                'kata_kunci' => ['PKK', 'pemberdayaan kesejahteraan keluarga', 'daftar PKK', 'kegiatan PKK'],
                'jawaban_atau_konten' => 'Untuk pendaftaran program PKK: 1) Login ke portal warga. 2) Pilih menu "Pemberdayaan Masyarakat" lalu "Program PKK". 3) Lihat daftar program PKK yang tersedia seperti program kesehatan, pendidikan, atau ekonomi keluarga. 4) Pilih program yang ingin diikuti. 5) Klik "Daftar" pada program yang dipilih. 6) Isi data pendukung sesuai program yang dipilih. 7) Kirim pendaftaran. 8) Ketua TP-PKK gampong akan menghubungi Anda untuk konfirmasi. 9) Anda akan diikutsertakan dalam kegiatan sesuai jadwal yang ditentukan. 10) Informasi perkembangan program akan dikirim melalui notifikasi.',
            ],
            [
                'kunci' => 'pros-028',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan Kartu Tanda Penduduk (KTP) melalui SIG-Udeung?',
                'kata_kunci' => ['KTP', 'kartu tanda penduduk', 'e-KTP', 'cetak KTP', 'pengurusan KTP'],
                'jawaban_atau_konten' => 'Cara mengajukan penerbitan KTP: 1) Login ke portal warga. 2) Pilih menu "Kependudukan" lalu "Pengajuan KTP". 3) Pilih jenis pengajuan: KTP baru, perubahan data, atau penggantian KTP rusak/hilang. 4) Isi data diri: NIK, nama, tanggal lahir, jenis kelamin, alamat, dan golongan darah. 5) Lampirkan KK, akta kelahiran, dan foto berwarna terbaru dengan latar belakang merah. 6) Untuk penggantian KTP hilang, lampirkan surat keterangan hilang dari polisi. 7) Kirim pengajuan. 8) Admin gampong akan memproses dan meneruskan ke disdukcapil. 9) Setelah selesai, Anda akan menerima notifikasi untuk mengambil KTP di kantor gampong atau disdukcapil. 10) KTP bisa diambil dalam waktu 7-14 hari kerja.',
            ],
            [
                'kunci' => 'pros-029',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan perubahan data pada Kartu Keluarga (KK) melalui SIG-Udeung?',
                'kata_kunci' => ['ubah KK', 'perubahan KK', 'kartu keluarga', 'update KK', 'edit KK'],
                'jawaban_atau_konten' => 'Untuk pengajuan perubahan data KK: 1) Login ke portal warga. 2) Pilih menu "Kependudukan" lalu "Perubahan Kartu Keluarga". 3) Pilih jenis perubahan: penambahan anggota keluarga, pengurangan anggota keluarga, atau perubahan data anggota. 4) Isi data yang akan diubah: nama, NIK, hubungan keluarga, atau status perkawinan. 5) Lampirkan dokumen pendukung sesuai jenis perubahan: surat nikah, surat cerai, akta kelahiran, atau surat kematian. 6) Kirim pengajuan. 7) Admin gampong akan memverifikasi dan memproses perubahan. 8) Data akan diperbarui di database kependudukan. 9) KK baru bisa diambil di kantor gampong atau disdukcapil. 10) Proses biasanya memakan waktu 3-5 hari kerja.',
            ],
            [
                'kunci' => 'pros-030',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan surat izin memandikan jenazah melalui SIG-Udeung?',
                'kata_kunci' => ['surat jenazah', 'memandikan jenazah', 'kematian jenazah', 'surat kematian'],
                'jawaban_atau_konten' => 'Cara mengajukan surat izin memandikan jenazah: 1) Buka portal warga SIG-Udeung. 2) Pilih menu "Pengajuan Surat" lalu "Surat Izin Memandikan Jenazah". 3) Isi data almarhum/almarhumah: NIK, nama lengkap, tanggal wafat, dan penyebab kematian. 4) Isi data pemohon: NIK, nama, hubungan dengan almarhum, dan alamat. 5) Lampirkan surat kematian dari rumah sakit atau dokter, KTP almarhum, dan KK. 6) Kirim pengajuan. 7) Admin gampong akan memproses penerbitan surat izin. 8) Surat izin bisa diambil di kantor gampong dalam waktu 1x24 jam untuk keperluan pemakaman segera.',
            ],
            [
                'kunci' => 'pros-031',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan bantuan pendidikan anak melalui SIG-Udeung?',
                'kata_kunci' => ['bantuan pendidikan', 'beasiswa', 'biaya sekolah', 'bantuan biaya pendidikan'],
                'jawaban_atau_konten' => 'Untuk mengajukan bantuan pendidikan: 1) Login ke portal warga. 2) Pilih menu "Pendidikan" lalu "Bantuan Pendidikan". 3) Isi data anak: NIK, nama, sekolah, kelas, dan prestasi akademik jika ada. 4) Isi data orang tua: NIK, nama, pekerjaan, penghasilan bulanan, dan jumlah tanggungan anak sekolah. 5) Lampirkan KTP orang tua, KK, rapor anak, surat keterangan kurang mampu dari RT/RW, dan bukti penghasilan. 6) Pilih jenis bantuan: SPP, seragam, buku tulis, atau biaya ujian. 7) Kirim pengajuan. 8) Tim verifikasi akan memproses data Anda. 9) Jika disetujui, bantuan akan disalurkan melalui rekening atau langsung ke sekolah. 10) Status pengajuan bisa dipantau melalui dashboard.',
            ],
            [
                'kunci' => 'pros-032',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan lansia ke program Lansia Sejahtera melalui SIG-Udeung?',
                'kata_kunci' => ['lansia', 'lansia sejahtera', 'program lansia', 'manula', 'lansia terlantar'],
                'jawaban_atau_konten' => 'Cara mendaftarkan lansia: 1) Login ke portal warga atau minta bantuan anak/keluarga. 2) Pilih menu "Program Sosial" lalu "Program Lansia Sejahtera". 3) Isi data lansia: NIK, nama, tanggal lahir, alamat, dan kondisi kesehatan. 4) Isi data keluarga terdekat: nama, hubungan, dan kontak yang bisa dihubungi. 5) Lampirkan KTP lansia, KK, surat keterangan dari puskesmas tentang kondisi kesehatan. 6) Unggah foto lansia terbaru. 7) Kirim pendaftaran. 8) Petugas kesehatan gampong akan melakukan kunjungan untuk verifikasi. 9) Lansia yang terdaftar akan mendapatkan layanan kesehatan rutin, bantuan sembako, dan kunjungan kader. 10) Informasi jadwal layanan akan dikirim melalui notifikasi.',
            ],
            [
                'kunci' => 'pros-033',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan usaha (SKU) melalui SIG-Udeung?',
                'kata_kunci' => ['SKU', 'surat keterangan usaha', 'surat usaha', 'izin usaha kecil'],
                'jawaban_atau_konten' => 'Untuk pengajuan SKU: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Usaha". 3) Isi data pemohon: NIK, nama, alamat, dan jenis usaha. 4) Isi data usaha: nama usaha, bidang usaha, alamat usaha, dan lama usaha berjalan. 5) Lampirkan KTP, KK, foto usaha, dan surat pernyataan tidak keberatan dari tetangga terdekat jika usaha berada di area pemukiman. 6) Jika usaha memerlukan izin khusus seperti izin makanan, lampirkan juga izin dari dinas terkait. 7) Kirim pengajuan. 8) Admin gampong akan memproses penerbitan SKU. 9) SKU bisa diambil di kantor gampong dalam waktu 2-3 hari kerja. 10) SKU berlaku selama 1 tahun dan bisa diperpanjang melalui portal.',
            ],
            [
                'kunci' => 'pros-034',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan tidak mampu (SKTM) melalui SIG-Udeung?',
                'kata_kunci' => ['SKTM', 'surat tidak mampu', 'surat keterangan miskin', 'tidak mampu'],
                'jawaban_atau_konten' => 'Cara mengajukan SKTM: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Tidak Mampu". 3) Isi data pemohon: NIK, nama, alamat, jumlah anggota keluarga, dan sumber penghasilan. 4) Jelaskan kondisi ekonomi: penghasilan bulanan, pekerjaan, dan jumlah tanggungan. 5) Lampirkan KTP, KK, surat keterangan dari RT/RW tentang kondisi tidak mampu, dan bukti penghasilan jika ada. 6) Untuk lansia atau difabel, lampirkan surat keterangan dari puskesmas. 7) Kirim pengajuan. 8) Admin gampong akan memverifikasi data. 9) SKTM akan diterbitkan dan bisa diambil di kantor gampong. 10) SKTM berlaku 6 bulan dan bisa diperpanjang.',
            ],
            [
                'kunci' => 'pros-035',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan domisili melalui SIG-Udeung?',
                'kata_kunci' => ['surat domisili', 'domisili', 'surat keterangan tinggal', 'bukti domisili'],
                'jawaban_atau_konten' => 'Untuk pengajuan surat domisili: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Domisili". 3) Isi data pemohon: NIK, nama, alamat lengkap, dan lama tinggal di alamat tersebut. 4) Jika bukan pemilik rumah, isi data pemilik rumah: nama, NIK, dan hubungan. 5) Lampirkan KTP, KK, bukti sewa atau surat izin tinggal dari pemilik rumah. 6) Kirim pengajuan. 7) Admin gampong akan memverifikasi data. 8) Surat keterangan domisili akan diterbitkan. 9) Surat bisa diambil di kantor gampong dalam waktu 1-2 hari kerja. 10) Surat domisili berlaku 6 bulan dan bisa diperpanjang.',
            ],
            [
                'kunci' => 'pros-036',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan penghasilan melalui SIG-Udeung?',
                'kata_kunci' => ['surat penghasilan', 'bukti penghasilan', 'surat gaji', 'surat keterangan bekerja'],
                'jawaban_atau_konten' => 'Cara mengajukan surat penghasilan: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Penghasilan". 3) Isi data pemohon: NIK, nama, pekerjaan, dan penghasilan bulanan. 4) Isi data tempat kerja: nama perusahaan/usaha, alamat, dan kontak yang bisa dihubungi. 5) Lampirkan KTP, KK, dan slip gaji 3 bulan terakhir atau surat keterangan dari tempat kerja. 6) Kirim pengajuan. 7) Admin gampong akan memverifikasi data. 8) Surat keterangan penghasilan akan diterbitkan. 9) Surat bisa diambil di kantor gampong dalam waktu 1-2 hari kerja. 10) Surat ini biasanya diperlukan untuk pengajuan kredit, beasiswa, atau bantuan sosial.',
            ],
            [
                'kunci' => 'pros-037',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan bebas narkoba melalui SIG-Udeung?',
                'kata_kunci' => ['surat bebas narkoba', 'narkoba', 'test narkoba', 'surat keterangan narkoba'],
                'jawaban_atau_konten' => 'Untuk pengajuan surat bebas narkoba: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Bebas Narkoba". 3) Isi data pemohon: NIK, nama, alamat, dan tujuan pengajuan (melamar kerja, sekolah, atau keperluan lainnya). 4) Lampirkan KTP dan KK. 5) Kirim pengajuan. 6) Anda akan diarahkan ke fasilitas kesehatan yang bekerja sama untuk melakukan tes urine. 7) Setelah hasil tes keluar dan dinyatakan negatif, admin gampong akan menerbitkan surat. 8) Surat bisa diambil di kantor gampong atau langsung diambil di fasilitas kesehatan. 9) Biaya tes ditanggung oleh pemohon. 10) Surat berlaku 6 bulan sejak diterbitkan.',
            ],
            [
                'kunci' => 'pros-038',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan waris melalui SIG-Udeung?',
                'kata_kunci' => ['surat waris', 'waris', 'harta warisan', 'surat keterangan ahli waris'],
                'jawaban_atau_konten' => 'Cara mengajukan surat keterangan waris: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Waris". 3) Isi data pewaris: NIK, nama, tanggal meninggal, danalamat terakhir. 4) Isi data ahli waris: NIK, nama, hubungan dengan pewaris, dan urutan ahli waris. 5) Lampirkan KTP pewaris (almarhum), KK, akta kematian, dan surat keterangan waris dari tokoh masyarakat atau imam desa. 6) Sertakan kesepakatan ahli waris yang ditandatangani seluruh ahli waris. 7) Kirim pengajuan. 8) Admin gampong akan memverifikasi data. 9) Surat keterangan waris akan diterbitkan. 10) Surat bisa diambil di kantor gampong dalam waktu 3-5 hari kerja.',
            ],
            [
                'kunci' => 'pros-039',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan hidup melalui SIG-Udeung?',
                'kata_kunci' => ['surat hidup', 'surat keterangan hidup', 'surat still alive', 'surat keterangan masih hidup'],
                'jawaban_atau_konten' => 'Untuk pengajuan surat keterangan hidup: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Hidup". 3) Isi data pemohon: NIK, nama, alamat, dan tujuan pengajuan (pensiun, klaim asuransi, atau keperluan bank). 4) Lampirkan KTP dan KK. 5) Kirim pengajuan. 6) Admin gampong akan memverifikasi keaktifan data kependudukan. 7) Surat keterangan hidup akan diterbitkan. 8) Surat bisa diambil di kantor gampong dalam waktu 1 hari kerja. 9) Surat ini membuktikan bahwa pemohon masih dalam kondisi hidup dan aktif sebagai penduduk. 10) Surat berlaku selama 1 bulan sejak diterbitkan.',
            ],
            [
                'kunci' => 'pros-040',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan pernah sekolah melalui SIG-Udeung?',
                'kata_kunci' => ['surat pernah sekolah', 'surat pendidikan', 'surat lulus', 'surat keterangan pendidikan'],
                'jawaban_atau_konten' => 'Cara mengajukan surat keterangan pernah sekolah: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Pernah Sekolah". 3) Isi data pemohon: NIK, nama, alamat, dan riwayat pendidikan. 4) Isi detail pendidikan: nama sekolah, alamat sekolah, tahun masuk, tahun lulus, dan ijazah terakhir. 5) Lampirkan KTP, KK, fotokopi ijazah terakhir, dan fotokopi rapor. 6) Kirim pengajuan. 7) Admin gampong akan memverifikasi data. 8) Surat keterangan pernah sekolah akan diterbitkan. 9) Surat bisa diambil di kantor gampong dalam waktu 2-3 hari kerja. 10) Surat ini biasanya diperlukan untuk melamar kerja atau melanjutkan pendidikan.',
            ],
            [
                'kunci' => 'pros-041',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan bantuan modal usaha untuk perempuan melalui SIG-Udeung?',
                'kata_kunci' => ['bantuan modal', 'modal usaha perempuan', 'pinjaman perempuan', 'usaha perempuan'],
                'jawaban_atau_konten' => 'Untuk mengajukan bantuan modal usaha perempuan: 1) Login ke portal warga. 2) Pilih menu "Ekonomi Desa" lalu "Bantuan Modal Usaha Perempuan". 3) Isi data pemohon: NIK, nama, alamat, dan usaha yang dijalankan. 4) Isi rencana penggunaan modal: jenis usaha, perkiraan kebutuhan modal, dan rencana pengembangan usaha. 5) Lampirkan KTP, KK, proposal usaha singkat, dan foto usaha. 6) Sertakan rekomendasi dari ketua PKK atau kelompok usaha. 7) Kirim pengajuan. 8) Tim verifikasi akan memproses dan melakukan wawancara. 9) Jika disetujui, dana akan dicairkan melalui rekening bank. 10) Penerima bantuan wajib melaporkan perkembangan usaha setiap bulan.',
            ],
            [
                'kunci' => 'pros-042',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan kegiatan posbindu melalui SIG-Udeung?',
                'kata_kunci' => ['posbindu', 'pos pembinaan terpadu', 'kesehatan lansia', 'penyakit tidak menular'],
                'jawaban_atau_konten' => 'Cara mendaftarkan kegiatan posbindu: 1) Login ke portal warga. 2) Pilih menu "Kesehatan" lalu "Posbindu". 3) Lihat jadwal kegiatan posbindu yang tersedia. 4) Klik "Daftar" untuk mengikuti sesi yang diinginkan. 5) Isi data kesehatan: tekanan darah, gula darah, kolesterol, dan berat badan terkini. 6) Pilih waktu yang tersedia untuk pemeriksaan. 7) Kirim pendaftaran. 8) Anda akan menerima konfirmasi jadwal dan lokasi. 9) Hadir tepat waktu dengan membawa kartu identitas. 10) Hasil pemeriksaan akan tercatat dalam database kesehatan gampong dan bisa diakses melalui portal.',
            ],
            [
                'kunci' => 'pros-043',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan janda/duda melalui SIG-Udeung?',
                'kata_kunci' => ['surat janda', 'surat duda', 'status janda', 'status duda', 'kematian pasangan'],
                'jawaban_atau_konten' => 'Untuk pengajuan surat keterangan janda/duda: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Janda/Duda". 3) Isi data pemohon: NIK, nama, alamat, dan status pernikahan. 4) Isi data pasangan yang meninggal: NIK, nama, dan tanggal meninggal. 5) Lampirkan KTP, KK, akta kematian pasangan, dan surat nikah asli. 6) Kirim pengajuan. 7) Admin gampong akan memverifikasi data. 8) Surat keterangan janda/duda akan diterbitkan. 9) Surat bisa diambil di kantor gampong dalam waktu 2-3 hari kerja. 10) Surat ini diperlukan untuk pengurusan pensiun, waris, atau pernikahan lagi.',
            ],
            [
                'kunci' => 'pros-044',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan pengalaman kerja melalui SIG-Udeung?',
                'kata_kunci' => ['surat pengalaman kerja', 'pengalaman kerja', 'surat referensi kerja', 'surat keterangan bekerja'],
                'jawaban_atau_konten' => 'Cara mengajukan surat pengalaman kerja: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Pengalaman Kerja". 3) Isi data pemohon: NIK, nama, alamat, dan data pekerjaan. 4) Isi detail pekerjaan: nama perusahaan, posisi, lama bekerja, dan deskripsi pekerjaan. 5) Lampirkan KTP, KK, surat pengalaman kerja dari perusahaan sebelumnya, dan fotokopi SK pengangkatan. 6) Kirim pengajuan. 7) Admin gampong akan memverifikasi data. 8) Surat keterangan pengalaman kerja akan diterbitkan. 9) Surat bisa diambil di kantor gampong dalam waktu 2-3 hari kerja. 10) Surat ini diperlukan untuk melamar pekerjaan baru.',
            ],
            [
                'kunci' => 'pros-045',
                'tipe' => 'prosedur',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan penerbitan surat keterangan bebas dari penyakit menular melalui SIG-Udeung?',
                'kata_kunci' => ['surat bebas penyakit', 'surat kesehatan', 'surat tidak menular', 'surat medis'],
                'jawaban_atau_konten' => 'Untuk pengajuan surat keterangan bebas penyakit menular: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Surat" lalu "Surat Keterangan Bebas Penyakit Menular". 3) Isi data pemohon: NIK, nama, alamat, dan tujuan pengajuan (melamar kerja, bepergian, atau keperluan lainnya). 4) Lampirkan KTP dan KK. 5) Kirim pengajuan. 6) Anda akan diarahkan ke puskesmas atau rumah sakit untuk pemeriksaan kesehatan. 7) Setelah dinyatakan sehat, hasil pemeriksaan akan dikirim ke admin gampong. 8) Surat keterangan bebas penyakit menular akan diterbitkan. 9) Surat bisa diambil di kantor gampong atau langsung di fasilitas kesehatan. 10) Surat berlaku 3 bulan sejak diterbitkan.',
            ],
        ];
    }

    public function getInformasiSistem(): array
    {
        return [
            [
                'kunci' => 'info-sys-001',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara login ke portal warga SIG-Udeung?',
                'kata_kunci' => ['login portal warga', 'cara login', 'masuk portal', 'akses portal'],
                'jawaban_atau_konten' => 'Untuk login ke portal warga SIG-Udeung: 1) Buka browser dan kunjungi alamat portal yang telah ditetapkan. 2) Pada halaman utama, masukkan NIK (Nomor Induk Kependudukan) Anda di kolom yang tersedia. 3) Masukkan Nomor Kartu Keluarga (No KK) sebagai password. 4) Klik tombol "Masuk" atau "Login". 5) Jika data sesuai, Anda akan diarahkan ke dashboard warga. 6) Jika lupa password, klik "Lupa Password" dan ikuti instruksi reset melalui email atau SMS. 7) Pastikan NIK dan No KK terdaftar di sistem kependudukan gampong untuk bisa login.',
            ],
            [
                'kunci' => 'info-sys-002',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara login ke panel admin SIG-Udeung?',
                'kata_kunci' => ['login admin', 'panel admin', 'admin login', 'masuk admin'],
                'jawaban_atau_konten' => 'Untuk login ke panel admin SIG-Udeung: 1) Buka browser dan kunjungi halaman admin panel. 2) Masukkan username admin yang telah didaftarkan. 3) Masukkan password admin. 4) Klik tombol "Login". 5) Jika berhasil, Anda akan diarahkan ke dashboard admin dengan menu dan fitur lengkap. 6) Jika lupa password, hubungi administrator sistem untuk reset. 7) Panel admin hanya bisa diakses oleh perangkat gampong yang memiliki hak akses. 8) Setelah selesai bekerja, selalu logout dengan klik tombol "Keluar" di pojok kanan atas.',
            ],
            [
                'kunci' => 'info-sys-003',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengajukan surat online di SIG-Udeung?',
                'kata_kunci' => ['ajukan surat online', 'surat online', 'pengajuan surat digital', 'e-surat'],
                'jawaban_atau_konten' => 'Cara mengajukan surat online: 1) Login ke portal warga dengan NIK dan No KK. 2) Di dashboard, cari dan klik menu "Pengajuan Surat". 3) Pilih jenis surat yang dibutuhkan dari daftar yang tersedia. 4) Isi semua kolom yang diminta dengan data yang benar dan lengkap. 5) Unggah dokumen pendukung yang diperlukan dalam format JPG, PNG, atau PDF dengan ukuran maksimal 2MB per file. 6) Periksa kembali data yang sudah diisi sebelum mengirim. 7) Klik "Kirim Pengajuan" untuk mengirim permohonan Anda. 8) Anda akan menerima nomor referensi yang bisa digunakan untuk melacak status pengajuan. 9) Tunggu proses verifikasi dari admin gampong.',
            ],
            [
                'kunci' => 'info-sys-004',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara memantau status pengajuan surat di SIG-Udeung?',
                'kata_kunci' => ['status pengajuan', 'pantau status', 'cek status surat', 'progress pengajuan'],
                'jawaban_atau_konten' => 'Untuk memantau status pengajuan: 1) Login ke portal warga. 2) Di dashboard, klik menu "Pengajuan Saya" atau "Riwayat Pengajuan". 3) Anda akan melihat daftar semua pengajuan yang pernah dibuat beserta statusnya. 4) Status pengajuan terdiri dari: Menunggu Verifikasi, Sedang Diproses, Disetujui, Ditolak, atau Selesai. 5) Klik pada pengajuan tertentu untuk melihat detail dan kronologi pemrosesan. 6) Jika pengajuan disetujui, Anda akan melihat tombol "Unduh Surat" untuk mengunduh file surat. 7) Jika pengajuan ditolak, alasan penolakan akan ditampilkan. 8) Notifikasi perubahan status juga akan dikirim melalui email atau WhatsApp.',
            ],
            [
                'kunci' => 'info-sys-005',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengunduh surat yang sudah jadi di SIG-Udeung?',
                'kata_kunci' => ['unduh surat', 'download surat', 'ambil surat', 'surat jadi'],
                'jawaban_atau_konten' => 'Cara mengunduh surat yang sudah jadi: 1) Login ke portal warga. 2) Pilih menu "Pengajuan Saya". 3) Cari pengajuan yang statusnya "Selesai" atau "Disetujui". 4) Klik pada pengajuan tersebut untuk melihat detail. 5) Klik tombol "Unduh Surat" atau "Download PDF". 6) File surat akan terunduh dalam format PDF ke perangkat Anda. 7) Simpan file di lokasi yang aman. 8) Surat digital memiliki QR Code sebagai tanda keaslian. 9) Anda bisa mencetak surat sesuai kebutuhan. 10) Jika mengalami kendala unduhan, hubungi admin gampong untuk bantuan.',
            ],
            [
                'kunci' => 'info-sys-006',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat berita dan pengumuman di SIG-Udeung?',
                'kata_kunci' => ['berita', 'pengumuman', 'kabar desa', 'informasi terbaru'],
                'jawaban_atau_konten' => 'Untuk melihat berita dan pengumuman: 1) Login ke portal warga. 2) Di dashboard utama, Anda akan melihat bagian "Berita Terkini" atau "Pengumuman Penting" di bagian atas halaman. 3) Klik judul berita atau pengumuman untuk membaca detailnya. 4) Anda juga bisa mengakses menu "Berita & Pengumuman" di sidebar untuk melihat semua archive berita. 5) Berita dan pengumuman dikelompokkan berdasarkan kategori: Umum, Pembangunan, Kesehatan, Pendidikan, dan Ekonomi. 6) Gunakan fitur pencarian untuk mencari berita tertentu. 7) Pengumuman penting akan ditandai dengan badge khusus. 8) Notifikasi pengumuman penting juga akan dikirim melalui WhatsApp.',
            ],
            [
                'kunci' => 'info-sys-007',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat profil gampong di SIG-Udeung?',
                'kata_kunci' => ['profil gampong', 'profil desa', 'tentang desa', 'informasi desa'],
                'jawaban_atau_konten' => 'Untuk melihat profil gampong: 1) Login ke portal warga. 2) Pilih menu "Profil Gampong" di sidebar atau klik logo gampong di pojok kiri atas. 3) Anda akan melihat informasi umum gampong: nama gampong, alamat, visi dan misi, serta struktur organisasi pemerintahan. 4) Lihat data demografi: jumlah penduduk, luas wilayah, dan jumlah dusun. 5) Lihat data pembangunan: anggaran tahun ini, proyek yang sedang berjalan, dan proyek yang sudah selesai. 6) Lihat galeri foto gampong dan video profil. 7) Lihat peta wilayah gampong dalam format interaktif. 8) Informasi profil gampong selalu diperbarui oleh admin.',
            ],
            [
                'kunci' => 'info-sys-008',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data penduduk di SIG-Udeung?',
                'kata_kunci' => ['data penduduk', 'daftar penduduk', 'cari penduduk', 'kependudukan'],
                'jawaban_atau_konten' => 'Untuk melihat data penduduk: 1) Login ke portal warga (hanya data diri sendiri dan keluarga). 2) Pilih menu "Kependudukan" lalu "Data Penduduk". 3) Untuk admin: login ke panel admin, pilih menu "Penduduk" lalu "Daftar Penduduk". 4) Gunakan fitur pencarian untuk mencari penduduk berdasarkan NIK, nama, atau alamat. 5) Filter data berdasarkan dusun, RT/RW, status, atau jenis kelamin. 6) Klik pada nama penduduk untuk melihat detail data. 7) Data yang tersedia meliputi: NIK, nama, tanggal lahir, alamat, pekerjaan, pendidikan, dan status keluarga. 8) Data hanya bisa diakses oleh yang berwenang sesuai hak akses masing-masing.',
            ],
            [
                'kunci' => 'info-sys-009',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengubah profil di SIG-Udeung?',
                'kata_kunci' => ['ubah profil', 'edit profil', 'update profil', 'perbarui profil'],
                'jawaban_atau_konten' => 'Cara mengubah profil: 1) Login ke portal warga. 2) Klik ikon profil atau nama Anda di pojok kanan atas. 3) Pilih "Pengaturan Profil" atau "Edit Profil". 4) Ubah data yang ingin diperbarui: nomor telepon, email, alamat, atau foto profil. 5) Untuk mengubah data kependudukan seperti nama atau alamat, Anda perlu mengajukan permohonan perubahan data melalui menu "Kependudukan". 6) Klik "Simpan Perubahan" setelah selesai mengedit. 7) Perubahan akan diverifikasi oleh admin sebelum berlaku. 8) Anda akan menerima notifikasi konfirmasi perubahan profil. 9) Pastikan data yang diubah sesuai dengan dokumen resmi.',
            ],
            [
                'kunci' => 'info-sys-010',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa saja fitur yang tersedia di dashboard warga SIG-Udeung?',
                'kata_kunci' => ['fitur dashboard', 'dashboard warga', 'menu warga', 'fitur portal'],
                'jawaban_atau_konten' => 'Dashboard warga SIG-Udeung memiliki fitur: 1) Profil Warga: melihat dan mengedit data profil. 2) Pengajuan Surat: membuat berbagai jenis surat pengajuan secara online. 3) Pengajuan Saya: memantau status semua pengajuan yang pernah dibuat. 4) Berita & Pengumuman: membaca informasi terbaru dari gampong. 5) Bantuan Sosial: mengajukan dan memantau bantuan sosial. 6) Kependudukan: melihat data kependudukan dan mengajukan perubahan. 7) Pendidikan: mendaftarkan anak sekolah dan program pendidikan lainnya. 8) Kesehatan: mendaftarkan posyandu dan melihat jadwal kesehatan. 9) Ekonomi Desa: mendaftarkan UMKM dan mengakses layanan ekonomi. 10) Pengaduan & Saran: menyampaikan pengaduan atau saran kepada gampong.',
            ],
            [
                'kunci' => 'info-sys-011',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa saja fitur yang tersedia di dashboard admin SIG-Udeung?',
                'kata_kunci' => ['fitur admin', 'dashboard admin', 'panel admin', 'fitur admin panel'],
                'jawaban_atau_konten' => 'Dashboard admin SIG-Udeung memiliki fitur: 1) Manajemen Penduduk: mengelola data kependudukan, menambah, mengedit, dan menghapus data. 2) Verifikasi Pengajuan: memproses dan memverifikasi semua pengajuan surat dari warga. 3) Manajemen Berita: membuat, mengedit, dan mempublikasikan berita serta pengumuman. 4) Manajemen Bantuan: mengelola program bantuan sosial dan memverifikasi penerima. 5) Laporan & Statistik: melihat laporan kependudukan, pengajuan, dan statistik gampong. 6) Manajemen User: mengelola akun warga dan hak akses. 7) Pengaturan Sistem: mengatur konfigurasi sistem dan template surat. 8) Backup Data: melakukan pencadangan data secara berkala. 9) Audit Trail: melacak semua aktivitas perubahan data dalam sistem.',
            ],
            [
                'kunci' => 'info-sys-012',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa itu bot Telegram SIG-Udeung?',
                'kata_kunci' => ['bot telegram', 'telegram bot', 'chatbot', 'bot desa'],
                'jawaban_atau_konten' => 'Bot Telegram SIG-Udeung adalah asisten virtual berbasis Telegram yang membantu warga Desa Udeung mengakses layanan desa secara cepat dan mudah. Bot ini terintegrasi dengan sistem SIG-Udeung dan memungkinkan warga: 1) Melihat profil gampong. 2) Memantau status pengajuan surat. 3) Mendapatkan informasi berita dan pengumuman terbaru. 4) Mengajukan pertanyaan seputar layanan desa. 5) Mencari informasi kependudukan. Bot beroperasi 24 jam sehari dan bisa diakses dari mana saja melalui aplikasi Telegram.',
            ],
            [
                'kunci' => 'info-sys-013',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara menggunakan bot Telegram SIG-Udeung?',
                'kata_kunci' => ['cara pakai bot', 'menggunakan bot', 'start bot', 'mulai bot'],
                'jawaban_atau_konten' => 'Cara menggunakan bot Telegram SIG-Udeung: 1) Buka aplikasi Telegram di smartphone Anda. 2) Cari bot dengan username @sigudeung_bot atau cari "SIG-Udeung Bot" di pencarian. 3) Klik "Start" atau kirim perintah "/start" untuk memulai. 4) Bot akan meminta Anda untuk verifikasi identitas dengan memasukkan NIK. 5) Setelah terverifikasi, Anda akan melihat menu utama dengan berbagai opsi. 6) Pilih menu dengan mengklik tombol yang tersedia atau ketik perintah sesuai panduan. 7) Ikuti instruksi yang diberikan bot untuk setiap layanan. 8) Jika memerlukan bantuan, ketik "/help" untuk melihat panduan lengkap.',
            ],
            [
                'kunci' => 'info-sys-014',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Pertanyaan apa saja yang bisa ditanyakan ke bot Telegram SIG-Udeung?',
                'kata_kunci' => ['pertanyaan bot', 'apa yang bisa ditanya', 'fitur chatbot', 'kapabilitas bot'],
                'jawaban_atau_konten' => 'Bot Telegram SIG-Udeung bisa menjawab pertanyaan: 1) "Status surat saya" untuk melihat progress pengajuan surat. 2) "Berita terbaru" untuk melihat berita gampong terkini. 3) "Profil gampong" untuk melihat informasi umum desa. 4) "Cara daftar" untuk panduan pendaftaran layanan. 5) "Jadwal posyandu" untuk melihat jadwal kesehatan. 6) "UMKM desa" untuk melihat daftar UMKM yang terdaftar. 7) "Anggaran desa" untuk melihat informasi anggaran. 8) "Kontak gampong" untuk mendapatkan nomor telepon penting. 9) "Cara login" untuk panduan masuk portal. 10) Bot juga bisa merespon pertanyaan umum seputar layanan desa.',
            ],
            [
                'kunci' => 'info-sys-015',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana keamanan data di SIG-Udeung?',
                'kata_kunci' => ['keamanan data', 'privasi data', 'pengamanan data', 'data aman'],
                'jawaban_atau_konten' => 'SIG-Udeung menerapkan keamanan data: 1) Enkripsi data saat transmisi menggunakan SSL/TLS. 2) Penyimpanan data sensitif dienkripsi di database. 3) Autentikasi dua faktor untuk akun admin. 4) Sistem hak akses berbasis peran (role-based access control). 5) Audit trail mencatat semua aktivitas perubahan data. 6) Backup data otomatis setiap hari. 7) Firewall dan proteksi dari serangan siber. 8) Data warga hanya bisa diakses oleh yang berwenang. 9) Sistem secara berkala melakukan penetrasi testing. 10) Kebijakan privasi data sesuai dengan peraturan perundangan yang berlaku di Indonesia.',
            ],
            [
                'kunci' => 'info-sys-016',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa saja syarat dan ketentuan penggunaan SIG-Udeung?',
                'kata_kunci' => ['syarat ketentuan', 'terms of service', 'aturan pakai', 'kebijakan penggunaan'],
                'jawaban_atau_konten' => 'Syarat dan ketentuan penggunaan SIG-Udeung: 1) Pengguna harus merupakan penduduk terdaftar di Desa Udeung. 2) Setiap pengguna hanya boleh memiliki satu akun. 3) Data yang diisi harus benar dan sesuai dokumen resmi. 4) Pengguna bertanggung jawab atas kerahasiaan akun masing-masing. 5) Penggunaan sistem untuk kepentingan pribadi yang sah. 6) Dilarang menggunakan sistem untuk tujuan yang melanggar hukum. 7) Pengguna wajib mematuhi etika digital saat berinteraksi. 8) Gampong berhak menangguhkan atau menghapus akun yang melanggar aturan. 9) Pengguna setuju untuk menerima notifikasi dari sistem. 10) Ketentuan ini dapat berubah sewaktu-waktu dan pengguna akan diberitahu.',
            ],
            [
                'kunci' => 'info-sys-017',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa yang harus dilakukan jika lupa password portal warga SIG-Udeung?',
                'kata_kunci' => ['lupa password', 'lupa kata sandi', 'reset password', 'password hilang'],
                'jawaban_atau_konten' => 'Jika lupa password: 1) Buka halaman login portal warga. 2) Klik link "Lupa Password" di bawah form login. 3) Masukkan NIK Anda. 4) Pilih metode reset: melalui email atau SMS. 5) Jika memilih email, masukkan alamat email yang terdaftar. 6) Jika memilih SMS, masukkan nomor telepon yang terdaftar. 7) Anda akan menerima kode OTP (One Time Password). 8) Masukkan kode OTP di halaman verifikasi. 9) Buat password baru yang kuat: minimal 8 karakter, kombinasi huruf besar, huruf kecil, angka, dan simbol. 10) Klik "Simpan" dan gunakan password baru untuk login.',
            ],
            [
                'kunci' => 'info-sys-018',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan akun baru di SIG-Udeung?',
                'kata_kunci' => ['daftar akun', 'registrasi', 'buat akun', 'register'],
                'jawaban_atau_konten' => 'Cara mendaftarkan akun baru: 1) Buka halaman utama SIG-Udeung. 2) Klik tombol "Daftar" atau "Registrasi". 3) Pilih jenis pendaftaran: Warga atau Admin. 4) Untuk pendaftaran warga: masukkan NIK yang valid dan terdaftar di gampong. 5) Sistem akan memverifikasi NIK dengan database kependudukan. 6) Jika NIK valid, lengkapi data: nama, email, nomor telepon, dan buat password. 7) Verifikasi akun melalui email atau SMS dengan memasukkan kode OTP. 8) Akun Anda sudah aktif dan bisa digunakan untuk login. 9) Jika NIK tidak ditemukan, hubungi admin gampong untuk pendaftaran data kependudukan terlebih dahulu.',
            ],
            [
                'kunci' => 'info-sys-019',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Berapa lama proses pengajuan surat di SIG-Udeung?',
                'kata_kunci' => ['lama proses', 'waktu proses', 'berapa lama', 'estimasi waktu'],
                'jawaban_atau_konten' => 'Estimasi waktu proses pengajuan surat di SIG-Udeung: 1) Surat keterangan domisili: 1-2 hari kerja. 2) Surat keterangan tidak mampu: 1-2 hari kerja. 3) Surat keterangan usaha: 2-3 hari kerja. 4) Surat pengantar nikah: 2-3 hari kerja. 5) Surat keterangan catatan kepolisian (SKCK): 2-3 hari kerja. 6) Surat keterangan waris: 3-5 hari kerja. 7) Pengajuan bantuan sosial: 3-7 hari kerja. 8) Pendaftaran BPJS: 5-7 hari kerja. 9) Perubahan data kependudukan: 3-5 hari kerja. 10) Waktu di atas adalah estimasi dan dapat berubah tergantung kelengkapan dokumen dan beban kerja admin.',
            ],
            [
                'kunci' => 'info-sys-020',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apakah SIG-Udeung bisa diakses melalui smartphone?',
                'kata_kunci' => ['akses smartphone', 'mobile', 'hp android', 'aplikasi mobile'],
                'jawaban_atau_konten' => 'Ya, SIG-Udeung bisa diakses melalui smartphone: 1) Portal web SIG-Udeung dirancang responsif dan bisa diakses melalui browser smartphone. 2) Buka browser Chrome, Safari, atau browser lainnya di smartphone. 3) Kunjungi alamat portal SIG-Udeung. 4) Login seperti biasa menggunakan NIK dan No KK. 5) Tampilan akan menyesuaikan ukuran layar smartphone Anda. 6) Semua fitur yang tersedia di desktop juga tersedia di versi mobile. 7) Selain portal web, SIG-Udeung juga bisa diakses melalui bot Telegram yang bisa digunakan di smartphone. 8) Untuk pengalaman terbaik, gunakan browser terbaru dan koneksi internet stabil.',
            ],
            [
                'kunci' => 'info-sys-021',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa yang harus dilakukan jika mengalami kendala teknis di SIG-Udeung?',
                'kata_kunci' => ['kendala teknis', 'error', 'masalah teknis', 'gangguan sistem'],
                'jawaban_atau_konten' => 'Jika mengalami kendala teknis: 1) Coba refresh halaman browser Anda. 2) Bersihkan cache dan cookies browser. 3) Pastikan koneksi internet Anda stabil. 4) Coba gunakan browser yang berbeda (Chrome, Firefox, Edge). 5) Jika masih bermasalah, catat pesan error yang muncul. 6) Hubungi admin gampong melalui WhatsApp atau telepon yang tertera di halaman kontak. 7) Kirimkan screenshot kendala yang Anda alami. 8) Sertakan NIK dan detail langkah yang sudah dilakukan. 9) Admin akan membantu menyelesaikan kendala teknis. 10) Untuk gangguan sistem yang meluas, pengumuman pemeliharaan akan ditampilkan di portal.',
            ],
            [
                'kunci' => 'info-sys-022',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara menghubungi admin SIG-Udeung?',
                'kata_kunci' => ['hubungi admin', 'kontak admin', 'bantuan admin', 'telepon admin'],
                'jawaban_atau_konten' => 'Untuk menghubungi admin SIG-Udeung: 1) Login ke portal warga. 2) Klik menu "Bantuan" atau "Hubungi Kami" di sidebar. 3) Anda akan melihat informasi kontak admin: nomor telepon, email, dan WhatsApp. 4) Kirim pesan melalui WhatsApp untuk respon tercepat. 5) Sertakan NIK dan keluhan atau pertanyaan Anda. 6) Anda juga bisa datang langsung ke kantor gampong pada jam kerja (Senin-Jumat, 08.00-16.00). 7) Admin akan merespon dalam waktu 1x24 jam pada hari kerja. 8) Untuk kendala darurat di luar jam kerja, hubungi nomor telepon darurat yang tertera.',
            ],
            [
                'kunci' => 'info-sys-023',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apakah penggunaan SIG-Udeung dikenakan biaya?',
                'kata_kunci' => ['biaya', 'gratis', 'bayar', 'tarif', 'pembayaran'],
                'jawaban_atau_konten' => 'Informasi biaya penggunaan SIG-Udeung: 1) Akses dan penggunaan portal SIG-Udeung adalah GRATIS untuk semua warga. 2) Tidak ada biaya langganan atau biaya pendaftaran akun. 3) Biaya administrasi surat mengikuti ketentuan gampong yang berlaku (jika ada). 4) Untuk layanan tertentu seperti pengurusan BPJS atau tes kesehatan, biaya mengikuti ketentuan penyedia layanan. 5) Pembayaran biaya administrasi bisa dilakukan melalui transfer bank atau tunai di kantor gampong. 6) Setiap biaya akan diinformasikan dengan jelas sebelum pengajuan diproses. 7) Tidak ada biaya tersembunyi dalam penggunaan sistem.',
            ],
            [
                'kunci' => 'info-sys-024',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengubah nomor telepon atau email di SIG-Udeung?',
                'kata_kunci' => ['ubah nomor telepon', 'ubah email', 'update kontak', 'ganti nomor'],
                'jawaban_atau_konten' => 'Cara mengubah nomor telepon atau email: 1) Login ke portal warga. 2) Klik ikon profil di pojok kanan atas. 3) Pilih "Pengaturan Akun". 4) Klik "Edit" pada bagian kontak. 5) Ubah nomor telepon atau email yang baru. 6) Masukkan password untuk konfirmasi perubahan. 7) Sistem akan mengirim kode verifikasi ke kontak baru Anda. 8) Masukkan kode verifikasi untuk mengkonfirmasi perubahan. 9) Klik "Simpan Perubahan". 10) Perubahan akan langsung berlaku dan notifikasi konfirmasi akan dikirim ke kontak lama Anda.',
            ],
            [
                'kunci' => 'info-sys-025',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat anggaran gampong di SIG-Udeung?',
                'kata_kunci' => ['anggaran desa', 'anggaran gampong', 'APBDes', 'keuangan desa'],
                'jawaban_atau_konten' => 'Untuk melihat anggaran gampong: 1) Login ke portal warga. 2) Pilih menu "Keuangan Desa" atau "Anggaran Gampong". 3) Anda akan melihat ringkasan anggaran tahun berjalan. 4) Lihat rincian Pendapatan Asli Desa (PAD), dana transfer, dan other income. 5) Lihat rincian belanja: bidang pemerintahan, pembangunan, kemasyarakatan, dan pemberdayaan. 6) Klik pada program atau kegiatan untuk melihat detail anggaran. 7) Lihat capaian realisasi anggaran sampai dengan bulan berjalan. 8) Data anggaran diperbarui setiap bulan oleh admin. 9) Transparansi anggaran merupakan hak setiap warga sesuai UU Desa.',
            ],
            [
                'kunci' => 'info-sys-026',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat peta gampong di SIG-Udeung?',
                'kata_kunci' => ['peta desa', 'peta gampong', 'maps', 'pemetaan'],
                'jawaban_atau_konten' => 'Untuk melihat peta gampong: 1) Login ke portal warga. 2) Pilih menu "Peta Gampong" atau "Pemetaan". 3) Anda akan melihat peta interaktif wilayah Desa Udeung. 4) Gunakan fitur zoom in dan zoom out untuk melihat detail area tertentu. 5) Klik pada marker untuk melihat informasi lokasi: nama dusun, jumlah penduduk, dan fasilitas umum. 6) Lihat batas wilayah gampong dan batas dusun. 7) Temukan lokasi fasilitas publik: kantor gampong, sekolah, puskesmas, masjid, dan pasar. 8) Gunakan fitur pencarian untuk menemukan alamat tertentu. 9) Peta diperbarui secara berkala berdasarkan data survei terbaru.',
            ],
            [
                'kunci' => 'info-sys-027',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Apa yang dimaksud dengan Sistem Informasi Geospasial (SIG) di SIG-Udeung?',
                'kata_kunci' => ['SIG', 'sistem informasi geospasial', 'geospasial', 'gis'],
                'jawaban_atau_konten' => 'SIG dalam SIG-Udeung adalah Sistem Informasi Geospasial yang merupakan teknologi untuk mengelola dan menganalisis data berbasis lokasi geografis. Dalam konteks Desa Udeung, SIG digunakan untuk: 1) Pemetaan wilayah gampong secara digital. 2) Pemetaan aset dan infrastruktur desa. 3) Pemetaan program-program pembangunan. 4) Analisis data kependudukan berbasis lokasi. 5) Perencanaan pembangunan berbasis peta. 6) Monitoring dan evaluasi program desa. 7) Transparansi anggaran melalui peta interaktif. SIG membantu perangkat gampong dalam pengambilan keputusan berbasis data spasial yang akurat.',
            ],
            [
                'kunci' => 'info-sys-028',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data UMKM di SIG-Udeung?',
                'kata_kunci' => ['data UMKM', 'daftar UMKM', ' direktori UMKM', 'usaha desa'],
                'jawaban_atau_konten' => 'Untuk melihat data UMKM: 1) Login ke portal warga. 2) Pilih menu "Ekonomi Desa" lalu "Direktori UMKM". 3) Anda akan melihat daftar UMKM yang terdaftar di gampong. 4) Gunakan fitur pencarian berdasarkan nama usaha atau jenis usaha. 5) Filter berdasarkan kategori: makanan, minuman, kerajinan, jasa, atau lainnya. 6) Klik pada nama UMKM untuk melihat detail: nama usaha, pemilik, alamat, nomor telepon, dan foto produk. 7) Hubungi UMKM langsung melalui nomor telepon yang tersedia. 8) Anda juga bisa melihat UMKM terdekat dari lokasi Anda menggunakan fitur peta. 9) Data UMKM diperbarui secara berkala oleh admin.',
            ],
            [
                'kunci' => 'info-sys-029',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat jadwal kegiatan di SIG-Udeung?',
                'kata_kunci' => ['jadwal kegiatan', 'kalender acara', 'agenda desa', 'kegiatan gampong'],
                'jawaban_atau_konten' => 'Untuk melihat jadwal kegiatan: 1) Login ke portal warga. 2) Pilih menu "Kalender" atau "Jadwal Kegiatan". 3) Anda akan melihat kalender interaktif dengan semua kegiatan gampong. 4) Lihat kegiatan berdasarkan hari, minggu, atau bulan. 5) Klik pada kegiatan untuk melihat detail: waktu, lokasi, dan deskripsi. 6) Filter kegiatan berdasarkan kategori: pembangunan, kesehatan, pendidikan, keagamaan, atau sosial. 7) Setel pengingat untuk kegiatan penting yang ingin Anda ikuti. 8) Anda juga bisa mengajukan kegiatan baru melalui menu "Usul Kegiatan". 9) Jadwal juga akan dikirim melalui notifikasi ke email atau WhatsApp.',
            ],
            [
                'kunci' => 'info-sys-030',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data RT/RW di SIG-Udeung?',
                'kata_kunci' => ['data RT', 'data RW', 'RT RW', 'rukun tetangga', 'rukun warga'],
                'jawaban_atau_konten' => 'Untuk melihat data RT/RW: 1) Login ke portal warga. 2) Pilih menu "Kependudukan" lalu "Data RT/RW". 3) Anda akan melihat daftar RT dan RW yang ada di gampong. 4) Pilih dusun untuk melihat RT/RW di wilayah tersebut. 5) Klik pada RT atau RW tertentu untuk melihat detail: nama ketua RT/RW, alamat, jumlah anggota, dan jumlah KK. 6) Lihat peta distribusi RT/RW. 7) Lihat data demografi per RT/RW: jumlah penduduk, usia, pekerjaan, dan pendidikan. 8) Data diperbarui berdasarkan registrasi terbaru. 9) Untuk perubahan data RT/RW, hubungi admin gampong.',
            ],
            [
                'kunci' => 'info-sys-031',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data program pembangunan di SIG-Udeung?',
                'kata_kunci' => ['program pembangunan', 'proyek desa', 'pembangunan gampong', 'kegiatan fisik'],
                'jawaban_atau_konten' => 'Untuk melihat data program pembangunan: 1) Login ke portal warga. 2) Pilih menu "Pembangunan" atau "Program Desa". 3) Anda akan melihat daftar program pembangunan yang sedang berjalan dan yang sudah selesai. 4) Filter berdasarkan tahun anggaran atau jenis program. 5) Klik pada program untuk melihat detail: nama program, anggaran, sumber dana, lokasi, dan progres. 6) Lihat foto dokumentasi pelaksanaan program. 7) Lihat realisasi anggaran per program. 8) Berikan saran atau masukan terhadap program yang sedang berjalan. 9) Data program diperbarui oleh admin setiap ada perkembangan.',
            ],
            [
                'kunci' => 'info-sys-032',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data penerima bantuan sosial di SIG-Udeung?',
                'kata_kunci' => ['penerima bansos', 'data penerima bantuan', 'daftar bansos', 'penerima manfaat'],
                'jawaban_atau_konten' => 'Untuk melihat data penerima bantuan sosial: 1) Login ke portal warga. 2) Pilih menu "Bantuan Sosial" lalu "Data Penerima". 3) Anda akan melihat daftar penerima bantuan sesuai program. 4) Filter berdasarkan jenis bantuan: bantuan pangan, sembako, biaya pendidikan, atau bantuan lainnya. 5) Filter berdasarkan tahun penyaluran. 6) Klik pada nama penerima untuk melihat detail: nama, alamat, jenis bantuan, dan nominal. 7) Lihat foto penyaluran bantuan. 8) Transparansi data penerima bantuan merupakan bagian dari good governance. 9) Jika menemukan ketidaksesuaian, sampaikan melalui menu pengaduan.',
            ],
            [
                'kunci' => 'info-sys-033',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data demografi gampong di SIG-Udeung?',
                'kata_kunci' => ['data demografi', 'demografi desa', 'statistik penduduk', 'jumlah penduduk'],
                'jawaban_atau_konten' => 'Untuk melihat data demografi gampong: 1) Login ke portal warga. 2) Pilih menu "Statistik" atau "Data Demografi". 3) Anda akan melihat ringkasan data kependudukan gampong. 4) Lihat grafik distribusi berdasarkan jenis kelamin. 5) Lihat grafik distribusi berdasarkan usia (anak-anak, produktif, lansia). 6) Lihat distribusi berdasarkan dusun atau RT/RW. 7) Lihat data pendidikan: lulusan SD, SMP, SMA, dan perguruan tinggi. 8) Lihat data pekerjaan: petani, pedagang, buruh, PNS, dan lainnya. 9) Lihat data agama dan suku bangsa. 10) Data demografi diperbarui setiap ada perubahan data kependudukan.',
            ],
            [
                'kunci' => 'info-sys-034',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat laporan kegiatan gampong di SIG-Udeung?',
                'kata_kunci' => ['laporan kegiatan', 'laporan gampong', 'report', 'laporan tahunan'],
                'jawaban_atau_konten' => 'Untuk melihat laporan kegiatan gampong: 1) Login ke portal warga. 2) Pilih menu "Laporan" atau "Laporan Gampong". 3) Pilih periode laporan: bulanan, triwulan, semesteran, atau tahunan. 4) Pilih jenis laporan: laporan keuangan, laporan pembangunan, laporan kependudukan, atau laporan menyeluruh. 5) Lihat ringkasan laporan dalam format grafik dan tabel. 6) Unduh laporan dalam format PDF untuk arsip pribadi. 7) Laporan tahunan menampilkan pencapaian seluruh program gampong. 8) Laporan juga tersedia dalam format cetak di kantor gampong. 9) Transparansi laporan merupakan hak setiap warga.',
            ],
            [
                'kunci' => 'info-sys-035',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data keluarga di SIG-Udeung?',
                'kata_kunci' => ['data keluarga', 'daftar keluarga', 'kartu keluarga', 'data KK'],
                'jawaban_atau_konten' => 'Untuk melihat data keluarga: 1) Login ke portal warga dengan NIK Anda. 2) Pilih menu "Kependudukan" lalu "Data Keluarga". 3) Anda akan melihat data Kartu Keluarga Anda. 4) Lihat daftar anggota keluarga: nama, NIK, hubungan, dan status. 5) Lihat detail masing-masing anggota: tanggal lahir, pekerjaan, pendidikan, dan alamat. 6) Lihat riwayat perubahan data keluarga. 7) Jika ingin menambah atau mengurangi anggota keluarga, ajukan permohonan perubahan. 8) Data keluarga hanya bisa diakses oleh anggota keluarga yang bersangkutan. 9) Hubungi admin jika terdapat kesalahan data.',
            ],
            [
                'kunci' => 'info-sys-036',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengaktifkan notifikasi di SIG-Udeung?',
                'kata_kunci' => ['notifikasi', 'aktifkan notif', 'pemberitahuan', 'alert'],
                'jawaban_atau_konten' => 'Cara mengaktifkan notifikasi: 1) Login ke portal warga. 2) Klik ikon profil lalu pilih "Pengaturan Notifikasi". 3) Pilih metode notifikasi: email, SMS, atau WhatsApp. 4) Aktifkan notifikasi untuk kategori: status pengajuan surat, berita gampong, jadwal kegiatan, dan pengumuman penting. 5) Atur frekuensi notifikasi: real-time, harian, atau mingguan. 6) Masukkan alamat email dan nomor telepon yang aktif. 7) Klik "Simpan Pengaturan". 8) Anda akan menerima notifikasi sesuai pengaturan yang dipilih. 9) Nonaktifkan notifikasi yang tidak diperlukan untuk menghindari spam. 10) Pengaturan bisa diubah sewaktu-waktu.',
            ],
            [
                'kunci' => 'info-sys-037',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat galeri foto dan video gampong di SIG-Udeung?',
                'kata_kunci' => ['galeri foto', 'galeri video', 'foto gampong', 'video desa'],
                'jawaban_atau_konten' => 'Untuk melihat galeri foto dan video: 1) Login ke portal warga. 2) Pilih menu "Galeri" di sidebar. 3) Anda akan melihat galeri foto dan video yang terbagi dalam album. 4) Lihat album berdasarkan kategori: kegiatan desa, pembangunan, budaya, alam, dan lainnya. 5) Klik pada foto untuk melihat dalam ukuran penuh. 6) Gunakan fitur slideshow untuk melihat foto secara otomatis. 7) Putar video profil gampong atau dokumentasi kegiatan. 8) Unduh foto atau video yang Anda butuhkan. 9) Upload foto atau video kegiatan gampong melalui menu upload (hanya admin yang bisa). 10) Galeri diperbarui secara berkala oleh admin.',
            ],
            [
                'kunci' => 'info-sys-038',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data keuangan desa di SIG-Udeung?',
                'kata_kunci' => ['keuangan desa', 'APBDes', 'realisasi anggaran', 'laporan keuangan'],
                'jawaban_atau_konten' => 'Untuk melihat data keuangan desa: 1) Login ke portal warga. 2) Pilih menu "Keuangan Desa" atau "APBDes". 3) Lihat ringkasan anggaran pendapatan dan belanja desa tahun berjalan. 4) Lihat rincian sumber pendapatan: dana desa, ADD, BDH, dan PAD. 5) Lihat rincian belanja: pemerintahan, pembangunan, kemasyarakatan, dan pemberdayaan. 6) Lihat realisasi anggaran per bulan dalam grafik. 7) Bandingkan target dan realisasi anggaran. 8) Unduh laporan keuangan dalam format PDF. 9) Transparansi keuangan desa merupakan kewajiban sesuai UU No. 6 Tahun 2014 tentang Desa.',
            ],
            [
                'kunci' => 'info-sys-039',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara melihat data aset desa di SIG-Udeung?',
                'kata_kunci' => ['aset desa', 'asset gampong', 'inventaris', 'barang milik desa'],
                'jawaban_atau_konten' => 'Untuk melihat data aset desa: 1) Login ke portal warga. 2) Pilih menu "Aset Desa" atau "Inventaris". 3) Anda akan melihat daftar aset yang dimiliki gampong. 4) Filter aset berdasarkan kategori: tanah, bangunan, kendaraan, inventaris kantor, dan alat berat. 5) Klik pada aset untuk melihat detail: nama aset, lokasi, tahun perolehan, kondisi, dan nilai. 6) Lihat foto aset terkini. 7) Lihat riwayat perawatan dan pemeliharaan aset. 8) Lihat peta lokasi aset. 9) Data aset diperbarui setiap ada penambahan atau pengurangan aset. 10) Transparansi aset desa merupakan bagian dari akuntabilitas pengelolaan desa.',
            ],
            [
                'kunci' => 'info-sys-040',
                'tipe' => 'informasi',
                'pertanyaan_atau_topik' => 'Bagaimana cara memberikan saran atau masukan untuk pengembangan SIG-Udeung?',
                'kata_kunci' => ['saran', 'masukan', 'feedback', 'kritik', 'usul'],
                'jawaban_atau_konten' => 'Untuk memberikan saran atau masukan: 1) Login ke portal warga. 2) Pilih menu "Saran & Masukan" atau "Hubungi Kami". 3) Pilih jenis: saran, masukan, atau kritik. 4) Isi form dengan detail saran atau masukan Anda. 5) Jelaskan bagian sistem yang ingin diperbaiki atau ditambah. 6) Kirim saran. 7) Tim pengelola SIG-Udeung akan meninjau setiap saran yang masuk. 8) Jika saran diterapkan, Anda akan mendapat apresiasi. 9) Anda juga bisa mengirim saran melalui email ke alamat yang tertera di portal. 10) Pengembangan sistem berkelanjutan sangat mengandung partisipasi aktif dari seluruh warga.',
            ],
        ];
    }
}
