<?php

namespace Database\Seeders\knowledge;

class BotKnowledgeFaqKesehatanEkonomi
{
    public function getFaqKesehatan(): array
    {
        return [
            [
                'kunci' => 'faq-kes-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana lokasi Puskesmas terdekat dari Gampong Udeung?',
                'kata_kunci' => ['puskesmas', 'lokasi', 'tempat', 'kesehatan', 'rumah sakit'],
                'jawaban_atau_konten' => 'Puskesmas terdekat dari Gampong Udeung adalah Puskesmas Kecamatan yang berjarak sekitar 5-7 km. Anda bisa menuju ke sana menggunakan kendaraan pribadi atau angkutan umum. Jam operasional Puskesmas biasanya Senin-Sabtu pukul 08.00-14.00 WIB. Untuk informasi lebih lanjut, silakan hubungi kantor gampong.',
            ],
            [
                'kunci' => 'faq-kes-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jam buka Puskesmas berapa?',
                'kata_kunci' => ['jam', 'buka', 'puskesmas', 'waktu', 'operasional'],
                'jawaban_atau_konten' => 'Puskesmas Kecamatan buka setiap hari Senin sampai Sabtu pukul 08.00 hingga 14.00 WIB. Pada hari Minggu dan hari libur nasional, Puskesmas tutup kecuali untuk layanan gawat darurat. Untuk keadaan darurat di luar jam operasional, silakan hubungi nomor darurat atau datang ke IGD rumah sakit terdekat.',
            ],
            [
                'kunci' => 'faq-kes-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Layanan apa saja yang tersedia di Puskesmas?',
                'kata_kunci' => ['layanan', 'puskesmas', 'periksa', 'pengobatan'],
                'jawaban_atau_konten' => 'Puskesmas menyediakan berbagai layanan kesehatan meliputi: pemeriksaan umum, persalinan, imunisasi anak, pelayanan KB, perawatan ibu hamil, pengobatan penyakit dalam, pelayanan gigi dan mulut, laboratorium sederhana, dan pelayanan gizi. Semua layanan ini bisa diakses dengan Kartu Indonesia Sehat atau BPJS Kesehatan.',
            ],
            [
                'kunci' => 'faq-kes-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa biaya berobat di Puskesmas?',
                'kata_kunci' => ['biaya', 'bayar', 'gratis', 'puskesmas', 'obat'],
                'jawaban_atau_konten' => 'Bagi pemegang Kartu Indonesia Sehat (KIS) atau BPJS Kesehatan kelas II dan III, berobat di Puskesmas tidak dipungut biaya alias gratis termasuk obat-obatan. Untuk yang tidak memiliki jaminan kesehatan, biaya administrasi sangat terjangkau sesuai ketentuan pemerintah daerah. Silakan tanyakan ke bagian pendaftaran untuk info lebih lengkap.',
            ],
            [
                'kunci' => 'faq-kes-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kapan jadwal Posyandu di Gampong Udeung?',
                'kata_kunci' => ['posyandu', 'jadwal', 'balita', 'ibu hamil', 'kader'],
                'jawaban_atau_konten' => 'Posyandu di Gampong Udeung diadakan setiap tanggal 10 setiap bulannya. Kegiatan dimulai pukul 08.00 hingga selesai di Balai Desa atau pos yang sudah ditentukan. Layanan yang tersedia meliputi penimbangan balita, pemeriksaan ibu hamil, pemberian vitamin A, imunisasi, dan penyuluhan kesehatan. Ibu-ibu hamil dan ibu yang memiliki balita diharapkan hadir.',
            ],
            [
                'kunci' => 'faq-kes-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Posyandu melayani siapa saja?',
                'kata_kunci' => ['posyandu', 'layanan', 'siapa', 'balita', 'hamil'],
                'jawaban_atau_konten' => 'Posyandu melayani ibu hamil, bayi, dan balita di bawah usia 5 tahun. Selain itu, posyandu juga melayani pemeriksaan kesehatan lansia dan pemberian makanan tambahan bagi balita gizi kurang. Semua warga gampong bisa memanfaatkan layanan posyandu secara gratis.',
            ],
            [
                'kunci' => 'faq-kes-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana bisa menemukan bidan desa?',
                'kata_kunci' => ['bidan', 'desa', 'persalinan', 'hamil', 'kontak'],
                'jawaban_atau_konten' => 'Bidan desa Gampong Udeung bertugas di Poskesdes atau bisa dikunjungi di rumah dinasnya. Anda bisa menghubungi kantor gampong untuk mendapatkan nomor telepon bidan desa. Bidan desa melayani pemeriksaan kehamilan, persalinan normal, perawatan pasca persalinan, dan konseling kesehatan reproduksi. Untuk persalinan darurat, segera hubungi bidan desa atau rujuk ke Puskesmas.',
            ],
            [
                'kunci' => 'faq-kes-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Layanan persalinan di bidan desa gratis?',
                'kata_kunci' => ['bidan', 'persalinan', 'gratis', 'biaya', 'melahirkan'],
                'jawaban_atau_konten' => 'Persalinan di bidan desa bisa dilakukan secara gratis bagi pemegang BPJS Kesehatan atau KIS. Untuk yang tidak memiliki jaminan kesehatan, biaya persalinan di bidan desa sangat terjangkau dan bisa dicicil. Jika persalinan memerlukan tindakan khusus, bidan akan merujuk ke Puskesmas atau rumah sakit.',
            ],
            [
                'kunci' => 'faq-kes-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftar BPJS Kesehatan?',
                'kata_kunci' => ['bpjs', 'daftar', 'kesehatan', 'kis', 'jaminan'],
                'jawaban_atau_konten' => 'Cara mendaftar BPJS Kesehatan: 1) Siapkan KTP elektronik dan KK. 2) Kunjungi kantor BPJS Kesehatan terdekat atau kantor camat. 3) Isi formulir pendaftaran. 4) Pilih kelas perawatan (I, II, atau III). 5) Bayar iuran pertama. Untuk warga kurang mampu, bisa mendaftar melalui program JKN-KIS PBI (Penerima Bantuan Iuran) yang iurannya ditanggung pemerintah. Pendaftaran juga bisa dilakukan secara online melalui aplikasi Mobile JKN.',
            ],
            [
                'kunci' => 'faq-kes-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa iuran BPJS Kesehatan per bulan?',
                'kata_kunci' => ['bpjs', 'iuran', 'bayar', 'premi', 'kelas'],
                'jawaban_atau_konten' => 'Iuran BPJS Kesehatan per bulan: Kelas I sekitar Rp 150.000, Kelas II sekitar Rp 100.000, dan Kelas III sekitar Rp 42.000 per orang. Untuk peserta PBI (Penerima Bantuan Iuan), iuran ditanggung sepenuhnya oleh pemerintah. Iuran harus dibayarkan paling lambat tanggal 10 setiap bulannya. Keterlambatan pembayaran akan mengakibatkan tunggakan dan hak layanan terhenti sementara.',
            ],
            [
                'kunci' => 'faq-kes-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara klaim BPJS Kesehatan?',
                'kata_kunci' => ['bpjs', 'klaim', 'tagihan', 'pengajuan', 'rumah sakit'],
                'jawaban_atau_konten' => 'Untuk klaim BPJS Kesehatan di faskes tingkat pertama seperti Puskesmas atau klinik, peserta hanya perlu membawa kartu BPJS dan KTP. Tidak perlu membayar di muka karena faskes akan mengklaim langsung ke BPJS. Untuk rujukan ke rumah sakit, pastikan surat rujukan dari faskes tingkat pertama sudah terbit. Klaim rawat jalan dan rawat inap ditanggung sesuai ketentuan BPJS.',
            ],
            [
                'kunci' => 'faq-kes-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jadwal imunisasi anak lengkap kapan saja?',
                'kata_kunci' => ['imunisasi', 'anak', 'vaksin', 'jadwal', 'bayi'],
                'jawaban_atau_konten' => 'Jadwal imunisasi anak di Indonesia: Bayi baru lahir mendapatkan Hepatitis B (HB-0) dalam 24 jam pertama. Usia 2 bulan: DPT-HB-Hib 1, PCV 1, Rotavirus 1. Usia 4 bulan: DPT-HB-Hib 2, PCV 2, Rotavirus 2. Usia 6 bulan: DPT-HB-Hib 3, PCV 3, Rotavirus 3. Usia 9 bulan: Campak 1. Usia 12 bulan: Campak 2. Usia 18 bulan: DPT-HB-Hib booster, MR booster. Imunisasi tersedia gratis di Puskesmas dan Posyandu.',
            ],
            [
                'kunci' => 'faq-kes-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah imunisasi itu wajib?',
                'kata_kunci' => ['imunisasi', 'wajib', 'hukum', 'anak', 'vaksin'],
                'jawaban_atau_konten' => 'Ya, imunisasi diwajibkan oleh pemerintah berdasarkan Undang-Undang No. 18 Tahun 2018 tentang Kesehatan. Setiap anak berhak mendapatkan imunisasi dasar dan lanjutan. Imunisasi bertujuan melindungi anak dari penyakit berbahaya seperti difteri, tetanus, campak, polio, dan lain-lain. Penolakan imunisasi dapat dikenai sanksi sesuai peraturan yang berlaku.',
            ],
            [
                'kunci' => 'faq-kes-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana bisa dapat obat gratis?',
                'kata_kunci' => ['obat', 'gratis', 'apotek', 'resep', 'puskesmas'],
                'jawaban_atau_konten' => 'Obat gratis bisa didapatkan dengan cara: 1) Berobat ke Puskesmas dengan KIS atau BPJS, obat akan diberikan gratis sesuai resep dokter. 2) Melalui program stunting yang menyediakan tablet tambah darah dan suplementasi. 3) Di posyandu tersedia vitamin A gratis untuk balita. 4) Program pengobatan TB dan malaria juga menyediakan obat gratis. Untuk obat di luar fasilitas kesehatan, silakan kunjungi apotek terdekat dengan resep dokter.',
            ],
            [
                'kunci' => 'faq-kes-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada apotek di Gampong Udeung?',
                'kata_kunci' => ['apotek', 'obat', 'farmasi', 'toko obat', 'beli obat'],
                'jawaban_atau_konten' => 'Saat ini Gampong Udeung belum memiliki apotek resmi. Namun, masyarakat bisa mendapatkan obat di warung atau toko kelontong yang menjual obat-obatan ringan seperti parasetamol, obat batuk, dan vitamin. Untuk obat dengan resep dokter, silakan kunjungi Puskesmas atau apotek di ibu kota kecamatan. Ada juga kader kesehatan yang bisa membantu menginformasikan ketersediaan obat.',
            ],
            [
                'kunci' => 'faq-kes-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Obat apa yang harus disiapkan di rumah?',
                'kata_kunci' => ['obat', 'darurat', 'pertolongan', 'rumah', 'kotak obat'],
                'jawaban_atau_konten' => 'Setiap rumah tangga sebaiknya menyiapkan kotak P3K berisi: parasetamol (untuk demam dan nyeri), obat diare (oralit dan loperamid), kasa steril dan plester luka, betadine atau antiseptik, minyak kayu putih, obat alergi (CTM), garam dapur untuk oralit darurat, termometer, dan gunting kecil. Sediakan juga nomor telepon darurat medis yang bisa dihubungi kapan saja.',
            ],
            [
                'kunci' => 'faq-kes-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa yang harus dilakukan jika demam tinggi?',
                'kata_kunci' => ['demam', 'panas', 'suhu', 'sakit', 'fever'],
                'jawaban_atau_konten' => 'Langkah pertolongan pertama saat demam: 1) Minum parasetamol sesuai dosis. 2) Kompres dahi dengan air hangat. 3) Banyak minum air putih agar tidak dehidrasi. 4) Istirahat di tempat teduh dan sejuk. 5) Pakai baju tipis dan longgar. Segera ke Puskesmas jika demam disertai: suhu di atas 40 derajat Celcius, kejang, muntah terus-menerus, nyeri kepala hebat, atau demam berlangsung lebih dari 3 hari.',
            ],
            [
                'kunci' => 'faq-kes-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengatasi diare pada anak?',
                'kata_kunci' => ['diare', 'anak', 'mencret', 'oralit', 'dehidrasi'],
                'jawaban_atau_konten' => 'Penanganan diare pada anak: 1) Berikan oralit terus-menerus untuk mencegah dehidrasi. Cara membuat oralit: larutkan 1 sendok teh garam dan 6 sendok teh gula pasir dalam 1 gelas air matang. 2) Tetap berikan ASI atau makanan seperti biasa. 3) Jangan berikan obat diare tanpa resep dokter pada anak. 4) Cuci tangan dengan sabun sebelum menyiapkan makanan. Segera ke Puskesmas jika anak lemas, mata cekung, tidak mau minum, atau diare berdarah.',
            ],
            [
                'kunci' => 'faq-kes-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa itu malaria dan bagaimana pencegahannya?',
                'kata_kunci' => ['malaria', 'nyamuk', 'demam', 'menggigil', 'pencegahan'],
                'jawaban_atau_konten' => 'Malaria adalah penyakit yang disebabkan oleh parasit Plasmodium dan ditularkan melalui gigitan nyamuk Anopheles. Gejala meliputi demam menggigil, keringat dingin, sakit kepala, dan mual. Pencegahan malaria: 1) Gunakan kelambu saat tidur. 2) Pakai losion anti nyamuk. 3) Minum obat pencegahan jika bepergian ke daerah endemis. 4) Bersihkan genangan air di sekitar rumah. Jika mengalami gejala malaria, segera periksa ke Puskesmas untuk tes darah. Pengobatan malaria harus tuntas selama yang diresepkan dokter.',
            ],
            [
                'kunci' => 'faq-kes-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa itu DBD dan bagaimana mengatasinya?',
                'kata_kunci' => ['dbd', 'demam berdarah', 'nyamuk', 'aedes', 'flu tulang'],
                'jawaban_atau_konten' => 'DBD (Demam Berdarah Dengue) adalah penyakit yang disebabkan virus dengue dan ditularkan oleh nyamuk Aedes aegypti. Gejala: demam tinggi mendadak selama 2-7 hari, nyeri otot dan tulang, bintik merah pada kulit, dan pendarahan. Pencegahan: 1) Ganti air di tempat penampungan setiap minggu. 2) Tutup rapat tempat penampungan air. 3) Gunakan obat nyamuk atau losion anti nyamuk. 4) Tanam pemangsa jentik seperti ikan. Segera ke Puskesmas jika demam turun tapi tubuh lemas karena bisa tanda syok DBD.',
            ],
            [
                'kunci' => 'faq-kes-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana menjaga kesehatan ibu hamil?',
                'kata_kunci' => ['hamil', 'kehamilan', 'ibU', 'periksa', 'nutrisi', 'persiapan'],
                'jawaban_atau_konten' => 'Tips menjaga kesehatan ibu hamil: 1) Periksa kehamilan minimal 4 kali selama kehamilan di Puskesmas atau bidan desa. 2) Konsumsi tablet tambah darah (TTD) setiap hari untuk mencegah anemia. 3) Makan makanan bergizi seimbang: protein, sayur, buah, dan karbohidrat. 4) Minum susu ibu hamil atau susu full cream. 5) Olahraga ringan seperti berjalan kaki. 6) Hindari rokok, kopi, dan makanan mentah. 7) Istirahat cukup 7-8 jam per hari. 8) Persiapkan persalinan di Puskesmas atau bidan desa yang sudah terdaftar.',
            ],
            [
                'kunci' => 'faq-kes-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa kali periksa kehamilan yang disarankan?',
                'kata_kunci' => ['hamil', 'periksa', 'kandungan', 'usg', 'kontrol'],
                'jawaban_atau_konten' => 'Minimal 4 kali pemeriksaan kehamilan (ANC) selama masa kehamilan: trimester 1 (usia kandungan 0-12 minggu) minimal 1 kali, trimester 2 (13-27 minggu) minimal 1 kali, dan trimester 3 (28-36 minggu) minimal 2 kali. Pemeriksaan meliputi: pengecekan tekanan darah, berat badan, tinggi fundus, detak jantung janin, tes urin, dan skrining anemia. Jika ada keluhan, periksa lebih sering. Pemeriksaan kehamilan gratis di Puskesmas dengan BPJS Kesehatan.',
            ],
            [
                'kunci' => 'faq-kes-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Makanan apa yang baik untuk ibu hamil?',
                'kata_kunci' => ['hamil', 'makanan', 'nutrisi', 'gizi', 'diet'],
                'jawaban_atau_konten' => 'Makanan yang baik untuk ibu hamil: 1) Protein: ikan laut, telur, tempe, tahu, daging ayam. 2) Sayuran hijau: bayam, kangkung, sawi hijau. 3) Buah-buahan: pepaya, pisang, jeruk, alpukat. 4) Karbohidrat kompleks: nasi merah, kentang, ubi. 5) Susu dan produk olahan susu. 6) Kacang-kacangan: kacang hijau, kacang merah. Yang harus dihindari: makanan mentah, ikan laut tinggi merkuri, kopi berlebihan, makanan kaleng, dan alkohol.',
            ],
            [
                'kunci' => 'faq-kes-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana menjaga gizi anak agar tidak stunting?',
                'kata_kunci' => ['anak', 'gizi', 'stunting', 'pertumbuhan', 'makanan'],
                'jawaban_atau_konten' => 'Tips mencegah stunting pada anak: 1) Berikan ASI eksklusif selama 6 bulan pertama. 2) Mulai makanan pendamping ASI (MPASI) yang bergizi pada usia 6 bulan. 3) Sajikan makanan bervariasi: nasi, lauk hewani (ikan, telur, daging), sayur, dan buah. 4) Berikan vitamin A dan tablet tambah darah sesuai jadwal posyandu. 5) Pantau berat badan dan tinggi badan anak di posyandu. 6) Berikan makan 3-4 kali sehari dengan 2-3 kali camilan sehat. 7) Cuci tangan sebelum makan dan menjaga kebersihan lingkungan.',
            ],
            [
                'kunci' => 'faq-kes-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Vitamin apa yang harus diberikan kepada anak?',
                'kata_kunci' => ['anak', 'vitamin', 'suplemen', 'pertumbuhan', 'tumbuh kembang'],
                'jawaban_atau_konten' => 'Vitamin yang penting untuk anak: 1) Vitamin A: diberikan setiap 6 bulan sekali di posyandu untuk bayi usia 6-59 bulan. Penting untuk kesehatan mata dan daya tahan tubuh. 2) Tablet tambah darah (TTD): untuk mencegah anemia pada remaja putri dan ibu hamil. 3) Vitamin D: bisa didapat dari sinar matahari pagi 15-20 menit per hari. 4) Vitamin C: dari buah-buahan segar seperti jeruk dan jambu biji. Sebaiknya tidak memberikan vitamin tanpa rekomendasi dokter.',
            ],
            [
                'kunci' => 'faq-kes-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana menjaga kesehatan lansia?',
                'kata_kunci' => ['lansia', 'manula', 'kesehatan', 'perawatan', 'tua'],
                'jawaban_atau_konten' => 'Tips menjaga kesehatan lansia: 1) Rutin periksa kesehatan ke Puskesmas minimal 3 bulan sekali. 2) Tetap aktif bergerak dengan berjalan kaki ringan atau senam lansia. 3) Konsumsi makanan bergizi tinggi serat dan rendah garam. 4) Minum obat rutin jika memiliki penyakit kronis seperti hipertensi atau diabetes. 5) Jaga kesehatan gigi dan mulut. 6) Jaga kesehatan mental dengan berinteraksi dengan keluarga dan tetangga. 7) Cukup tidur dan hindari stres berlebihan.',
            ],
            [
                'kunci' => 'faq-kes-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Olahraga apa yang cocok untuk lansia?',
                'kata_kunci' => ['lansia', 'olahraga', 'senam', 'jalan kaki', 'aktif'],
                'jawaban_atau_konten' => 'Olahraga yang cocok untuk lansia: 1) Berjalan kaki minimal 30 menit per hari. 2) Senam lansia atau senam pagi bersama di lapangan gampong. 3) Berkebun ringan merawat tanaman. 4) Bersepeda statis atau bersepeda santai. 5) Peregangan ringan untuk menjaga kelenturan otot. 6) Tai chi untuk keseimbangan. Yang harus dihindari: olahraga berat yang melompat-lompat, angkat beban berat, dan olahraga saat cuaca panas terik. Konsultasikan ke dokter sebelum memulai program olahraga.',
            ],
            [
                'kunci' => 'faq-kes-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa nomor telepon darurat medis?',
                'kata_kunci' => ['darurat', 'telepon', 'nomor', 'ambulans', 'gawat darurat'],
                'jawaban_atau_konten' => 'Nomor telepon darurat medis yang bisa dihubungi: 1) Nomor darurat nasional: 112 (bisa diakses dari semua operator). 2) Puskesmas Kecamatan: hubungi kantor camat untuk nomor terkini. 3) Bidan desa: hubungi kantor gampong. 4) UGD Rumah Sakit terdekat: hubungi 118 atau 119 untuk layanan ambulans. 5) BPJS Kesehatan Care Center: 1500400. Simpan nomor-nomor ini di ponsel Anda untuk keadaan darurat.',
            ],
            [
                'kunci' => 'faq-kes-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa yang harus dilakukan dalam keadaan darurat medis?',
                'kata_kunci' => ['darurat', 'pertolongan', 'kecelakaan', 'pingsan', 'luka'],
                'jawaban_atau_konten' => 'Langkah pertolongan pertama dalam keadaan darurat medis: 1) Tetap tenang dan evaluasi situasi. 2) Hubungi nomor darurat 112 atau 118. 3) Pastikan keselamatan diri sebelum menolong. 4) Jika korban tidak sadar, periksa napas dan detak jantung. 5) Lakukan CPR jika diperlukan. 6) Jangan memindahkan korban kecuali ada bahaya. 7) Berikan informasi jelas tentang lokasi dan kondisi korban. 8) Tunggu bantuan medis tiba. Jangan memberikan makanan atau minuman kepada korban yang tidak sadar.',
            ],
            [
                'kunci' => 'faq-kes-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengatasi stres?',
                'kata_kunci' => ['stres', 'depresi', 'kesehatan mental', 'cemas', 'konseling'],
                'jawaban_atau_konten' => 'Tips mengatasi stres: 1) Identifikasi penyebab stres dan cari solusi bersama orang terpercaya. 2) Berolahraga rutin minimal 30 menit per hari. 3) Cukup tidur 7-8 jam per malam. 4) Lakukan aktivitas yang menyenangkan seperti berkebun atau memasak. 5) Berdoa dan mendekatkan diri kepada Tuhan. 6) Batasi penggunaan media sosial. 7) Makan makanan bergizi. Jika stres berlanjut dan mengganggu aktivitas sehari-hari, konsultasikan ke petugas kesehatan di Puskesmas atau konselor yang terpercaya.',
            ],
            [
                'kunci' => 'faq-kes-031',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana bisa mendapatkan konseling kesehatan mental?',
                'kata_kunci' => ['konseling', 'kesehatan mental', 'depresi', 'psikolog', 'bantuan'],
                'jawaban_atau_konten' => 'Layanan konseling kesehatan mental bisa diakses melalui: 1) Puskesmas: tersedia layanan konseling dasar. 2) Rumah sakit: poli psikiatri untuk gangguan mental yang lebih serius. 3) hotline kesehatan mental nasional: 119 ext 8. 4) Konsultasi dengan ustadz atau pemuka agama untuk masalah spiritual. 5) Berbicara dengan keluarga atau sahabat terpercaya. Jangan malu untuk mencari bantuan, kesehatan mental sama pentingnya dengan kesehatan fisik.',
            ],
            [
                'kunci' => 'faq-kes-032',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara menjaga kesehatan gigi dan mulut?',
                'kata_kunci' => ['gigi', 'mulut', 'sikat gigi', 'kesehatan', 'sakit gigi'],
                'jawaban_atau_konten' => 'Tips menjaga kesehatan gigi dan mulut: 1) Sikat gigi minimal 2 kali sehari, pagi setelah sarapan dan malam sebelum tidur. 2) Gunakan sikat gigi dengan bulu halus dan pasta gigi berfluoride. 3) Gunakan benang gigi untuk membersihkan sela-sela gigi. 4) Hindari terlalu banyak makanan manis. 5) Periksa gigi ke dokter gigi minimal 6 bulan sekali. 6) Bilas mulut dengan air putih setelah makan. 7) Ganti sikat gigi setiap 3 bulan. Puskesmas biasanya menyediakan layanan kesehatan gigi dan mulut.',
            ],
        ];
    }

    public function getFaqEkonomi(): array
    {
        return [
            [
                'kunci' => 'faq-eko-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan bantuan modal untuk UMKM?',
                'kata_kunci' => ['umkm', 'modal', 'bantuan', 'pinjaman', 'usaha'],
                'jawaban_atau_konten' => 'Cara mendapatkan bantuan modal UMKM: 1) Daftarkan usaha ke Dinas Koperasi dan UMKM Kabupaten. 2) Ikuti pelatihan kewirausahaan yang diselenggarakan dinas terkait. 3) Ajukan proposal usaha. 4) Bantuan bisa berupa hibah modal Rp 1-5 juta atau pinjaman lunak melalui KUR. 5) Untuk bantuan dari program desa, sampaikan proposal melalui Keuchik Gampong Udeung. 6) Pastikan memiliki NIB (Nomor Induk Berusaha) untuk mempermudah pengajuan.',
            ],
            [
                'kunci' => 'faq-eko-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pelatihan apa saja yang tersedia untuk UMKM?',
                'kata_kunci' => ['umkm', 'pelatihan', 'kursus', 'keterampilan', 'wirausaha'],
                'jawaban_atau_konten' => 'Pelatihan untuk UMKM yang biasanya tersedia: 1) Pelatihan pemasaran digital dan media sosial. 2) Pelatihan pengelolaan keuangan sederhana. 3) Pelatihan membuat kemasan produk yang menarik. 4) Pelatihan memasak dan pengolahan makanan. 5) Pelatihan pertanian modern dan有机. 6) Pelatihan pembuatan produk kerajinan. Pelatihan ini biasanya diselenggarakan oleh Dinas Koperasi, BLK (Balai Latihan Kerja), atau program CSR perusahaan. Informasi jadwal bisa ditanyakan ke kantor camat.',
            ],
            [
                'kunci' => 'faq-eko-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara memasarkan produk UMKM?',
                'kata_kunci' => ['umkm', 'pemasaran', 'jual', 'promosi', 'online'],
                'jawaban_atau_konten' => 'Tips memasarkan produk UMKM: 1) Manfaatkan media sosial seperti Facebook, Instagram, dan WhatsApp. 2) Gabung komunitas UMKM Gampong Udeung untuk saling mempromosikan. 3) Ikut pameran UMKM di tingkat kecamatan dan kabupaten. 4) Tawarkan produk ke warung dan toko di sekitar gampong. 5) Gunakan kemasan yang menarik dan label produk yang jelas. 6) Daftarkan produk ke marketplace online lokal. 7) Berikan promo atau diskon untuk pelanggan pertama.',
            ],
            [
                'kunci' => 'faq-eko-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Tanaman apa yang cocok ditanam di Gampong Udeung?',
                'kata_kunci' => ['tanaman', 'pertanian', 'cocok', 'tanam', 'lahan'],
                'jawaban_atau_konten' => 'Tanaman yang cocok untuk iklim dan kondisi tanah di Aceh: 1) Padi sawah dan padi ladang. 2) Kelapa untuk kopra dan minyak kelapa. 3) Sawit untuk tandan buah segar. 4) Karet untuk lateks. 5) Sayuran: cabai, tomat, terong, kangkung, bayam. 6) Buah-buahan: pisang, pepaya, durian, mangga, rambutan. 7) Rempah-rempah: jahe, kunyit, lengkuas, serai. Pilih tanaman sesuai kondisi lahan dan kebutuhan pasar.',
            ],
            [
                'kunci' => 'faq-eko-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kapan musim tanam padi di Aceh?',
                'kata_kunci' => ['padi', 'musim', 'tanam', 'sawah', 'panen'],
                'jawaban_atau_konten' => 'Musim tanam padi di Aceh: 1) Musim rendeng (tanam basah): Desember sampai Februari, panen Maret-April. 2) Musim gadu (tanam kemarau): Juni sampai Agustus, panen September-Oktober. Jarak tanam yang disarankan 25x25 cm atau 20x20 cm. Gunakan benih varietas unggul seperti Inpari atau Ciherang. Konsultasikan dengan penyuluh pertanian untuk jadwal tanam yang tepat sesuai kondisi cuaca tahun ini.',
            ],
            [
                'kunci' => 'faq-eko-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pupuk apa yang bagus untuk tanaman?',
                'kata_kunci' => ['pupuk', 'tanaman', 'pupuk organik', 'kompos', 'subsid'],
                'jawaban_atau_konten' => 'Jenis pupuk untuk tanaman: 1) Pupuk kandang: dari kotoran sapi atau ayam yang sudah difermentasi. 2) Kompos: dari sampah organik dan daun kering yang sudah diolah. 3) Pupuk NPK: campuran nitrogen, fosfor, dan kalium. 4) Pupuk Urea: untuk mempercepat pertumbuhan daun. 5) Pupuk ZA: untuk tanaman yang membutuhkan sulfur. Untuk memperoleh pupuk bersubsidi, daftarkan diri sebagai petani di Dinas Pertanian dan bawa KTP serta surat keterangan dari Keuchik.',
            ],
            [
                'kunci' => 'faq-eko-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana mengatasi hama pada tanaman?',
                'kata_kunci' => ['hama', 'tanaman', 'ulat', 'serangga', 'penyakit tanaman'],
                'jawaban_atau_konten' => 'Cara mengatasi hama tanaman: 1) Pengendalian alami: gunakan predator alami seperti burung dan katak. 2) Semprotkan pestisida organik dari bahan nabati seperti daun neem atau bawang putih. 3) Gunakan pestisida kimia sesuai dosis anjuran jika serangan parah. 4) Lakukan rotasi tanaman untuk memutus siklus hama. 5) Bersihkan gulma dan sisa tanaman yang terinfeksi. 6) Konsultasikan ke penyuluh pertanian untuk identifikasi hama dan penanganan yang tepat.',
            ],
            [
                'kunci' => 'faq-eko-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara beternak ikan di kolam?',
                'kata_kunci' => ['ikan', 'kolam', 'budidaya', 'perikanan', 'ternak ikan'],
                'jawaban_atau_konten' => 'Langkah budidaya ikan di kolam: 1) Siapkan kolam: buat kolam tanah atau terpal dengan ukuran minimal 3x3 meter. 2) Isi air setinggi 50-70 cm. 3) Pilih bibit ikan: lele, nila, gurame, atau mas. 4) Tebar benih ikan sesuai ukuran kolam. 5) Beri pakan 2-3 kali sehari dengan pelet. 6) Jaga kualitas air: ganti air secara berkala. 7) Panen setelah 3-4 bulan tergantung jenis ikan. Bantuan bibit ikan bisa didapatkan melalui program Dinas Perikanan Kabupaten.',
            ],
            [
                'kunci' => 'faq-eko-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Ikan apa yang menguntungkan untuk dibudidayakan?',
                'kata_kunci' => ['ikan', 'untung', 'budidaya', 'lele', 'nila', 'gurame'],
                'jawaban_atau_konten' => 'Jenis ikan yang menguntungkan untuk dibudidayakan: 1) Lele: pertumbuhan cepat, tahan kondisi air, permintaan tinggi. Panen 2-3 bulan. 2) Nila: mudah dirawat, rasa enak, harga stabil. Panen 3-4 bulan. 3) Gurame: harga jual tinggi, bisa mencapai Rp 40.000-60.000 per kg. Panen 6-8 bulan. 4) Mas: cocok untuk kolam dengan sirkulasi air baik. 5) Patin: permintaan tinggi untuk restoran. 6) Belut: harga jual tinggi, bisa dibudidayakan di lahan sempit.',
            ],
            [
                'kunci' => 'faq-eko-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara beternak ayam kampung?',
                'kata_kunci' => ['ayam', 'kampung', 'ternak', 'ayam', 'petelur', 'pedaging'],
                'jawaban_atau_konten' => 'Cara beternak ayam kampung: 1) Siapkan kandang yang bersih dan kering, minimal 1 meter persegi untuk 2-3 ekor. 2) Pilih bibit ayam kampung unggul dari peternak terpercaya. 3) Sediakan pakan: campuran beras, jagung, dan dedak. 4) Beri air minum bersih dan vitamin. 5) Vaksin dan obati jika sakit. 6) Untuk ayam petelur, panen telur setiap 1-2 hari. 7) Untuk ayam pedaging, panen setelah 3-4 bulan. Harga ayam kampung hidup sekitar Rp 50.000-70.000 per ekor.',
            ],
            [
                'kunci' => 'faq-eko-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara beternak kambing?',
                'kata_kunci' => ['kambing', 'ternak', 'daging', 'susu', 'kotoran'],
                'jawaban_atau_konten' => 'Cara beternak kambing: 1) Siapkan kandang yang bersih dan terhindar dari hujan. 2) Pilih bibit kambing berkualitas: Etawa, PE, atau Kacang. 3) Sediakan pakan berupa rumput segar, daun-leguminosa, dan konsentrat. 4) Beri air minum yang cukup dan bersih. 5) Perhatikan kesehatan: vaksinasi dan obati cacingan. 6) Untuk kambing perah, perah susu 2 kali sehari. 7) Kotoran kambing bisa dijual sebagai pupuk organik. Beternak 2-3 ekor kambing bisa menghasilkan pendapatan tambahan Rp 1-2 juta per bulan.',
            ],
            [
                'kunci' => 'faq-eko-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara beternak sapi?',
                'kata_kunci' => ['sapi', 'ternak', 'daging', 'sapi potong', 'sapi perah'],
                'jawaban_atau_konten' => 'Cara beternak sapi: 1) Siapkan kandang yang kokoh dan luas. 2) Pilih jenis sapi: Sapi Bali untuk pedaging atau Sapi FH untuk perah. 3) Sediakan pakan: rumput, jerami, konsentrat, dan suplemen mineral. 4) Beri air minum minimal 20-30 liter per hari. 5) Vaksinasi dan obati parasit secara berkala. 6) Untuk penggemukan, proses selama 6-8 bulan. 7) Untuk sapi perah, perah susu 2-3 kali sehari. Investasi ternak sapi memang besar, tapi hasilnya jangka panjang dan menguntungkan.',
            ],
            [
                'kunci' => 'faq-eko-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pakan ternak yang bagus apa saja?',
                'kata_kunci' => ['pakan', 'ternak', 'konsentrat', 'rumput', 'makanan hewan'],
                'jawaban_atau_konten' => 'Jenis pakan ternak yang bagus: 1) Rumput: rumput gajah, rumput raja, kolan. 2) Konsentrat: campuran bekatul, jagung giling, dan bungkil kelapa. 3) Daun leguminosa: lamtoro, indigofera, gamal. 4) Limbah pertanian: jerami, kulit kacang, ampas tahu. 5) Mineral: garam dapur dan suplemen mineral. 6) Air minum yang bersih dan cukup. Untuk penghematan, manfaatkan lahan pekarangan untuk menanam rumput pakan ternak.',
            ],
            [
                'kunci' => 'faq-eko-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa itu KUR dan bagaimana cara daftarnya?',
                'kata_kunci' => ['kur', 'kredit', 'modal', 'pinjaman', 'bunga rendah'],
                'jawaban_atau_konten' => 'KUR (Kredit Usaha Rakyat) adalah program pemerintah untuk memberikan pinjaman modal usaha dengan bunga rendah. Syarat KUR: 1) Warga negara Indonesia. 2) Usia minimal 21 tahun atau sudah menikah. 3) Memiliki usaha produktif yang sudah berjalan minimal 6 bulan. 4) Tidak sedang menerima kredit dari bank lain. 5) Bukan PNS, TNI, atau Polri. Cara daftar: siapkan KTP, KK, proposal usaha, dan surat keterangan usaha dari Keuchik. Ajukan ke bank mitra KUR seperti BRI, BNI, atau Bank Aceh. Bunga KUR saat ini sekitar 6% per tahun.',
            ],
            [
                'kunci' => 'faq-eko-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa bunga KUR saat ini?',
                'kata_kunci' => ['kur', 'bunga', 'suku bunga', 'pinjaman', 'kredit'],
                'jawaban_atau_konten' => 'Bunga KUR (Kredit Usaha Rakyat) saat ini: 1) KUR Mikro: bunga 6% per tahun (0,5% per bulan). 2) KUR Kecil: bunga 6% per tahun. 3) KUR Penyalur: bunga 6% per tahun untuk pinjaman sampai Rp 10 juta. Tenor KUR: 1-4 tahun untuk modal kerja, 2-5 tahun untuk investasi. Untuk pinjaman di bawah Rp 10 juta, tidak perlu agunan. Untuk pinjaman Rp 10-500 juta, perlu jaminan berupa sertifikat tanah atau BPKB.',
            ],
            [
                'kunci' => 'faq-eko-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana ada bank atau koperasi di sekitar Gampong Udeung?',
                'kata_kunci' => ['bank', 'koperasi', 'tabungan', 'simpan pinjam', 'keuangan'],
                'jawaban_atau_konten' => 'Fasilitas keuangan di sekitar Gampong Udeung: 1) Bank Aceh Syariah: terdapat cabang di ibu kota kecamatan. 2) BRI unit kecamatan: melayani simpan pinjam dan KUR. 3) Koperasi Simpan Pinjam: ada di tingkat kecamatan. 4) KSP (Koperasi Serba Usaha): beberapa koperasi desa di kecamatan. 5) Agen LinkAja atau agen e-wagen lainnya di warung sekitar gampong untuk kebutuhan transaksi kecil. Untuk kebutuhan perbankan lengkap, silakan ke ibu kota kabupaten.',
            ],
            [
                'kunci' => 'faq-eko-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara membuka tabungan di bank?',
                'kata_kunci' => ['tabungan', 'bank', 'buka rekening', 'simpanan', 'atm'],
                'jawaban_atau_konten' => 'Cara membuka tabungan di bank: 1) Datang ke cabang bank terdekat. 2) Bawa KTP asli, KK, dan setoran awal minimal Rp 50.000-100.000. 3) Isi formulir pembukaan rekening. 4) Pilih jenis tabungan sesuai kebutuhan. 5) Dapatkan buku tabungan dan kartu ATM. 6) Aktivasi mobile banking melalui aplikasi bank. Beberapa bank yang mudah diakses: Bank Aceh Syariah, BRI, BNI Syariah. Untuk nasabah KUR, biasanya mendapatkan rekening gratis.',
            ],
            [
                'kunci' => 'faq-eko-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana lokasi pasar terdekat dari Gampong Udeung?',
                'kata_kunci' => ['pasar', 'belanja', 'jual', 'harga', 'berdagang'],
                'jawaban_atau_konten' => 'Pasar terdekat dari Gampong Udeung: 1) Pasar Desa: biasanya ada di beberapa gampong dengan hari pasaran tertentu. 2) Pasar Kecamatan: buka setiap hari dengan jam buka pukul 07.00-17.00 WIB. 3) Pasar Rakyat: buka pada hari-hari tertentu sesuai jadwal. Untuk kebutuhan sehari-hari, ada warung dan toko kelontong di dalam gampong. Untuk kebutuhan lebih lengkap, silakan ke pasar kecamatan atau pasar kabupaten.',
            ],
            [
                'kunci' => 'faq-eko-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa harga padi saat ini di Aceh?',
                'kata_kunci' => ['harga', 'padi', 'gabah', 'beras', 'komoditas'],
                'jawaban_atau_konten' => 'Harga padi di Aceh bisa berfluktuasi, namun estimasi harga: 1) Gabah kering panen: Rp 4.500-5.500 per kg. 2) Gabah kering panen (gkp): Rp 4.000-5.000 per kg. 3) Beras premium: Rp 12.000-15.000 per kg. 4) Beras kualitas menengah: Rp 10.000-12.000 per kg. Harga ini bisa berbeda di setiap daerah dan musim. Untuk harga terkini, cek di Unit Penggilingan Padi (UPP) atau hubungi Bulog setempat.',
            ],
            [
                'kunci' => 'faq-eko-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa harga kelapa di pasaran?',
                'kata_kunci' => ['harga', 'kelapa', 'kopra', 'minyak kelapa', 'komoditas'],
                'jawaban_atau_konten' => 'Harga kelapa di Aceh: 1) Kelapa tua (per butir): Rp 8.000-15.000 tergantung ukuran. 2) Kopra kering: Rp 5.000-7.000 per kg. 3) Minyak kelapa murni (virgin coconut oil): Rp 50.000-80.000 per liter. 4) Sabut kelapa: Rp 1.000-2.000 per kg. Harga kelapa bisa naik drastis saat kebutuhan industri tinggi. Petani bisa mendapatkan keuntungan lebih dengan mengolah kelapa menjadi minyak kelapa murni atau sabut kelapa.',
            ],
            [
                'kunci' => 'faq-eko-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa harga sawit saat ini?',
                'kata_kunci' => ['harga', 'sawit', 'tbs', 'cpo', 'komoditas'],
                'jawaban_atau_konten' => 'Harga Tandan Buah Segar (TBS) sawit di Aceh: 1) Harga TBS sawit mentah: Rp 1.800-2.500 per kg. 2) Harga tandan sawit bisa bervariasi tergantung kandungan minyak. 3) Harga CPO (Crude Palm Oil): Rp 10.000-14.000 per liter. Harga TBS sawit ditetapkan setiap dua minggu sekali oleh Dinas Perkebunan. Petani sawit di Gampong Udeung bisa menjual TBS ke pabrik kelapa sawit (PKS) terdekat.',
            ],
            [
                'kunci' => 'faq-eko-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara melamar kerja?',
                'kata_kunci' => ['kerja', 'lowongan', 'melamar', 'cv', 'wawancara'],
                'jawaban_atau_konten' => 'Cara melamar kerja: 1) Siapkan CV (Curriculum Vitae) yang lengkap dan rapi. 2) Cari informasi lowongan melalui: koran, internet, media sosial, atau informasi dari kerabat. 3) Kirim surat lamaran dan CV ke perusahaan yang dituju. 4) Ikuti tes seleksi sesuai jadwal yang ditentukan. 5) Siapkan dokumen pendukung: Ijazah, SKCK, surat keterangan sehat. 6) Datang tepat waktu untuk wawancara. Tips: tunjukkan sikap percaya diri, jujur, dan semangat kerja saat wawancara.',
            ],
            [
                'kunci' => 'faq-eko-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana mencari lowongan kerja?',
                'kata_kunci' => ['lowongan', 'kerja', 'cari', 'info', 'pekerjaan'],
                'jawaban_atau_konten' => 'Tempat mencari lowongan kerja: 1) Media sosial: grup Facebook lowongan kerja Aceh, Instagram @lokeraceh. 2) Website: jobstreet.co.id, indeed.co.id, karir.com. 3) Kantor Disnaker (Dinas Ketenagakerjaan) Kabupaten. 4) Job fair atau bursa kerja yang diadakan pemerintah. 5) Informasi dari keluarga dan teman. 6) Koran lokal atau majalah. 7) Langsung datang ke perusahaan yang diminati. Pantau terus informasi lowongan karena bisa berubah sewaktu-waktu.',
            ],
            [
                'kunci' => 'faq-eko-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara membuat CV yang baik?',
                'kata_kunci' => ['cv', 'lamaran', 'resume', 'daftar riwayat', 'pekerjaan'],
                'jawaban_atau_konten' => 'Tips membuat CV yang baik: 1) Gunakan format yang rapi dan profesional. 2) Cantumkan data diri: nama, alamat, nomor telepon, email. 3) Tuliskan pendidikan terakhir secara kronologis. 4) Sertakan pengalaman kerja atau kegiatan relevan. 5) Sebutkan keahlian yang dimiliki. 6) Lampirkan foto formal berukuran 3x4. 7) Maksimal 2 halaman. 8) Gunakan bahasa Indonesia yang baik dan benar. 9) Cek ejaan dan tata bahasa sebelum mengirim. Bisa dibuat di warung internet (warnet) atau menggunakan template gratis dari internet.',
            ],
            [
                'kunci' => 'faq-eko-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa saja komoditas ekspor dari Aceh?',
                'kata_kunci' => ['ekspor', 'komoditas', 'aceh', 'perdagangan', 'luar negeri'],
                'jawaban_atau_konten' => 'Komoditas utama ekspor dari Aceh: 1) Minyak kelapa sawit (CPO). 2) Kopra dan minyak kelapa. 3) Karet. 4) Kopi Arabika Gayo. 5) Cengkeh. 6) Lada. 7) Produk perikanan: ikan beku, udang, dan tuna. 8) Produk kayu: rotan dan olahan kayu. Aceh memiliki potensi ekspor yang besar terutama untuk komoditas perkebunan dan perikanan. Untuk informasi ekspor, hubungi Dinas Perindustrian dan Perdagangan Kabupaten.',
            ],
            [
                'kunci' => 'faq-eko-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengekspor produk dari Aceh?',
                'kata_kunci' => ['ekspor', 'produk', 'perdagangan', 'luar negeri', 'internasional'],
                'jawaban_atau_konten' => 'Langkah mengekspor produk dari Aceh: 1) Pastikan produk memenuhi standar ekspor dan memiliki sertifikasi. 2) Daftarkan usaha ekspor di Dinas Perindag. 3) Cari mitra atau buyer luar negeri melalui pameran atau online. 4) Siapkan dokumen ekspor: invoice, packing list, sertifikat asal barang, dan surat keterangan kesehatan. 5) Gunakan jasa forwarder atau ekspedisi internasional. 6) Pahami ketentuan bea cukai dan pajak ekspor. Mulai dari ekspor skala kecil dan tingkatkan secara bertahap.',
            ],
            [
                'kunci' => 'faq-eko-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa itu koperasi dan bagaimana cara bergabung?',
                'kata_kunci' => ['koperasi', 'bergabung', 'anggota', 'simpan pinjam', 'keuntungan'],
                'jawaban_atau_konten' => 'Koperasi adalah organisasi ekonomi yang dimiliki dan dijalankan oleh anggotanya untuk kepentingan bersih. Cara bergabung: 1) Cari koperasi terdekat di kecamatan atau kabupaten. 2) Datang dan tanyakan syarat keanggotaan. 3) Isi formulir keanggotaan. 4) Bayar simpanan pokok dan simpanan wajib. 5) Dapatkan buku anggota. Keuntungan menjadi anggota koperasi: bisa meminjam modal dengan bunga rendah, mendapat dividen tahunan, dan berpartisipasi dalam Rapat Anggota Tahunan (RAT).',
            ],
            [
                'kunci' => 'faq-eko-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Manfaat menjadi anggota koperasi apa saja?',
                'kata_kunci' => ['koperasi', 'manfaat', 'anggota', 'dividen', 'pinjaman'],
                'jawaban_atau_konten' => 'Manfaat menjadi anggota koperasi: 1) Bisa meminjam modal usaha dengan bunga rendah. 2) Mendapat keuntungan (dividen) dari kegiatan usaha koperasi. 3) Bisa membeli kebutuhan sehari-hari dengan harga lebih murah di toko koperasi. 4) Mendapat pelatihan dan pembinaan usaha. 5) Hak suara dalam Rapat Anggota Tahunan. 6) Bisa menyimpan uang dengan bunga simpanan yang menguntungkan. 7) Gotong royong sesama anggota untuk kemajuan bersama.',
            ],
            [
                'kunci' => 'faq-eko-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengembangkan usaha pertanian?',
                'kata_kunci' => ['pertanian', 'usaha', 'kembangkan', 'modern', 'teknologi'],
                'jawaban_atau_konten' => 'Tips mengembangkan usaha pertanian: 1) Gunakan bibit unggul dan benih bersertifikat. 2) Terapkan pola tanam yang baik sesuai musim. 3) Manfaatkan pupuk organik dan pengendalian hama terpadu. 4) Gunakan teknologi irigasi sederhana untuk efisiensi air. 5) Gabung dengan kelompok tani untuk saling belajar. 6) Pasarkan hasil panen melalui jalur yang lebih baik. 7) Diversifikasi produk: olah hasil panen menjadi produk bernilai tambah. 8) Manfaatkan program bantuan pemerintah untuk alat dan mesin pertanian.',
            ],
            [
                'kunci' => 'faq-eko-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa itu subsidi pupuk dan bagaimana cara mendapatkannya?',
                'kata_kunci' => ['subsidi', 'pupuk', 'program', 'pemerintah', 'petani'],
                'jawaban_atau_konten' => 'Subsidi pupuk adalah program pemerintah untuk memberikan pupuk dengan harga lebih murah kepada petani. Cara mendapatkan: 1) Daftarkan diri sebagai petani di Dinas Pertanian Kabupaten. 2) Daftarkan lahan pertanian yang dimiliki. 3) Dapatkan e-RE (Elektronik Rencana Usaha) dari sistem online. 4) Beli pupuk bersubsidi di pengecer resmi yang ditunjuk. 5) Bawa e-RE atau surat keterangan dari Keuchik. Jenis pupuk bersubsidi: Urea, NPK, dan ZA. Kuota pupuk subsidi terbatas, jadi daftar sebelum musim tanam.',
            ],
            [
                'kunci' => 'faq-eko-031',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara memulai usaha dari nol?',
                'kata_kunci' => ['usaha', 'mulai', 'nol', 'wirausaha', 'pemula'],
                'jawaban_atau_konten' => 'Tips memulai usaha dari nol: 1) Identifikasi minat dan keahlian yang dimiliki. 2) Riset pasar: cari tahu kebutuhan masyarakat sekitar. 3) Buat rencana usaha sederhana. 4) Mulai dari usaha kecil-kecilan dengan modal seadanya. 5) Manfaatkan kemampuan yang ada: memasak, menjahit, atau bertani. 6) Bangun reputasi dengan memberikan pelayanan terbaik. 7) Hemat dan sisihkan keuntungan untuk modal usaha. 8) Manfaatkan bantuan pemerintah untuk UMKM. 9) Ikut komunitas wirausaha untuk saling mendukung.',
            ],
            [
                'kunci' => 'faq-eko-032',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa saja peluang usaha di Gampong Udeung?',
                'kata_kunci' => ['peluang', 'usaha', 'desa', 'gampng', 'ide usaha'],
                'jawaban_atau_konten' => 'Peluang usaha di Gampong Udeung: 1) Budidaya ikan lele atau nila di kolam. 2) Beternak ayam kampung atau kambing. 3) Mengolah hasil pertanian menjadi produk olahan. 4) Usaha warung atau toko kelontong. 5) Jasa pertukangan atau bangunan. 6) Usaha jahit menjahit pakaian. 7) Budidaya madu lebah. 8) Usaha jual beli hasil kebun. 9) Jasa ojek atau transportasi. 10) Usaha kuliner makanan khas Aceh. Pilih usaha yang sesuai dengan minat, modal, dan kebutuhan pasar lokal.',
            ],
        ];
    }
}
