<?php

namespace Database\Seeders\knowledge;

class BotKnowledgeFaqAdministrasi
{
    public function getFaqAdministrasi(): array
    {
        return [
            // ==================== KARTU KELUARGA ====================
            [
                'kunci' => 'faq-adm-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara membuat Kartu Keluarga (KK) baru',
                'kata_kunci' => ['kartu keluarga', 'kk baru', 'membuat kk', 'daftar kk'],
                'jawaban_atau_konten' => 'Untuk membuat Kartu Keluarga baru, datang ke Kantor Keuchik/Desa dengan membawa surat pengantar dari Keuchik Dusun, fotokopi KTP suami dan istri, surat nikah/akta nikah, dan fotokopi akta kelahiran anak (jika ada). Penggratisan biaya, proses sekitar 3-7 hari kerja. Petugas desa akan mengisi formulir F.1.01 dan mengirim ke Dinas Kependudukan dan Pencatatan Sipil (Disdukcapil).',
            ],
            [
                'kunci' => 'faq-adm-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mengubah data di Kartu Keluarga',
                'kata_kunci' => ['ubah data kk', 'perubahan kk', 'update kk', 'koreksi kk'],
                'jawaban_atau_konten' => 'Untuk mengubah data di KK (nama, tanggal lahir, pekerjaan, dll), ajukan permohonan perubahan data ke Disdukcapil melalui kantor desa. Bawa KK asli, dokumen pendukung yang berkaitan dengan perubahan (akta nikah, akta kelahiran, ijazah), dan fotokopi KTP. Proses gratis dan memakan waktu 1-5 hari kerja tergantung jenis perubahannya.',
            ],
            [
                'kunci' => 'faq-adm-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kartu Keluarga hilang, bagaimana cara mencetak ulang?',
                'kata_kunci' => ['kk hilang', 'cetak ulang kk', 'kk rusak', 'penggantian kk'],
                'jawaban_atau_konten' => 'Jika KK hilang atau rusak, laporkan ke kantor polisi untuk membuat surat keterangan kehilangan. Kemudian datang ke kantor desa dengan membawa surat keterangan kehilangan, fotokopi KTP semua anggota keluarga, dan surat pengantar dari Keuchik. Petugas desa akan mengajukan cetak ulang ke Disdukcapil. Biaya gratis, proses 3-7 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Menambahkan anggota keluarga baru di KK',
                'kata_kunci' => ['tambah anggota keluarga', 'bayi baru lahir di kk', 'anak baru di kk', 'menambah nama'],
                'jawaban_atau_konten' => 'Untuk menambahkan anggota keluarga baru (bayi yang baru lahir) ke dalam KK, bawa akta kelahiran anak, fotokopi KTP orang tua, dan KK asli ke kantor desa. Petugas akan mengisi formulir untuk penambahan anggota keluarga. Proses gratis dan selesai dalam 1-3 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mengeluarkan anggota keluarga dari KK',
                'kata_kunci' => ['keluar dari kk', 'hapus anggota kk', 'pindah dari kk'],
                'jawaban_atau_konten' => 'Anggota keluarga dapat dikeluarkan dari KK jika sudah menikah dan punya KK sendiri, atau pindah domisili. Bawa KK asli, fotokopi KTP yang bersangkutan, surat nikah (jika menikah), atau surat keterangan pindah. Proses gratis di kantor desa, dikirim ke Disdukcapil, waktu 3-5 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah KK sementara bisa dibuat?',
                'kata_kunci' => ['kk sementara', 'surat keterangan domisili', 'skd'],
                'jawaban_atau_konten' => 'Untuk keperluan sementara seperti pendaftaran sekolah atau administrasi lainnya, bisa dibuatkan Surat Keterangan Domisili (SKD) dari kantor desa. SKD ini berfungsi sebagai pengganti sementara KK. Bawa KTP asli dan fotokopi, surat pengantar dari Keuchik Dusun. Biaya gratis, proses 1 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Validasi Kartu Keluarga',
                'kata_kunci' => ['validasi kk', 'cek kebenaran data kk', 'verifikasi kk'],
                'jawaban_atau_konten' => 'Validasi KK dilakukan untuk memastikan data di KK sesuai dengan kondisi riil. Datang ke kantor desa dengan membawa KK asli dan dokumen pendukung. Petugas akan melakukan pengecekan dan memperbarui data jika ditemukan ketidaksesuaian. Proses gratis dan selesai dalam 1-3 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Memisahkan KK dari orang tua',
                'kata_kunci' => ['pisah kk', 'kk baru dari orang tua', 'mandiri kk'],
                'jawaban_atau_konten' => 'Untuk memisahkan KK dari orang tua, yang bersangkutan harus sudah berusia minimal 17 tahun atau sudah menikah. Bawa KTP asli, fotokopi KK orang tua, akta nikah (jika menikah), surat pengantar dari Keuchik. Proses gratis, kantor desa akan mengurus ke Disdukcapil. Waktu 3-7 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mengganti nama dalam Kartu Keluarga',
                'kata_kunci' => ['ganti nama kk', 'ubah nama di kk', 'perubahan nama'],
                'jawaban_atau_konten' => 'Untuk mengganti nama dalam KK, perlu dibuat dulu Surat Keterangan Ganti Nama dari pejabat berwenang (pengadilan/agama). Bawa surat ganti nama, KK asli, KTP, dan fotokopi dokumen pendukung ke kantor desa. Proses gratis, waktu 3-7 hari kerja di Disdukcapil.',
            ],
            [
                'kunci' => 'faq-adm-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Memperbaiki kesalahan data di KK',
                'kata_kunci' => ['koreksi data kk', 'salah tulis di kk', 'koreksi nama di kk'],
                'jawaban_atau_konten' => 'Jika ada kesalahan penulisan nama, tanggal lahir, atau data lain di KK, ajukan koreksi ke kantor desa. Bawa KK asli, dokumen asli sebagai bukti (akta lahir, ijazah), dan fotokopi KTP. Petugas desa akan mengajukan perubahan ke Disdukcapil. Gratis dan selesai dalam 1-5 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pindah domisili dan proses KK',
                'kata_kunci' => ['pindah domisili', 'pindah alamat', 'pindah rumah'],
                'jawaban_atau_konten' => 'Jika pindah dalam satu desa, cukup lapor ke kantor desa untuk pembaruan data. Jika pindah ke desa/kota lain, urus surat pindah di kantor desa, kemudian daftar di desa tujuan dalam waktu 14 hari. Bawa KK asli, KTP, dan surat pengantar. Proses gratis.',
            ],
            [
                'kunci' => 'faq-adm-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mengetahui nomor KK',
                'kata_kunci' => ['nomor kk', 'cek nomor kk', 'lupa nomor kk'],
                'jawaban_atau_konten' => 'Nomor KK tercantum di pojok kanan atas Kartu Keluarga. Jika lupa atau KK hilang, bisa ditanyakan ke kantor desa atau cek melalui layanan online Disdukcapil Aceh. Bawa KTP untuk verifikasi identitas.',
            ],
            [
                'kunci' => 'faq-adm-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Melapor KK yang sudah tidak berlaku',
                'kata_kunci' => ['kk tidak berlaku', 'kk kadaluarsa', 'lapor kk'],
                'jawaban_atau_konten' => 'KK yang sudah tidak berlaku (misalnya karena pemegang meninggal atau pindah) harus dilaporkan ke kantor desa untuk pencatatan. Bawa KK asli, surat keterangan kematian (jika meninggal), atau surat pindah. Proses gratis dan penting untuk menjaga akurasi data kependudukan.',
            ],
            [
                'kunci' => 'faq-adm-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kartu Keluarga untuk warga tidak mampu',
                'kata_kunci' => ['kk miskin', 'kk bantuan', 'data tidak mampu'],
                'jawaban_atau_konten' => 'Warga tidak mampu yang belum memiliki KK bisa mengajukan pembuatan KK baru melalui kantor desa. Sertakan surat keterangan tidak mampu dari Keuchik. Petugas desa akan memprioritaskan pengurusannya. Semua proses gratis.',
            ],
            [
                'kunci' => 'faq-adm-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mencetak ulang KK karena perubahan data',
                'kata_kunci' => ['cetak ulang kk', 'kk baru setelah ubah data'],
                'jawaban_atau_konten' => 'Setelah perubahan data di KK disetujui oleh Disdukcapil, Anda bisa mencetak ulang KK yang baru dengan data terkini. Datang ke kantor desa dengan membawa KK lama. Proses cetak ulang gratis dan selesai dalam 1-3 hari kerja.',
            ],

            // ==================== KTP ====================
            [
                'kunci' => 'faq-adm-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara membuat KTP baru (e-KTP)',
                'kata_kunci' => ['ktp baru', 'buat ktp', 'e-ktp', 'daftar ktp'],
                'jawaban_atau_konten' => 'Untuk membuat KTP baru (e-KTP), datang ke kantor desa untuk mendapatkan surat pengantar, lalu ke Dinas Kependudukan dan Pencatatan Sipil untuk perekaman data biometrik. Bawa fotokopi KK, akta kelahiran, dan pas foto 3x4. Warga yang sudah berusia 17 tahun atau sudah menikah wajib memiliki KTP. Biaya gratis, proses perekaman sekitar 15-30 menit, cetak KTP sekitar 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Perpanjangan KTP',
                'kata_kunci' => ['perpanjang ktp', 'ktp expired', 'ktp habis masa berlaku'],
                'jawaban_atau_konten' => 'KTP yang sudah habis masa berlakunya perlu diperpanjang. Datang ke kantor desa untuk surat pengantar, lalu ke Disdukcapil dengan membawa KTP asli dan fotokopi KK. Perekaman ulang tidak diperlukan jika data biometrik masih valid. Biaya gratis, proses 1-5 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'KTP hilang, bagaimana mengurusnya?',
                'kata_kunci' => ['ktp hilang', 'kehilangan ktp', 'ganti ktp'],
                'jawaban_atau_konten' => 'Jika KTP hilang, laporkan ke kantor polisi untuk surat keterangan kehilangan. Kemudian datang ke kantor desa dengan surat kehilangan dan fotokopi KK untuk mendapatkan surat pengantar pembuatan KTP baru. Perekaman ulang di Disdukcapil. Biaya gratis, proses 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'KTP belum jadi, bagaimana mengecek statusnya?',
                'kata_kunci' => ['cek ktp', 'ktp belum jadi', 'status ktp', 'cek status cetak ktp'],
                'jawaban_atau_konten' => 'Untuk mengecek status pencetakan KTP, bisa datang ke kantor desa atau menghubungi Disdukcapil. Biasanya KTP selesai dicetak dalam 1-2 minggu setelah perekaman. Jika sudah lama belum jadi, petugas desa bisa membantu mengecek ke Disdukcapil.',
            ],
            [
                'kunci' => 'faq-adm-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'KTP luar daerah, bagaimana mengurusnya di sini?',
                'kata_kunci' => ['ktp luar daerah', 'ktp luar kota', 'ktp domisili'],
                'jawaban_atau_konten' => 'Pendatang dengan KTP luar daerah yang sudah menetap di Gampong Udeung bisa mengajukan perpindahan domisili KTP ke kantor desa. Bawa KTP lama, KK asli (jika sudah punya KK di sini), dan surat pengantar dari Keuchik. Proses pindah datang ke Disdukcapil. Gratis, waktu 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'KTP untuk warga negara asing',
                'kata_kunci' => ['ktp wna', 'ktp asing', 'ktp warga negara asing'],
                'jawaban_atau_konten' => 'Warga negara asing yang menetap di Indonesia memiliki KITAP/KITAS sebagai pengganti KTP. Untuk keperluan administrasi desa, bawa KITAP/KITAS asli dan fotokopi, surat izin tinggal dari imigrasi, serta surat pengantar dari keuchik. Proses registrasi di kantor desa gratis.',
            ],
            [
                'kunci' => 'faq-adm-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mengubah data di KTP',
                'kata_kunci' => ['ubah data ktp', 'update ktp', 'koreksi ktp'],
                'jawaban_atau_konten' => 'Untuk mengubah data di KTP (nama, alamat, pekerjaan, dll), ajukan permohonan perubahan ke Disdukcapil melalui kantor desa. Bawa KTP asli, KK, dan dokumen pendukung perubahan. Proses gratis, waktu 1-5 hari kerja tergantung jenis perubahan.',
            ],
            [
                'kunci' => 'faq-adm-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'KTP rusak, apakah perlu diganti?',
                'kata_kunci' => ['ktp rusak', 'ktp tidak terbaca', 'ganti ktp rusak'],
                'jawaban_atau_konten' => 'KTP yang rusak atau sudah tidak terbaca sebaiknya diganti dengan yang baru. Datang ke kantor desa untuk surat pengantar, lalu ke Disdukcapil dengan membawa KTP rusak dan fotokopi KK. Perekaman ulang mungkin diperlukan. Gratis, proses 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Anak sudah 17 tahun, bagaimana cara membuat KTP?',
                'kata_kunci' => ['anak 17 tahun ktp', 'ktp pertama', 'ktp usia 17'],
                'jawaban_atau_konten' => 'Warga yang sudah berusia 17 tahun sudah wajib memiliki KTP. Datang ke kantor desa dengan membawa fotokopi KK, akta kelahiran, dan pas foto 3x4. Petugas desa akan membuatkan surat pengantar untuk perekaman e-KTP di Disdukcapil. Biaya gratis.',
            ],
            [
                'kunci' => 'faq-adm-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mendapatkan surat pengantar KTP',
                'kata_kunci' => ['surat pengantar ktp', 'surat pengantar buat ktp'],
                'jawaban_atau_konten' => 'Surat pengantar KTP bisa didapatkan di kantor keuchik dengan membawa fotokopi KK dan pas foto 3x4. Petugas desa akan menerbitkan surat pengantar yang berlaku untuk perekaman KTP di Disdukcapil. Gratis dan selesai dalam 1 hari.',
            ],
            [
                'kunci' => 'faq-adm-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'KTP elang atau KTP elektronik',
                'kata_kunci' => ['ktp elang', 'ktp elektronik', 'e-ktp'],
                'jawaban_atau_konten' => 'KTP Elang adalah KTP elektronik yang memiliki chip berisi data biometrik. Semua KTP baru sekarang adalah KTP Elang. Proses pembuatannya sama dengan e-KTP biasa, datang ke kantor desa untuk surat pengantar, lalu perekaman di Disdukcapil. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Duplikat KTP untuk keperluan administrasi',
                'kata_kunci' => ['duplikat ktp', 'ktp ganda', 'ktp cadangan'],
                'jawaban_atau_konten' => 'Untuk keperluan administrasi tertentu yang memerlukan KTP asli, Anda bisa mengurus surat keterangan pengganti KTP di kantor desa. Bawa KTP asli, fotokopi KK, dan pas foto. Surat keterangan ini berfungsi sementara sambil menunggu KTP jadi.',
            ],

            // ==================== AKTA NIKAH ====================
            [
                'kunci' => 'faq-adm-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mengurus akta nikah',
                'kata_kunci' => ['akta nikah', 'nikah', 'buku nikah', 'pernikahan'],
                'jawaban_atau_konten' => 'Akta nikah dikeluarkan oleh KUA (Kantor Urusan Agama) untuk Muslim atau Disdukcapil untuk non-Muslim. Untuk nikah di KUA, bawa surat pengantar dari keuchik, fotokopi KTP calon pengantin, fotokopi KK, akta kelahiran, pas foto, dan surat izin orang tua (jika belum 21 tahun). Pendaftaran nikah dilakukan minimal 10 hari sebelum tanggal pernikahan. Biaya nikah di KUA gratis untuk menikah pada jam kerja.',
            ],
            [
                'kunci' => 'faq-adm-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Nikah di luar KUA, bagaimana mengurus akta nikahnya?',
                'kata_kunci' => ['nikah di luar kua', 'nikah di luar', 'catat nikah'],
                'jawaban_atau_konten' => 'Jika menikah di luar KUA (misalnya di masjid atau rumah), akta nikah tetap bisa diurus di KUA dengan membawa surat keterangan nikah dari penghulu/ulama yang menikahkan, surat pengantar dari keuchik, fotokopi KTP dan KK kedua mempelai, serta dokumen lainnya. Proses pencatatan gratis di KUA.',
            ],
            [
                'kunci' => 'faq-adm-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Nikah siri, apakah bisa diuruskan akta nikah?',
                'kata_kunci' => ['nikah siri', 'nikah tidak resmi', 'nikah tidak dicatat'],
                'jawaban_atau_konten' => 'Nikah siri yang tidak tercatat di KUA tidak memiliki akta nikah resmi. Untuk mengesahkan secara hukum, pasangan bisa melakukan pencatatan nikah di KUA dengan membawa surat keterangan nikah dari ulama/penghulu yang menikahkan, fotokopi KTP dan KK, serta dokumen pendukung lainnya. Pencatatan ini gratis dan penting untuk keperluan administrasi kependudukan.',
            ],
            [
                'kunci' => 'faq-adm-031',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Akta nikah hilang, bagaimana mencetak ulang?',
                'kata_kunci' => ['akta nikah hilang', 'buku nikah hilang', 'cetak ulang nikah'],
                'jawaban_atau_konten' => 'Jika akta nikah/buku nikah hilang, laporkan ke kantor polisi untuk surat keterangan kehilangan. Kemudian datang ke KUA dengan surat kehilangan, fotokopi KTP dan KK, serta surat pengantar dari keuchik. KUA akan menerbitkan duplikat akta nikah. Biaya gratis, proses 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-032',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cerai/perceraian, bagaimana prosesnya?',
                'kata_kunci' => ['cerai', 'perceraian', 'talak', 'gugat cerai'],
                'jawaban_atau_konten' => 'Perceraian untuk Muslim diajukan ke Pengadilan Agama dengan membawa akta nikah asli, fotokopi KTP dan KK, serta dokumen pendukung lainnya. Setelah ada putusan cerai dari pengadilan, laporkan ke KUA untuk pencatatan perceraian. Untuk non-Muslim, perceraian diurus di Pengadilan Negeri. Proses pengadilan berbeda-beda tergantung kasus.',
            ],
            [
                'kunci' => 'faq-adm-033',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mengubah data dalam akta nikah',
                'kata_kunci' => ['ubah data nikah', 'koreksi akta nikah', 'perubahan nama nikah'],
                'jawaban_atau_konten' => 'Untuk mengubah data dalam akta nikah (nama, tanggal lahir, dll), ajukan permohonan ke KUA dengan membawa akta nikah asli, dokumen pendukung perubahan (akta lahir, surat ganti nama), dan fotokopi KTP. Proses gratis, waktu 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-034',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Nikah campuran (WNI dan WNA)',
                'kata_kunci' => ['nikah campuran', 'nikah dengan wna', 'nikah wni wna'],
                'jawaban_atau_konten' => 'Pernikahan antara WNI dan WNA memerlukan izin dari Kementerian Agama atau Disdukcapil. Bawa paspor dan KITAS/KITAP WNA, KTP dan KK WNI, surat pengantar dari keuchik, serta dokumen lain yang dipersyaratkan. Proses lebih kompleks dan memerlukan waktu lebih lama. Konsultasikan langsung ke KUA.',
            ],
            [
                'kunci' => 'faq-adm-035',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Akta nikah untuk pernikahan kedua',
                'kata_kunci' => ['nikah kedua', 'menikah lagi', 'akta nikah kedua'],
                'jawaban_atau_konten' => 'Untuk menikah lagi setelah cerai atau ditinggal wafat, perlu melampirkan akta perceraian dari pengadilan atau surat keterangan kematian pasangan sebelumnya. Bawa dokumen tersebut bersama dokumen nikah biasa ke KUA. Proses pencatatan gratis.',
            ],
            [
                'kunci' => 'faq-adm-036',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Biaya nikah di KUA',
                'kata_kunci' => ['biaya nikah kua', 'gratis nikah', 'nikah gratis'],
                'jawaban_atau_konten' => 'Nikah di KUA pada jam kerja (Senin-Jumat pukul 08.00-15.00) adalah GRATIS sesuai peraturan pemerintah. Untuk nikah di luar jam kerja atau di luar KUA, dikenakan biaya sesuai ketentuan yang berlaku di masing-masing KUA. Silakan tanyakan langsung ke KUA setempat untuk informasi biaya terkini.',
            ],
            [
                'kunci' => 'faq-adm-037',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat pengantar nikah dari desa',
                'kata_kunci' => ['surat pengantar nikah', 'surat nikah dari keuchik'],
                'jawaban_atau_konten' => 'Surat pengantar nikah bisa didapatkan di kantor keuchik dengan membawa fotokopi KTP calon pengantin, fotokopi KK, dan surat keterangan belum menikah dari desa. Petugas desa akan menerbitkan surat pengantar yang berlaku untuk pendaftaran nikah di KUA. Gratis dan selesai dalam 1 hari.',
            ],

            // ==================== AKTA KELAHIRAN ====================
            [
                'kunci' => 'faq-adm-038',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara membuat akta kelahiran anak',
                'kata_kunci' => ['akta kelahiran', 'daftar lahir', 'akta anak baru lahir'],
                'jawaban_atau_konten' => 'Akta kelahiran anak dibuat di Disdukcapil melalui kantor desa. Bawa surat keterangan lahir dari bidan/dokter/rumah sakit, fotokopi KTP orang tua, KK, dan surat pengantar dari keuchik. Pendaftaran harus dilakukan maksimal 60 hari setelah kelahiran. Biaya gratis, proses 1-5 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-039',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Membuat akta kelahiran terlambat (lebih dari 60 hari)',
                'kata_kunci' => ['akta kelahiran terlambat', 'akta telat', 'daftar lahir terlambat'],
                'jawaban_atau_konten' => 'Jika pendaftaran akta kelahiran melewati 60 hari, tetap bisa diurus tetapi memerlukan surat keterangan lahir dari keuchik dan saksi-saksi. Bawa fotokopi KTP orang tua, KK, surat keterangan lahir (jika ada), dan surat keterangan dari keuchik tentang kelahiran anak tersebut. Proses gratis, waktu 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-040',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Akta kelahiran hilang, bagaimana mencetak ulang?',
                'kata_kunci' => ['akta kelahiran hilang', 'cetak ulang akta lahir'],
                'jawaban_atau_konten' => 'Jika akta kelahiran hilang, laporkan ke kantor polisi untuk surat keterangan kehilangan. Kemudian datang ke kantor desa dengan surat kehilangan dan fotokopi KTP orang tua. Petugas desa akan mengajukan cetak ulang ke Disdukcapil. Gratis, proses 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-041',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Mengubah nama di akta kelahiran',
                'kata_kunci' => ['ubah nama akta', 'ganti nama lahir', 'koreksi akta kelahiran'],
                'jawaban_atau_konten' => 'Untuk mengubah nama di akta kelahiran, ajukan permohonan ke Disdukcapil melalui kantor desa dengan membawa akta kelahiran asli, fotokopi KTP orang tua, surat keterangan ganti nama (jika ada), dan dokumen pendukung lainnya. Proses gratis, waktu 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-042',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Akta kelahiran untuk anak angkat',
                'kata_kunci' => ['akta kelahiran anak angkat', 'anak angkat', 'adopsi'],
                'jawaban_atau_konten' => 'Untuk akta kelahiran anak angkat, diperlukan surat keterangan pengangkatan anak dari pengadilan, surat keterangan lahir dari rumah sakit/bidan, KTP dan KK orang tua angkat, serta dokumen lain yang dipersyaratkan. Proses lebih kompleks, silakan konsultasi ke Disdukcapil.',
            ],
            [
                'kunci' => 'faq-adm-043',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat keterangan lahir dari desa',
                'kata_kunci' => ['surat keterangan lahir', 'surat lahir dari desa'],
                'jawaban_atau_konten' => 'Surat keterangan lahir bisa didapatkan di kantor keuchik dengan membawa surat keterangan lahir dari bidan/dokter, fotokopi KTP orang tua, dan KK. Petugas desa akan menerbitkan surat keterangan yang diperlukan untuk pembuatan akta kelahiran di Disdukcapil. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-044',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Anak lahir di luar rumah sakit/puskesmas',
                'kata_kunci' => ['anak lahir di rumah', 'lahir tanpa bantuan medis', 'lahir di rumah'],
                'jawaban_atau_konten' => 'Anak yang lahir di luar fasilitas kesehatan tetap bisa didaftarkan akta kelahirannya. Bawa surat keterangan lahir dari bidan desa atau saksi yang hadir saat persalinan, fotokopi KTP orang tua, dan KK ke kantor desa. Petugas akan membantu mengurus ke Disdukcapil. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-045',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Biaya pembuatan akta kelahiran',
                'kata_kunci' => ['biaya akta kelahiran', 'gratis akta lahir'],
                'jawaban_atau_konten' => 'Pembuatan akta kelahiran di Disdukcapil adalah GRATIS sesuai peraturan pemerintah. Tidak ada biaya apapun untuk pengurusan akta kelahiran baru maupun cetak ulang. Hati-hati terhadap pungutan liar yang mengatasnamakan Disdukcapil.',
            ],

            // ==================== AKTA KEMATIAN ====================
            [
                'kunci' => 'faq-adm-046',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mengurus akta kematian',
                'kata_kunci' => ['akta kematian', 'surat kematian', 'kematian'],
                'jawaban_atau_konten' => 'Akta kematian diurus di Disdukcapil melalui kantor desa. Bawa surat keterangan kematian dari rumah sakit/puskesmas, fotokopi KTP almarhum/almarhummah, KK, KTP pelapor, dan surat pengantar dari keuchik. Pendaftaran harus dilakukan maksimal 30 hari setelah kematian. Gratis, proses 1-5 hari kerja.',
            ],
            [
                'kunci' => 'faq-adm-047',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kematian terjadi di luar daerah',
                'kata_kunci' => ['kematian luar daerah', 'meninggal di luar kota', 'akta kematian luar daerah'],
                'jawaban_atau_konten' => 'Jika kematian terjadi di luar daerah, dapatkan surat keterangan kematian dari rumah sakit/puskesmas/kecamatan di daerah tersebut. Kemudian bawa surat tersebut ke kantor desa untuk pembuatan surat pengantar ke Disdukcapil. Akta kematian tetap bisa dibuat di daerah asal almarhum/almarhummah. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-048',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Akta kematian hilang, bagaimana mencetak ulang?',
                'kata_kunci' => ['akta kematian hilang', 'cetak ulang akta kematian'],
                'jawaban_atau_konten' => 'Jika akta kematian hilang, laporkan ke kantor polisi untuk surat keterangan kehilangan. Kemudian ke kantor desa dengan surat kehilangan, fotokopi KK, dan KTP pelapor. Petugas akan mengajukan cetak ulang ke Disdukcapil. Gratis, proses 1-2 minggu.',
            ],
            [
                'kunci' => 'faq-adm-049',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Siapa yang bisa melapor kematian?',
                'kata_kunci' => ['pelapor kematian', 'siapa yang melapor kematian'],
                'jawaban_atau_konten' => 'Yang bisa melapor kematian adalah anggota keluarga terdekat (istri/suami, anak, orang tua, saudara) atau pihak yang mengetahui kematian tersebut. Pelapor harus membawa KTP asli dan fotokopi KK almarhum/almarhummah.',
            ],
            [
                'kunci' => 'faq-adm-050',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kematian tanpa keterangan dari dokter/rumah sakit',
                'kata_kunci' => ['kematian tanpa surat dokter', 'meninggal di rumah', 'kematian alami'],
                'jawaban_atau_konten' => 'Jika kematian terjadi di rumah tanpa keterangan dari dokter/rumah sakit, perlu dibuat surat keterangan kematian dari Keuchik dengan disaksikan oleh dua orang saksi yang mengetahui kematian tersebut. Bawa KTP saksi, fotokopi KTP almarhum/almarhummah, dan KK ke kantor desa.',
            ],

            // ==================== SURAT PINDAH ====================
            [
                'kunci' => 'faq-adm-051',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mengurus surat pindah keluar daerah',
                'kata_kunci' => ['surat pindah', 'pindah keluar', 'pindah domisili'],
                'jawaban_atau_konten' => 'Untuk pindah keluar daerah, datang ke kantor desa dengan membawa KK asli, KTP, dan surat keterangan tujuan pindah dari desa tujuan (jika sudah ada). Petugas desa akan menerbitkan surat pengantar ke Disdukcapil untuk pembuatan surat pindah. Setelah mendapat surat pindah, daftar di desa tujuan dalam 14 hari. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-052',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pindah masuk ke Gampong Udeung',
                'kata_kunci' => ['pindah masuk', 'datang ke desa', 'pendatang baru'],
                'jawaban_atau_konten' => 'Pendatang yang ingin pindah masuk ke Gampong Udeung harus membawa surat pindah dari desa asal, KTP, KK asli, dan surat pengantar dari keuchik desa asal. Daftar di kantor keuchik setempat untuk mendapatkan surat keterangan pindah masuk. Kemudian urus perubahan data di Disdukcapil. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-053',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat pengantar pindah dari desa',
                'kata_kunci' => ['surat pengantar pindah', 'surat pindah dari desa'],
                'jawaban_atau_konten' => 'Surat pengantar pindah dari desa bisa didapatkan di kantor keuchik dengan membawa KK asli, KTP, dan alasan pindah yang jelas. Petugas desa akan menerbitkan surat pengantar yang akan diteruskan ke Disdukcapil untuk pembuatan resmi surat pindah. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-054',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Pindah dalam satu desa, perlu diurus apa?',
                'kata_kunci' => ['pindah dalam desa', 'pindah rumah di desa', 'pindah tetangga'],
                'jawaban_atau_konten' => 'Jika pindah dalam satu desa (misalnya dari satu dusun ke dusun lain), cukup lapor ke kantor keuchik untuk pembaruan data alamat. Bawa KK dan KTP asli. Tidak perlu surat pindah resmi dari Disdukcapil. Proses gratis dan cepat.',
            ],
            [
                'kunci' => 'faq-adm-055',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Masa berlaku surat pindah',
                'kata_kunci' => ['masa berlaku surat pindah', 'surat pindah kedaluarsa'],
                'jawaban_atau_konten' => 'Surat pindah berlaku selama 1 tahun sejak diterbitkan. Setelah masa berlaku habis, surat pindah tidak bisa digunakan lagi. Jika belum sempat mendaftar di desa tujuan, perlu mengurus surat pindah baru di desa asal.',
            ],
            [
                'kunci' => 'faq-adm-056',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kewajiban pendatang baru melapor',
                'kata_kunci' => ['kewajiban melapor', 'pendatang wajib lapor', ' registrasi pendatang'],
                'jawaban_atau_konten' => 'Setiap pendatang baru wajib melapor ke kantor keuchik maksimal 14 hari setelah tiba di Gampong Udeung. Bawa surat pindah dari desa asal, KTP, dan KK. Kewajiban melapor ini sesuai dengan peraturan daerah tentang ketertiban umum.',
            ],
            [
                'kunci' => 'faq-adm-057',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat keterangan pindah untuk anak',
                'kata_kunci' => ['pindah anak', 'surat pindah anak', 'pindah sekolah'],
                'jawaban_atau_konten' => 'Untuk pindah anak, orang tua membawa KK asli, akta kelahiran anak, dan KTP orang tua ke kantor desa. Petugas akan membuatkan surat pengantar pindah yang bisa digunakan untuk administrasi sekolah di daerah tujuan. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-058',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Biaya pengurusan surat pindah',
                'kata_kunci' => ['biaya surat pindah', 'gratis surat pindah'],
                'jawaban_atau_konten' => 'Semua proses pengurusan surat pindah di kantor desa adalah GRATIS. Tidak ada biaya apapun. Hati-hati terhadap pungutan liar. Jika dimintai biaya, laporkan ke aparat desa atau kecamatan.',
            ],

            // ==================== SURAT KETERANGAN LAINNYA ====================
            [
                'kunci' => 'faq-adm-059',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Usaha (SKU)',
                'kata_kunci' => ['sku', 'surat keterangan usaha', 'surat usaha'],
                'jawaban_atau_konten' => 'Surat Keterangan Usaha (SKU) dibutuhkan untuk keperluan pinjaman modal, perizinan usaha, dll. Datang ke kantor desa dengan membawa fotokopi KTP, fotokopi KK, dan keterangan tentang jenis usaha yang dijalankan. Petugas desa akan menerbitkan SKU. Gratis, selesai dalam 1 hari.',
            ],
            [
                'kunci' => 'faq-adm-060',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Domisili (SKD)',
                'kata_kunci' => ['skd', 'surat keterangan domisili', 'surat domisili'],
                'jawaban_atau_konten' => 'Surat Keterangan Domisili (SKD) diperlukan untuk keperluan administrasi seperti pendaftaran sekolah, pembuatan rekening bank, dll. Datang ke kantor desa dengan membawa fotokopi KTP dan KK. Petugas akan menerbitkan SKD. Gratis, selesai dalam 1 hari.',
            ],
            [
                'kunci' => 'faq-adm-061',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Tidak Mampu (SKTM)',
                'kata_kunci' => ['sktm', 'surat keterangan tidak mampu', 'surat miskin'],
                'jawaban_atau_konten' => 'Surat Keterangan Tidak Mampu (SKTM) diperlukan untuk keperluan beasiswa, bantuan sosial, pengurusan keringanan biaya, dll. Datang ke kantor desa dengan membawa fotokopi KTP dan KK, serta surat pernyataan tidak mampu. Keuchik akan menerbitkan SKTM berdasarkan data kemiskinan di desa. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-062',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Catatan Kepolisian (SKCK)',
                'kata_kunci' => ['skck', 'surat keterangan catatan kepolisian', 'skck polres'],
                'jawaban_atau_konten' => 'SKCK dikeluarkan oleh Kepolisian, bukan desa. Namun untuk pengurusannya, Anda memerlukan surat pengantar dari kantor desa. Datang ke kantor desa dengan membawa fotokopi KTP dan KK. Petugas akan menerbitkan surat pengantar yang kemudian dibawa ke Kepolisian untuk pembuatan SKCK. Biaya pembuatan SKCK di Kepolisian sesuai ketentuan yang berlaku.',
            ],
            [
                'kunci' => 'faq-adm-063',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Belum Menikah (SKBM)',
                'kata_kunci' => ['skbm', 'surat keterangan belum menikah', 'surat belum kawin'],
                'jawaban_atau_konten' => 'Surat Keterangan Belum Menikah (SKBM) diperlukan untuk keperluan bekerja di luar negeri, kuliah, dll. Datang ke kantor desa dengan membawa fotokopi KTP, KK, dan akta kelahiran. Petugas akan menerbitkan SKBM. Gratis, selesai dalam 1 hari.',
            ],
            [
                'kunci' => 'faq-adm-064',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Penghasilan',
                'kata_kunci' => ['surat penghasilan', 'surat keterangan penghasilan', 'slip gaji'],
                'jawaban_atau_konten' => 'Surat Keterangan Penghasilan diperlukan untuk keperluan kredit, pengajuan pinjaman, dll. Datang ke kantor desa dengan membawa fotokopi KTP, KK, dan keterangan tentang pekerjaan/penghasilan. Petugas akan menerbitkan surat keterangan penghasilan berdasarkan data yang tersedia. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-065',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Beda Nama',
                'kata_kunci' => ['surat beda nama', 'perbedaan nama', 'nama berbeda'],
                'jawaban_atau_konten' => 'Surat Keterangan Beda Nama diperlukan jika ada perbedaan nama antara dokumen yang satu dengan lainnya (misalnya nama di KTP berbeda dengan nama di ijazah). Datang ke kantor desa dengan membawa fotokopi KTP, KK, dan dokumen yang menunjukkan perbedaan nama. Petugas akan menerbitkan surat keterangan tersebut. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-066',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Khusus (SKU) untuk pengurusan administrasi',
                'kata_kunci' => ['surat keterangan khusus', 'sku khusus'],
                'jawaban_atau_konten' => 'Surat Keterangan Khusus bisa dibuat di kantor desa untuk berbagai keperluan administrasi yang tidak tercakup dalam surat keterangan lainnya. Jelaskan keperluan Anda kepada petugas desa, dan mereka akan membantu menerbitkan surat yang sesuai. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-067',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Kerja',
                'kata_kunci' => ['surat kerja', 'surat keterangan kerja', 'surat domisili kerja'],
                'jawaban_atau_konten' => 'Surat Keterangan Kerja diperlukan untuk keperluan administrasi di tempat kerja. Datang ke kantor desa dengan membawa fotokopi KTP, KK, dan keterangan tentang pekerjaan Anda. Petugas akan menerbitkan surat keterangan kerja. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-068',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Bebas Narkoba',
                'kata_kunci' => ['surat bebas narkoba', 'tes narkoba', 'surat keterangan narkoba'],
                'jawaban_atau_konten' => 'Surat Keterangan Bebas Narkoba dikeluarkan oleh rumah sakit atau laboratorium kesehatan setelah melakukan tes. Untuk keperluan surat pengantar, datang ke kantor desa dengan fotokopi KTP dan KK. Petugas akan membuatkan surat pengantar untuk tes narkoba di fasilitas kesehatan. Biaya tes narkoba sesuai ketentuan rumah sakit/laboratorium.',
            ],
            [
                'kunci' => 'faq-adm-069',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Aktif Kuliah/Kerja',
                'kata_kunci' => ['surat aktif kuliah', 'surat aktif kerja'],
                'jawaban_atau_konten' => 'Surat Keterangan Aktif Kuliah/Kerja biasanya dikeluarkan oleh institusi/perusahaan terkait. Namun untuk keperluan administrasi desa, bisa dimintakan surat pengantar dari kantor desa. Bawa fotokopi KTP, KK, dan bukti kuliah/kerja. Gratis.',
            ],
            [
                'kunci' => 'faq-adm-070',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat Keterangan Pindah Agama',
                'kata_kunci' => ['surat pindah agama', 'masuk islam', 'pindah agama'],
                'jawaban_atau_konten' => 'Untuk urusan perubahan agama dalam data kependudukan, perlu surat keterangan dari tokoh agama atau lembaga keagamaan terkait, serta putusan pengadilan (jika diperlukan). Datang ke kantor desa dengan membawa dokumen-dokumen tersebut. Proses lebih kompleks, silakan konsultasi ke Disdukcapil.',
            ],

            // ==================== BANTUAN SOSIAL ====================
            [
                'kunci' => 'faq-adm-071',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mendaftar Bantuan Langsung Tunai (BLT)',
                'kata_kunci' => ['blt', 'bantuan langsung tunai', 'daftar blt', 'blt dana desa'],
                'jawaban_atau_konten' => 'Pendaftaran BLT dilakukan di kantor keuchik dengan membawa fotokopi KTP, KK, surat keterangan tidak mampu, dan foto rumah. Keuchik akan mengusulkan nama warga yang memenuhi syarat ke kecamatan. BLT diberikan kepada warga miskin dan rentan miskin. Informasi terkait jadwal dan kuota bisa ditanyakan langsung ke kantor desa.',
            ],
            [
                'kunci' => 'faq-adm-072',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan Sosial Tunai (BST) dari Kemensos',
                'kata_kunci' => ['bst', 'bantuan sosial tunai', 'kemensos', 'bansos'],
                'jawaban_atau_konten' => 'BST dari Kementerian Sosial diberikan kepada keluarga miskin dan rentan miskin. Penerima BST biasanya sudah terdata dalam DTKS (Data Terpadu Kesejahteraan Sosial). Untuk mengecek apakah Anda terdaftar, datang ke kantor desa dengan membawa KTP dan KK. Jika belum terdaftar, bisa mengajukan usulan melalui keuchik.',
            ],
            [
                'kunci' => 'faq-adm-073',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan Pangan Non Tunai (BPNT)',
                'kata_kunci' => ['bpnt', 'bantuan pangan non tunai', 'bantuan beras', 'kartu sembako'],
                'jawaban_atau_konten' => 'BPNT adalah bantuan pangan berupa kartu elektronik yang bisa digunakan untuk membeli bahan pangan di e-warong yang ditunjuk. Penerima BPNT terdata dalam DTKS. Untuk mendaftar, datang ke kantor desa dengan KTP dan KK. Jika sudah menerima, pastikan kartu BPNT aktif dan saldo mencukupi.',
            ],
            [
                'kunci' => 'faq-adm-074',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Program Keluarga Harapan (PKH)',
                'kata_kunci' => ['pkh', 'program keluarga harapan', 'bantuan pkh'],
                'jawaban_atau_konten' => 'PKH adalah bantuan sosial bersyarat yang diberikan kepada keluarga miskin dengan komponen kesehatan dan pendidikan. Penerima PKH harus memenuhi kriteria: ibu hamil, anak usia sekolah, lansia, atau penyandang disabilitas. Untuk mendaftar, datang ke kantor desa dengan membawa KTP, KK, dan dokumen pendukung. Proses verifikasi dilakukan oleh dinas sosial.',
            ],
            [
                'kunci' => 'faq-adm-075',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan pertanian untuk petani',
                'kata_kunci' => ['bantuan pertanian', 'bantuan petani', 'subsidi pupuk', 'bantuan benih'],
                'jawaban_atau_konten' => 'Bantuan pertanian seperti pupuk bersubsidi, benih, dan alat pertanian bisa diakses melalui kantor desa. Petani terdaftar dalam data pertanian desa. Untuk mendapatkan bantuan, datang ke kantor desa dengan membawa fotokopi KTP, KK, dan surat keterangan sebagai petani dari keuchik. Kuota bantuan terbatas sesuai alokasi dari dinas pertanian.',
            ],
            [
                'kunci' => 'faq-adm-076',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan untuk lansia',
                'kata_kunci' => ['bantuan lansia', 'bantuan orang tua', 'bantuan jompo'],
                'jawaban_atau_konten' => 'Lansia yang membutuhkan bantuan bisa mengajukan melalui kantor desa. Jenis bantuan yang tersedia antara lain bantuan sosial tunai, bantuan pangan, dan bantuan keperluan sehari-hari. Datang ke kantor desa dengan membawa KTP lansia, KK, dan surat keterangan tidak mampu dari keuchik.',
            ],
            [
                'kunci' => 'faq-adm-077',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan untuk penyandang disabilitas',
                'kata_kunci' => ['bantuan disabilitas', 'bantuan difabel', 'bantuan orang cacat'],
                'jawaban_atau_konten' => 'Penyandang disabilitas berhak mendapatkan berbagai bantuan dari pemerintah. Untuk mendaftar, datang ke kantor desa dengan membawa KTP, KK, surat keterangan disabilitas dari rumah sakit/puskesmas, dan foto. Petugas desa akan mengusulkan ke dinas sosial untuk mendapatkan bantuan yang sesuai.',
            ],
            [
                'kunci' => 'faq-adm-078',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Cara mengecek status penerimaan bantuan sosial',
                'kata_kunci' => ['cek bantuan', 'status bansos', 'apakah dapat bantuan'],
                'jawaban_atau_konten' => 'Untuk mengecek status penerimaan bantuan sosial, datang ke kantor keuchik dengan membawa KTP dan KK. Petugas desa bisa mengecek apakah nama Anda terdaftar sebagai penerima bantuan. Anda juga bisa mengecek melalui website resmi Dinas Sosial atau Kementerian Sosial.',
            ],
            [
                'kunci' => 'faq-adm-079',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan pangan untuk ibu hamil dan balita',
                'kata_kunci' => ['bantuan ibu hamil', 'bantuan balita', 'gizi ibu hamil', 'pmt'],
                'jawaban_atau_konten' => 'Ibu hamil dan balita gizi kurang berhak mendapatkan bantuan pangan tambahan (PMT) dari posyandu. Untuk mendaftar, datang ke posyandu terdekat atau kantor desa dengan membawa KTP, KK, dan kartuMenuju Sehat (KMS). Bantuan diberikan secara berkala sesuai jadwal posyandu.',
            ],
            [
                'kunci' => 'faq-adm-080',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan untuk korban bencana alam',
                'kata_kunci' => ['bantuan bencana', 'bantuan korban banjir', 'bantuan gempa'],
                'jawaban_atau_konten' => 'Korban bencana alam bisa mendapatkan bantuan dari pemerintah melalui kantor desa. Datang ke kantor desa dengan membawa KTP, KK, dan bukti kerugian akibat bencana. Keuchik akan mengusulkan bantuan ke kecamatan dan dinas terkait. Bantuan bisa berupa bahan bangunan, sembako, dan bantuan tunai.',
            ],
            [
                'kunci' => 'faq-adm-081',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan biaya pendidikan',
                'kata_kunci' => ['bantuan pendidikan', 'beasiswa', 'bantuan sekolah', 'biaya sekolah'],
                'jawaban_atau_konten' => 'Bantuan biaya pendidikan tersedia untuk siswa tidak mampu. Untuk mendaftar, datang ke kantor desa dengan membawa fotokopi KTP orang tua, KK, rapor anak, dan surat keterangan tidak mampu dari keuchik. Petugas desa akan mengusulkan ke dinas pendidikan untuk mendapatkan bantuan.',
            ],
            [
                'kunci' => 'faq-adm-082',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan modal usaha kecil',
                'kata_kunci' => ['bantuan modal', 'pinjaman modal', 'bantuan usaha kecil'],
                'jawaban_atau_konten' => 'Bantuan modal usaha kecil bisa diakses melalui program KUR (Kredit Usaha Rakyat) atau bantuan dari dinas koperasi. Untuk pengurusan surat keterangan usaha (SKU) yang diperlukan, datang ke kantor desa dengan membawa fotokopi KTP dan KK. Petugas akan menerbitkan SKU gratis yang bisa digunakan untuk pengajuan pinjaman.',
            ],
            [
                'kunci' => 'faq-adm-083',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bantuan untuk janda/duda yang tidak mampu',
                'kata_kunci' => ['bantuan janda', 'bantuan duda', 'janda tidak mampu'],
                'jawaban_atau_konten' => 'Janda/duda yang tidak mampu bisa mengajukan bantuan sosial melalui kantor desa. Bawa KTP, KK, surat keterangan kematian pasangan (untuk janda/duda), dan surat keterangan tidak mampu dari keuchik. Petugas desa akan mengusulkan bantuan yang sesuai ke dinas sosial.',
            ],
            [
                'kunci' => 'faq-adm-084',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada bantuan untuk warga terdampak COVID-19?',
                'kata_kunci' => ['bantuan covid', 'bantuan pandemi', 'bantuan lockdown'],
                'jawaban_atau_konten' => 'Saat ini program bantuan COVID-19 sudah tidak berjalan lagi. Namun warga yang membutuhkan bisa mengajukan bantuan sosial reguler melalui kantor desa. Jenis bantuan yang tersedia antara lain BST, BLT, dan BPNT. Datang ke kantor desa dengan KTP dan KK untuk informasi lebih lanjut.',
            ],
            [
                'kunci' => 'faq-adm-085',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Hak dan kewajiban penerima bantuan sosial',
                'kata_kunci' => ['hak penerima bantuan', 'kewajiban penerima bansos'],
                'jawaban_atau_konten' => 'Penerima bantuan sosial berhak mendapatkan bantuan sesuai jenis yang diterima. Kewajiban penerima antara lain menggunakan bantuan sesuai peruntukan, melapor jika sudah mampu, dan tidak menjual bantuan yang diterima. Pelanggaran dapat menyebabkan pencabutan bantuan.',
            ],
        ];
    }
}
