<?php

namespace Database\Seeders\knowledge;

class BotKnowledgeFaqLayananPendidikan
{
    public function getFaqLayanan(): array
    {
        return [
            [
                'kunci' => 'faq-lay-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jam berapa kantor gampong buka?',
                'kata_kunci' => ['jam', 'kantor', 'buka', 'jam kerja', 'jam layanan'],
                'jawaban_atau_konten' => 'Jam pelayanan Kantor Keuchik Gampong Udeung:\n\nSenin - Kamis: 08.00 - 12.00 WIB\nJumat: 08.00 - 11.30 WIB\nSabtu - Minggu: TUTUP\n\nPelayanan pada hari libur nasional dan hari raya agama ditutup. Untuk keperluan mendesak di luar jam layanan, bisa menghubungi Keuchik melalui telepon.',
            ],
            [
                'kunci' => 'faq-lay-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana letak Kantor Keuchik Gampong Udeung?',
                'kata_kunci' => ['kantor', 'lokasi', 'alamat', 'dimana', 'letak'],
                'jawaban_atau_konten' => 'Kantor Keuchik Gampong Udeung terletak di:\n\nJl. Utama Gampong Udeung\nKecamatan Bandar Baru\nKabupaten Pidie Jaya\nProvinsi Aceh 24186\n\nKoordinat: -5.2333, 96.1667\n\nKantor ini berada di pusat gampong, dekat dengan Meunasah Gampong Udeung. Mudah dijangkau dari semua dusun.',
            ],
            [
                'kunci' => 'faq-lay-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah bisa mengurus surat lewat online?',
                'kata_kunci' => ['online', 'digital', 'internet', 'aplikasi', 'layanan online'],
                'jawaban_atau_konten' => 'Saat ini untuk pengurusan surat desa masih harus datang langsung ke Kantor Keuchik. Namun Anda bisa:\n\n- Mengunduh formulir melalui website gampong\n- Cek status pengajuan surat melalui portal warga\n- Pantau berita dan pengumuman gampong secara online\n\nRencana ke depan, sistem akan dikembangkan untuk pengajuan surat secara online melalui portal warga.',
            ],
            [
                'kunci' => 'faq-lay-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Siapa saja perangkat gampong yang bisa membantu?',
                'kata_kunci' => ['perangkat', 'keuchik', 'sekdes', 'staff', 'pejabat'],
                'jawaban_atau_konten' => 'Perangkat Gampong Udeung yang siap membantu:\n\nKeuchik (Kepala Desa): Tgk. H. Muhammad Yusuf\n- Urusan umum dan kebijakan gampong\n\nSekretaris Desa: Cut Nurhaliza, S.E.\n- Urusan administrasi dan surat-menyurat\n\nOperator: Petugas IT dan data\n- Pengelolaan website dan sistem informasi\n\nKeuchik Dusun: Perwakilan di setiap dusun\n- Koordinasi tingkat dusun\n\nTelepon Kantor: 0852-7000-1234',
            ],
            [
                'kunci' => 'faq-lay-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara memberikan saran atau keluhan?',
                'kata_kunci' => ['saran', 'keluhan', 'masukan', 'kritik', 'lapor'],
                'jawaban_atau_konten' => 'Untuk memberikan saran, masukan, atau keluhan:\n\n1. Langsung: Datang ke Kantor Keuchik\n2. Telepon: 0852-7000-1234\n3. Email: gampong.udeung@pidiejaya.go.id\n4. Portal Warga: Login ke sistem dan sampaikan melalui fitur pesan\n5. Musyawarah Gampong: Hadiri rapat gampong yang diadakan rutin\n\nSemua masukan akan ditampung dan dibahas dalam rapat perangkat gampong.',
            ],
            [
                'kunci' => 'faq-lay-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara login ke portal warga?',
                'kata_kunci' => ['login', 'portal', 'warga', 'masuk', 'sign in'],
                'jawaban_atau_konten' => 'Untuk login ke Portal Warga Gampong Udeung:\n\n1. Kunjungi website gampong\n2. Klik "Masuk Portal" atau "Login Warga"\n3. Masukkan NIK (16 digit) dan Nomor KK (16 digit)\n4. Klik "Masuk Ke Portal"\n\nPastikan:\n- NIK sudah terdaftar di database gampong\n- Status kependudukan aktif (Tetap)\n- Gunakan NIK dan KK yang sesuai\n\nJika ada masalah, hubungi Operator Gampong.',
            ],
            [
                'kunci' => 'faq-lay-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa yang bisa saya lakukan di portal warga?',
                'kata_kunci' => ['portal', 'warga', 'fitur', 'menu', 'fungsi'],
                'jawaban_atau_konten' => 'Di Portal Warga, Anda bisa:\n\nAjukan Surat:\n- Surat Keterangan Usaha (SKU)\n- Surat Keterangan Domisili (SKD)\n- Surat Keterangan Tidak Mampu (SKTM)\n- Surat Keterangan Kelahiran (SKL)\n- Surat Keterangan Kematian (SKK)\n- Surat Pengantar SKCK\n- Surat Keterangan Belum Menikah\n- Surat Keterangan Pindah\n- Surat Pengantar Nikah\n- Surat Keterangan Penghasilan\n\nPantau Status:\n- Lihat status pengajuan surat\n- Unduh surat yang sudah jadi\n\nInformasi:\n- Berita dan pengumuman gampong\n- Data statistik gampong',
            ],
            [
                'kunci' => 'faq-lay-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Lupa password portal warga, bagaimana?',
                'kata_kunci' => ['lupa', 'password', 'portal', 'lupa password', 'reset'],
                'jawaban_atau_konten' => 'Jika Anda lupa password portal warga:\n\n1. Klik "Lupa Password" di halaman login\n2. Masukkan NIK Anda\n3. Masukkan Nomor KK Anda\n4. Ikuti instruksi reset password melalui email atau SMS\n\nJika tidak berhasil:\n- Datang ke Kantor Keuchik membawa KTP dan KK\n- Operator akan membantu mereset password Anda\n\nTips: Simpan password di tempat aman atau gunakan password manager.',
            ],
            [
                'kunci' => 'faq-lay-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengecek status pengajuan surat?',
                'kata_kunci' => ['status', 'pengajuan', 'surat', 'cek', 'progress'],
                'jawaban_atau_konten' => 'Untuk mengecek status pengajuan surat:\n\nMelalui Portal Warga:\n1. Login ke portal warga\n2. Klik menu "Pengajuan Saya"\n3. Lihat status setiap pengajuan\n\nMelalui WhatsApp Bot:\n1. Kirim pesan ke nomor bot\n2. Ketik: status [nomor registrasi]\n3. Bot akan menampilkan status terkini\n\nAtau langsung ke Kantor Keuchik:\n- Bawa nomor registrasi yang diberikan saat pengajuan\n- Petugas akan cek di sistem',
            ],
            [
                'kunci' => 'faq-lay-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara melapor pengaduan ke gampong?',
                'kata_kunci' => ['pengaduan', 'lapor', 'keluhan', 'aduan', 'masalah'],
                'jawaban_atau_konten' => 'Untuk melapor pengaduan ke Gampong Udeung:\n\n1. Datang langsung ke Kantor Keuchik\n2. Isi formulir pengaduan\n3. Jelaskan masalah dengan detail\n4. Sertakan bukti jika ada (foto, dokumen)\n\nAtau melalui:\n- Telepon: 0852-7000-1234\n- Email: gampong.udeung@pidiejaya.go.id\n- Portal Warga: Menu "Pengaduan"\n\nSetiap pengaduan akan ditindaklanjuti dalam waktu 1-3 hari kerja. Anda akan mendapat notifikasi perkembangan.',
            ],
            [
                'kunci' => 'faq-lay-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa lama proses penanganan pengaduan?',
                'kata_kunci' => ['pengaduan', 'proses', 'lama', 'penanganan', 'waktu'],
                'jawaban_atau_konten' => 'Waktu penanganan pengaduan di Gampong Udeung:\n\n- Pengaduan ringan: 1-3 hari kerja\n- Pengaduan sedang: 3-7 hari kerja\n- Pengaduan berat: 7-14 hari kerja\n\nAnda akan mendapat notifikasi:\n1. Konfirmasi penerimaan pengaduan\n2. Proses penanganan\n3. Hasil penyelesaian\n\nJika pengaduan tidak ditangani dalam waktu yang ditentukan, silakan hubungi langsung Keuchik.',
            ],
            [
                'kunci' => 'faq-lay-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Jenis layanan apa saja yang tersedia di gampong?',
                'kata_kunci' => ['layanan', 'jenis', 'servis', 'fasilitas', 'tersedia'],
                'jawaban_atau_konten' => 'Layanan yang tersedia di Gampong Udeung:\n\n1. Layanan Administrasi:\n   - Pembuatan surat keterangan\n   - Pengurusan KK dan KTP\n   - Pendaftaran penduduk baru\n\n2. Layanan Kesehatan:\n   - Posyandu rutin\n   - Imunisasi anak\n\n3. Layanan Pendidikan:\n   - Perpustakaan gampong\n   - Beasiswa pelajar\n\n4. Layanan Sosial:\n   - Bantuan untuk warga tidak mampu\n   - Program pemberdayaan\n\n5. Layanan Keagamaan:\n   - Pengajian rutin\n   - TPA\n\nSemua layanan GRATIS untuk warga Gampong Udeung.',
            ],
            [
                'kunci' => 'faq-lay-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Berapa lama waktu tunggu pengurusan surat?',
                'kata_kunci' => ['waktu', 'tunggu', 'lama', 'proses', 'surat'],
                'jawaban_atau_konten' => 'Waktu tunggu pengurusan surat di Gampong Udeung:\n\n- Surat Keterangan Domisili: Langsung jadi\n- Surat Keterangan Usaha: Langsung jadi\n- Surat Keterangan Tidak Mampu: 1 hari kerja\n- Surat Keterangan Kelahiran: 1-2 hari kerja\n- Surat Keterangan Kematian: 1 hari kerja\n- Surat Pindah: 1-2 hari kerja\n- Surat Pengantar Nikah: 1-2 hari kerja\n- Surat Pengantar SKCK: Langsung jadi\n\nUntuk keperluan mendesak, bisa diusahakan lebih cepat dengan surat keterangan urgent dari Keuchik.',
            ],
            [
                'kunci' => 'faq-lay-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada biaya untuk pengurusan surat?',
                'kata_kunci' => ['biaya', 'gratis', 'bayar', 'ongkos', 'dikenakan'],
                'jawaban_atau_konten' => 'Semua layanan pengurusan surat di Kantor Keuchik Gampong Udeung adalah GRATIS, tidak dipungut biaya apapun.\n\nNamun untuk beberapa keperluan tertentu yang memerlukan pencetakan di Dinas Dukcapil atau instansi lain, mungkin ada biaya resmi sesuai ketetapan pemerintah.\n\nJika ada oknum yang memungut biaya untuk layanan di Kantor Keuchik, segera laporkan ke Keuchik.',
            ],
            [
                'kunci' => 'faq-lay-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengumpulkan berkas untuk pengajuan surat?',
                'kata_kunci' => ['berkas', 'kumpulkan', 'dokumen', 'persyaratan', 'syarat'],
                'jawaban_atau_konten' => 'Untuk mengumpulkan berkas pengajuan surat:\n\n1. Siapkan dokumen yang dibutuhkan (lihat jenis surat yang diurus)\n2. Fotokopi dokumen yang diperlukan:\n   - KTP\n   - KK\n   - Akta Nikah/Kelahiran\n   - Dokumen pendukung lainnya\n3. Kumpulkan dalam map atau amplop\n4. Bawa ke Kantor Keuchik\n\nTips:\n- Siapkan berkas sebelum datang ke kantor\n- Bawa dokumen asli untuk diverifikasi\n- Simpan salinan berkas untuk keperluan sendiri',
            ],
            [
                'kunci' => 'faq-lay-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara legalisir dokumen di gampong?',
                'kata_kunci' => ['legalisir', 'legalisasi', 'stempel', 'tanda tangan', 'dokumen'],
                'jawaban_atau_konten' => 'Untuk legalisir dokumen di Gampong Udeung:\n\n1. Datang ke Kantor Keuchik membawa:\n   - Dokumen asli yang akan dilegalisir\n   - Fotokopi dokumen tersebut\n   - KTP asli\n\n2. Petugas akan memverifikasi dokumen\n3. Keuchik akan menandatangani dan menempelkan stempel\n\nJenis dokumen yang bisa dilegalisir:\n- Ijazah\n- Transkrip nilai\n- Sertifikat\n- Surat keterangan lainnya\n\nBiaya: GRATIS. Proses: langsung jadi.',
            ],
            [
                'kunci' => 'faq-lay-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana bisa fotokopi dokumen?',
                'kata_kunci' => ['fotokopi', 'fotokopi', 'cetak', 'copy', 'dokumen'],
                'jawaban_atau_konten' => 'Tempat fotokopi di sekitar Gampong Udeung:\n\n1. Warung Fotokopi Pak Budi:\n   - Lokasi: Pusat Gampong Udeung\n   - Harga: Rp 500/halaman\n   - Jam buka: 08.00 - 17.00 WIB\n\n2. Toko Serba Ada:\n   - Lokasi: Pasar Udeung\n   - Harga: Rp 500/halaman\n   - Jam buka: 07.00 - 18.00 WIB\n\n3. Kantor Keuchik:\n   - Tersedia fasilitas fotokopi untuk keperluan pengurusan surat\n   - GRATIS untuk pengajuan surat gampong\n\nTips: Selalu fotokopi dokumen penting lebih dari satu untuk cadangan.',
            ],
            [
                'kunci' => 'faq-lay-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengurus surat pengantar nikah?',
                'kata_kunci' => ['nikah', 'surat pengantar', 'kua', 'menikah', 'pernikahan'],
                'jawaban_atau_konten' => 'Untuk mengurus Surat Pengantar Nikah (SPN):\n\n1. Datang ke Kantor Keuchik membawa:\n   - KTP asli dan fotokopi\n   - KK asli dan fotokopi\n   - Akta Kelahiran\n   - Surat Keterangan Belum Menikah dari Keuchik\n   - Pas foto 2x6 (biru) sebanyak 4 lembar\n   - Izin orang tua (jika calon mempelai di bawah 21 tahun)\n\n2. Isi formulir permohonan\n3. Keuchik akan menandatangani surat pengantar\n4. Bawa surat pengantar ke KUA Kec. Bandar Baru\n\nProses: 1-2 hari kerja. GRATIS.',
            ],
            [
                'kunci' => 'faq-lay-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengurus akta kelahiran anak?',
                'kata_kunci' => ['kelahiran', 'akta', 'anak', 'bayi', 'baru lahir'],
                'jawaban_atau_konten' => 'Untuk mengurus Akta Kelahiran anak:\n\n1. Datang ke Kantor Keuchik maksimal 60 hari setelah kelahiran\n2. Bawa persyaratan:\n   - Surat Keterangan Lahir dari Bidan/RS\n   - KTP Ayah dan Ibu\n   - KK\n   - Buku Nikah\n3. Isi formulir permohonan\n4. Nanti akan diarahkan ke Dinas Dukcapil\n\nBiaya: GRATIS. Penting untuk dicatat agar anak tercatat resmi.',
            ],
            [
                'kunci' => 'faq-lay-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengurus surat keterangan tidak mampu?',
                'kata_kunci' => ['sktm', 'tidak mampu', 'miskin', 'kurang mampu', 'bantuan'],
                'jawaban_atau_konten' => 'Untuk Surat Keterangan Tidak Mampu (SKTM):\n\n1. Datang ke Kantor Keuchik membawa:\n   - KTP asli dan fotokopi\n   - KK\n   - Foto rumah (depan dan dalam)\n   - Surat pernyataan tidak mampu dari tetangga (2 orang)\n2. Isi formulir permohonan\n3. Keuchik akan memverifikasi dan menandatangani\n\nProses: 1 hari kerja. GRATIS. SKTM bisa digunakan untuk pengajuan bantuan, beasiswa, dll.',
            ],
            [
                'kunci' => 'faq-lay-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara membuat surat keterangan domisili?',
                'kata_kunci' => ['domisili', 'surat domisili', 'skd', 'tinggal'],
                'jawaban_atau_konten' => 'Untuk Surat Keterangan Domisili (SKD):\n\n1. Datang ke Kantor Keuchik membawa:\n   - KTP asli dan fotokopi\n   - KK\n2. Isi formulir permohonan\n3. Keuchik akan menandatangani surat\n\nProses: langsung jadi. GRATIS. SKD berguna untuk keperluan kerja, sekolah, pinjaman, dll.',
            ],
            [
                'kunci' => 'faq-lay-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara membuat SKCK?',
                'kata_kunci' => ['skck', 'surat keterangan catatan kepolisian', 'polisi', 'keamanan'],
                'jawaban_atau_konten' => 'Untuk SKCK:\n\n1. Datang ke Kantor Keuchik untuk Surat Pengantar SKCK\n2. Bawa ke Polsek Bandar Baru atau Polres Pidie Jaya\n3. Persyaratan di Polsek:\n   - Surat Pengantar dari Keuchik\n   - Fotokopi KTP\n   - Fotokopi KK\n   - Fotokopi Akta Kelahiran/Ijazah\n   - Pas foto 4x6 (merah) 4 lembar\n4. Isi formulir dan foto\n\nBiaya: sesuai ketetapan. Proses: langsung jadi.',
            ],
            [
                'kunci' => 'faq-lay-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Surat keterangan usaha untuk apa?',
                'kata_kunci' => ['sku', 'usaha', 'surat usaha', 'dagang'],
                'jawaban_atau_konten' => 'Surat Keterangan Usaha (SKU) berguna untuk:\n\n1. Pengajuan pinjaman/kredit di bank\n2. Pendaftaran program pemerintah untuk UMKM\n3. Pengurusan izin usaha\n4. Persyaratan kerja\n5. Pengajuan bantuan modal usaha\n\nUntuk membuat SKU, datang ke Kantor Keuchik membawa KTP, KK, dan foto tempat usaha. GRATIS.',
            ],
            [
                'kunci' => 'faq-lay-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan bantuan BLT?',
                'kata_kunci' => ['blt', 'bantuan', 'tunai', 'dana desa', 'bantuan langsung'],
                'jawaban_atau_konten' => 'Untuk mendapatkan Bantuan Langsung Tunai (BLT) Dana Desa:\n\n1. Pastikan Anda terdaftar sebagai penerima manfaat\n2. Syarat penerima:\n   - Warga Gampong Udeung\n   - Berstatus tidak mampu\n   - Tidak menerima bantuan lain\n   - Belum bekerja atau penghasilan rendah\n3. Datang ke Kantor Keuchik saat penyaluran dengan membawa:\n   - KK asli\n   - KTP asli\n   - Surat keterangan tidak mampu\n\nInformasi jadwal penyaluran bisa dilihat di pengumuman gampong.',
            ],
            [
                'kunci' => 'faq-lay-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa saja bantuan yang tersedia di gampong ini?',
                'kata_kunci' => ['bantuan', 'program', 'jenis bantuan', 'dukungan'],
                'jawaban_atau_konten' => 'Bantuan yang tersedia di Gampong Udeung:\n\n1. BLT Dana Desa - Bantuan tunai untuk warga tidak mampu\n2. BST (Bantuan Sosial Tunai) dari Pemerintah Pusat\n3. BPNT (Bantuan Pangan Non Tunai) - Kartu Sembako\n4. Program Keluarga Harapan (PKH) - untuk ibu hamil dan anak\n5. Bantuan Pertanian - bibit, pupuk, alat\n6. Bantuan Modal UMKM - untuk usaha kecil\n7. Beasiswa Pendidikan - untuk pelajar kurang mampu\n8. Bantuan Kesehatan - untuk warga sakit\n\nUntuk mendaftar, datang ke Kantor Keuchik dengan membawa persyaratan yang dibutuhkan.',
            ],
            [
                'kunci' => 'faq-lay-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengecek data kependudukan?',
                'kata_kunci' => ['data', 'penduduk', 'cek', 'nik', 'status'],
                'jawaban_atau_konten' => 'Untuk mengecek data kependudukan:\n\n1. Online: Kunjungi website Dinas Dukcapil Kab. Pidie Jaya\n2. Offline: Datang ke Dinas Dukcapil dengan membawa KTP\n3. Melalui Keuchik: Datang ke Kantor Keuchik dengan membawa KTP dan KK\n\nData yang bisa dicek:\n- Status NIK aktif/tidak\n- Data di KK\n- Status mutasi (pindah/meninggal)\n- Data biometrik',
            ],
            [
                'kunci' => 'faq-lay-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'NIK saya tidak terdaftar, bagaimana?',
                'kata_kunci' => ['nik', 'tidak terdaftar', 'belum terdaftar', 'daftar nik'],
                'jawaban_atau_konten' => 'Jika NIK tidak terdaftar atau belum masuk database:\n\n1. Datang ke Kantor Keuchik membawa:\n   - KTP asli\n   - KK\n   - Akta Kelahiran\n2. Keuchik akan membantu mendaftarkan NIK ke Dinas Dukcapil\n3. Atau langsung ke Dinas Dukcapil Kab. Pidie Jaya\n\nPastikan semua data sudah benar agar tidak ada masalah di kemudian hari.',
            ],
            [
                'kunci' => 'faq-lay-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada layanan pengaduan online?',
                'kata_kunci' => ['pengaduan', 'online', 'lapor', 'internet', 'digital'],
                'jawaban_atau_konten' => 'Ya, layanan pengaduan online tersedia melalui:\n\n1. Portal Warga:\n   - Login ke portal\n   - Klik menu "Pengaduan"\n   - Isi formulir dengan lengkap\n   - Lampirkan bukti jika ada\n\n2. WhatsApp Bot:\n   - Kirim pesan ke nomor bot gampong\n   - Ketik: aduan [deskripsi masalah]\n   - Bot akan mencatat dan memberikan nomor tiket\n\n3. Email:\n   - Kirim ke: gampong.udeung@pidiejaya.go.id\n   - Subjek: Pengaduan - [judul masalah]\n\nSetiap pengaduan akan ditindaklanjuti dalam waktu 1-3 hari kerja.',
            ],
            [
                'kunci' => 'faq-lay-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara memperpanjang KTP yang sudah expired?',
                'kata_kunci' => ['ktp', 'expired', 'habis', 'masa berlaku', 'perpanjang'],
                'jawaban_atau_konten' => 'Untuk memperpanjang KTP yang sudah habis masa berlakunya:\n\n1. Datang ke Dinas Dukcapil Kab. Pidie Jaya\n2. Bawa KTP asli dan fotokopi\n3. Bawa KK asli dan fotokopi\n4. Pas foto 3x4 (2 lembar)\n5. Isi formulir perpanjangan\n\nBiaya: GRATIS. Proses: langsung jadi (online).',
            ],
            [
                'kunci' => 'faq-lay-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Anak saya sudah 17 tahun tapi belum punya KTP, bagaimana?',
                'kata_kunci' => ['ktp', 'anak', '17 tahun', 'baru', 'e-ktp'],
                'jawaban_atau_konten' => 'Untuk anak yang sudah berusia 17 tahun dan belum punya KTP:\n\n1. Daftar di Kantor Keuchik untuk pendataan\n2. Bawa fotokopi KK dan Akta Kelahiran\n3. Nanti akan dijadwalkan untuk foto di Dinas Dukcapil\n\nAlternatif: Langsung datang ke Dinas Dukcapil Kab. Pidie Jaya dengan membawa KK dan Akta Kelahiran. GRATIS.',
            ],
            [
                'kunci' => 'faq-lay-031',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengurus surat pindah dari Udeung ke desa lain?',
                'kata_kunci' => ['pindah', 'surat pindah', 'pindah domisili', 'pindah rumah'],
                'jawaban_atau_konten' => 'Untuk mengurus Surat Pindah dari Gampong Udeung:\n\n1. Datang ke Kantor Keuchik membawa:\n   - KTP asli dan fotokopi\n   - KK asli dan fotokopi\n   - Surat Tujuan Pindah dari desa tujuan (jika sudah tahu)\n2. Isi formulir permohonan pindah\n3. Keuchik akan menandatangani surat pindah\n4. Bawa surat pindah ke Dinas Dukcapil untuk pemrosesan\n\nProses: 1-2 hari kerja di Gampong. GRATIS.',
            ],
            [
                'kunci' => 'faq-lay-032',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Saya pindah dari desa lain ke Udeung, apa yang harus dilakukan?',
                'kata_kunci' => ['pindah', 'datang', 'ke udeung', 'pindah domisili'],
                'jawaban_atau_konten' => 'Untuk warga baru yang pindah ke Gampong Udeung:\n\n1. Bawa Surat Pindah dari desa asal\n2. Datang ke Kantor Keuchik membawa:\n   - Surat Pindah\n   - KTP asli dan fotokopi\n   - KK asli dan fotokopi\n   - Akta Nikah/Kelahiran\n3. Keuchik akan membuatkan Surat Keterangan Pindah Datang\n4. Daftarkan ke Dinas Dukcapil untuk update data\n\nSelamat datang di Gampong Udeung!',
            ],
            [
                'kunci' => 'faq-lay-033',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mengurus akta nikah?',
                'kata_kunci' => ['nikah', 'akta nikah', 'kawin', 'menikah', 'isu nikah'],
                'jawaban_atau_konten' => 'Untuk mengurus Akta Nikah:\n\n1. Nikah di Kantor Urusan Agama (KUA) Kec. Bandar Baru\n2. Setelah nikah, akta akan otomatis tercatat\n3. Untuk mendapatkan salinan akta, datang ke KUA dengan membawa:\n   - Buku Nikah asli\n   - KTP kedua pasangan\n   - Fotokopi KK\n\nJika nikah di luar KUA (masjid/meunasah), pastikan tercatat di KUA dalam waktu 30 hari.',
            ],
        ];
    }

    public function getFaqPendidikan(): array
    {
        return [
            [
                'kunci' => 'faq-edu-001',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada beasiswa untuk pelajar di gampong ini?',
                'kata_kunci' => ['beasiswa', 'pelajar', 'sekolah', 'biaya', 'bantuan pendidikan'],
                'jawaban_atau_konten' => 'Ya, ada beberapa program beasiswa:\n\n1. Beasiswa Gampong:\n   - Untuk pelajar SMA/SMK/Sederajat\n   - Syarat: Nilai rata-rata minimal 80, Surat Keterangan Tidak Mampu\n   - Pengajuan: Datang ke Kantor Keuchik\n\n2. Beasiswa Kabupaten Pidie Jaya:\n   - Untuk mahasiswa berprestasi\n   - Syarat: Mahasiswa aktif, IPK minimal 3.5\n   - Pengajuan: Melalui Dinas Pendidikan Kabupaten\n\n3. Beasiswa Aceh (BTA):\n   - Untuk mahasiswa semester 1-2\n   - Syarat: Lulus seleksi\n   - Pengajuan: Online melalui portal BTA\n\nSemua beasiswa GRATIS, tidak dipungut biaya apapun.',
            ],
            [
                'kunci' => 'faq-edu-002',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Di mana ada sekolah di sekitar gampong ini?',
                'kata_kunci' => ['sekolah', 'sd', 'smp', 'sma', 'pendidikan'],
                'jawaban_atau_konten' => 'Sekolah di sekitar Gampong Udeung:\n\nSD Negeri Udeung\n- Alamat: Dusun Tengah\n- Kelas: 1-6\n- Jarak: +/- 500 meter dari kantor gampong\n\nSMP Negeri Bandar Baru\n- Alamat: Kecamatan Bandar Baru\n- Kelas: 7-9\n- Jarak: +/- 2 km\n\nSMA Negeri Bandar Baru\n- Alamat: Kecamatan Bandar Baru\n- Kelas: 10-12\n- Jarak: +/- 2.5 km\n\nMA (Madrasah Aliyah) Bandar Baru\n- Alamat: Kecamatan Bandar Baru\n- Kelas: 10-12\n- Jarak: +/- 3 km\n\nTransportasi: Bisa menggunakan sepeda motor atau jalan kaki.',
            ],
            [
                'kunci' => 'faq-edu-003',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada TPA atau pendidikan anak usia dini?',
                'kata_kunci' => ['tpa', 'paud', 'anak', 'usia dini', 'pendidikan'],
                'jawaban_atau_konten' => 'Ya, ada beberapa lembaga pendidikan anak usia dini:\n\nTPA Meunasah Gampong Udeung\n- Untuk anak usia 4-6 tahun\n- Belajar membaca Al-Qur\'an dan dasar-dasar agama\n- Setiap hari setelah shalat Ashar\n- Biaya: GRATIS (sukarela)\n\nTK Gampong Udeung\n- Untuk anak usia 4-6 tahun\n- Kurikulum nasional dan pendidikan agama\n- Jam belajar: 07.30 - 11.00 WIB\n- Biaya: SPP Rp 50.000/bulan\n\nPAUD Tunas Gampong\n- Untuk anak usia 2-4 tahun\n- Stimulasi perkembangan anak\n- Setiap hari Senin, Rabu, Jumat\n- Biaya: Rp 30.000/bulan',
            ],
            [
                'kunci' => 'faq-edu-004',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke sekolah?',
                'kata_kunci' => ['daftar', 'sekolah', 'pendaftaran', 'anak', 'masuk sekolah'],
                'jawaban_atau_konten' => 'Untuk mendaftarkan anak ke sekolah:\n\n1. SD (Usia 7 tahun):\n   - Bawa Akta Kelahiran\n   - Bawa KK\n   - Bawa Surat Keterangan Lulus dari TK (jika ada)\n   - Pendaftaran: Bulan Mei-Juni\n\n2. SMP (Lulus SD):\n   - Bawa Ijazah SD\n   - Bawa SKL/UN\n   - Bawa KK\n   - Pendaftaran: Bulan Mei-Juni\n\n3. SMA/SMK (Lulus SMP):\n   - Bawa Ijazah SMP\n   - Bawa SKL/UN\n   - Bawa KK\n   - Pendaftaran: Melalui PPDB Online\n\nUntuk sekolah agama (Madrasah), silakan langsung ke madrasah yang bersangkutan.',
            ],
            [
                'kunci' => 'faq-edu-005',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada perpustakaan di gampong?',
                'kata_kunci' => ['perpustakaan', 'buku', 'membaca', 'pustaka'],
                'jawaban_atau_konten' => 'Ya, Gampong Udeung memiliki layanan perpustakaan:\n\nPerpustakaan Gampong Udeung\n- Lokasi: Kantor Keuchik\n- Jam buka: Senin-Kamis 08.00-12.00 WIB\n- Koleksi: Buku pelajaran, novel, majalah, referensi\n- Layanan: Pinjam baca di tempat dan bawa pulang\n\nMobile Library (Kunjungan)\n- Dari Dinas Pendidikan Kab. Pidie Jaya\n- Jadwal: 2 minggu sekali\n- Lokasi: Kantor Keuchik\n\nPerpustakaan Digital\n- Akses online melalui portal gampong\n- E-book dan jurnal gratis',
            ],
            [
                'kunci' => 'faq-edu-006',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana syarat mendapatkan beasiswa gampong?',
                'kata_kunci' => ['beasiswa', 'syarat', 'persyaratan', 'gampong', 'daftar'],
                'jawaban_atau_konten' => 'Syarat mendapatkan Beasiswa Gampong:\n\n1. Warga Gampong Udeung\n2. Pelajar SMA/SMK/Sederajat\n3. Nilai rata-rata minimal 80 dari rapor semester terakhir\n4. Surat Keterangan Tidak Mampu (SKTM) dari Keuchik\n5. Surat Keterangan aktif sekolah\n6. Fotokopi KK dan KTP orang tua\n7. Pas foto 3x4 (2 lembar)\n\nCara mendaftar:\n1. Ambil formulir di Kantor Keuchik\n2. Isi formulir dengan lengkap\n3. Lampirkan persyaratan\n4. Serahkan ke Kantor Keuchik\n5. Tunggu pengumuman seleksi\n\nBesar beasiswa: Rp 500.000/siswa per semester.',
            ],
            [
                'kunci' => 'faq-edu-007',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Kapan jadwal PPDB untuk sekolah di gampong?',
                'kata_kunci' => ['ppdb', 'pendaftaran', 'sekolah', 'jadwal', 'masuk sekolah'],
                'jawaban_atau_konten' => 'Jadwal PPDB (Penerimaan Peserta Didik Baru):\n\nSD Negeri Udeung:\n- Pendaftaran: Mei - Juni\n- Pengumuman: Juli\n- Masuk Sekolah: Juli\n\nSMP Negeri Bandar Baru:\n- Pendaftaran: Mei - Juni\n- Pengumuman: Juli\n- Masuk Sekolah: Juli\n\nSMA/SMK Negeri:\n- Pendaftaran: Juni - Juli (melalui PPDB Online)\n- Pengumuman: Agustus\n- Masuk Sekolah: Agustus\n\nMadrasah:\n- Pendaftaran: Mei - Juli\n- Pengumuman: Juli\n- Masuk Sekolah: Agustus\n\nUntuk informasi lebih lanjut, hubungi sekolah yang bersangkutan.',
            ],
            [
                'kunci' => 'faq-edu-008',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada kursus komputer di gampong?',
                'kata_kunci' => ['kursus', 'komputer', 'pelatihan', 'belajar', 'it'],
                'jawaban_atau_konten' => 'Ya, ada kursus komputer di Gampong Udeung:\n\nKursus Komputer Gampong\n- Lokasi: Aula Kantor Keuchik\n- Jadwal: Setiap Sabtu\n- Waktu: 09.00 - 12.00 WIB\n- Materi:\n  * Dasar komputer (Windows)\n  * Microsoft Office (Word, Excel, PowerPoint)\n  * Internet dan email\n  * Penggunaan smartphone\n- Biaya: Rp 50.000/bulan\n- Pendaftaran: Datang ke Kantor Keuchik\n\nKursus Terbuka:\n- Dari Dinas Kominfo Kab. Pidie Jaya\n- Jadwal: 3 bulan sekali\n- Gratis untuk warga\n\nInstruktur: Petugas IT Gampong dan tenaga pengajar dari Dinas Kominfo.',
            ],
            [
                'kunci' => 'faq-edu-009',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada pelatihan kerja untuk pemuda?',
                'kata_kunci' => ['pelatihan', 'kerja', 'pemuda', 'keterampilan', 'skill'],
                'jawaban_atau_konten' => 'Ya, ada beberapa program pelatihan kerja untuk pemuda:\n\n1. Pelatihan Pertanian:\n   - Materi: Teknik bercocok tanam modern\n   - Penyelenggara: Dinas Pertanian Kab. Pidie Jaya\n   - Jadwal: 2 bulan sekali\n   - Gratis\n\n2. Pelatihan Peternakan:\n   - Materi: Beternak ayam, kambing, sapi\n   - Penyelenggara: Dinas Peternakan\n   - Jadwal: 3 bulan sekali\n   - Gratis\n\n3. Pelatihan Tata Boga:\n   - Materi: Memasak dan pengolahan makanan\n   - Penyelenggara: PKK Gampong\n   - Jadwal: Setiap bulan\n   - Biaya: Rp 100.000 (sudah termasuk bahan)\n\n4. Pelatihan Otomotif:\n   - Materi: Perbaikan motor dan mesin\n   - Penyelenggara: Karang Taruna\n   - Jadwal: Bulanan\n   - Biaya: Rp 75.000/bulan\n\nPendaftaran melalui Kantor Keuchik.',
            ],
            [
                'kunci' => 'faq-edu-010',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan beasiswa untuk kuliah?',
                'kata_kunci' => ['beasiswa', 'kuliah', 'mahasiswa', 'universitas', 'perguruan tinggi'],
                'jawaban_atau_konten' => 'Untuk mendapatkan beasiswa kuliah:\n\n1. Beasiswa Aceh (BTA):\n   - Untuk mahasiswa semester 1-2\n   - Syarat: Lulus seleksi, IPK minimal 3.0\n   - Pengajuan: Online melalui portal BTA\n   - Besaran: Rp 2.500.000/semester\n\n2. Beasiswa Kabupaten Pidie Jaya:\n   - Untuk mahasiswa berprestasi\n   - Syarat: IPK minimal 3.5\n   - Pengajuan: Melalui Dinas Pendidikan\n\n3. Beasiswa Bank Aceh Syariah:\n   - Untuk mahasiswa aktif\n   - Syarat: IPK minimal 3.0\n   - Pengajuan: Kantor Bank Aceh Syariah terdekat\n\n4. Beasiswa LPDP:\n   - Untuk S2 dan S3\n   - Syarat: Lulus seleksi nasional\n   - Pengajuan: Online melalui website LPDP\n\nInformasi lengkap: Kantor Keuchik atau Dinas Pendidikan.',
            ],
            [
                'kunci' => 'faq-edu-011',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apa jalur masuk untuk kuliah di universitas?',
                'kata_kunci' => ['kuliah', 'universitas', 'jalur masuk', 'seleksi', 'pendaftaran'],
                'jawaban_atau_konten' => 'Jalur masuk kuliah di universitas:\n\n1. SNMPTN:\n   - Seleksi berdasarkan prestasi akademik\n   - Syarat: Ranking kelas, prestasi akademik\n   - Pendaftaran: Februari-Maret\n\n2. SBMPTN:\n   - Seleksi berdasarkan ujian tertulis\n   - Materi: TKA (Potensi Akademik) dan TKU\n   - Pendaftaran: Mei-Juni\n\n3. UMPTKIN:\n   - Untuk universitas Islam negeri\n   - Seleksi: Tulis dan Tulis-UNBK\n   - Pendaftaran: Maret-April\n\n4. Jalur Mandiri:\n   - Seleksi oleh masing-masing universitas\n   - Syarat: Berbeda tiap universitas\n   - Pendaftaran: Juni-Juli\n\n5. Politeknik:\n   - Seleksi: Tulis dan Wawancara\n   - Pendaftaran: April-Juni\n\nTips: Mulai persiapan dari kelas 10 SMA.',
            ],
            [
                'kunci' => 'faq-edu-012',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada kursus bahasa Inggris di gampong?',
                'kata_kunci' => ['kursus', 'bahasa inggris', 'english', 'belajar', 'inggris'],
                'jawaban_atau_konten' => 'Saat ini belum ada kursus bahasa Inggris tetap di Gampong Udeung. Namun ada beberapa alternatif:\n\n1. Kursus Privat:\n   - Beberapa guru bahasa Inggris menerima privat\n   - Biaya: Rp 100.000-150.000/jam\n   - Lokasi: Rumah guru atau rumah siswa\n\n2. Kursus Online:\n   - Platform: Duolingo, British Council, dll\n   - Gratis atau berbayar\n   - Bisa diakses dari rumah\n\n3. Kelas Bahasa Inggris Gratis:\n   - Dari Dinas Pendidikan Kab. Pidie Jaya\n   - Jadwal: 2 minggu sekali\n   - Lokasi: Aula Kantor Keuchik\n\n4. Belajar Mandiri:\n   - Gunakan aplikasi belajar bahasa\n   - Tonton video YouTube\n   - Praktik dengan warga asing jika ada\n\nHubungi Kantor Keuchik untuk informasi kelas gratis terbaru.',
            ],
            [
                'kunci' => 'faq-edu-013',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan akses perpustakaan digital?',
                'kata_kunci' => ['perpustakaan', 'digital', 'ebook', 'online', 'akses'],
                'jawaban_atau_konten' => 'Untuk mengakses perpustakaan digital Gampong Udeung:\n\n1. Portal Gampong:\n   - Kunjungi website gampong\n   - Login dengan NIK dan KK\n   - Klik menu "Perpustakaan Digital"\n   - Pilih buku dan baca secara online\n\n2. Aplikasi Perpustakaan Digital:\n   - Unduh aplikasi dari Play Store atau App Store\n   - Daftar dengan NIK\n   - Akses ribuan e-book gratis\n\n3. Kerjasama Dinas Pendidikan:\n   - Akses ke perpustakaan digital kabupaten\n   - Pendaftaran di Kantor Keuchik\n\nKoleksi tersedia:\n- Buku pelajaran SD, SMP, SMA\n- Novel dan cerpen\n- Buku referensi\n- Majalah dan jurnal\n- Buku agama\n\nSemua akses GRATIS untuk warga Gampong Udeung.',
            ],
            [
                'kunci' => 'faq-edu-014',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada program paket A, B, C untuk yang tidak sekolah?',
                'kata_kunci' => ['paket a', 'paket b', 'paket c', 'tidak sekolah', 'setara'],
                'jawaban_atau_konten' => 'Ya, ada program Paket A, B, C untuk yang tidak atau belum menyelesaikan pendidikan formal:\n\nPaket A (Setara SD):\n- Untuk usia 16 tahun ke atas\n- Lokasi: Kantor Keuchik atau Dinas Pendidikan\n- Waktu belajar: Malam hari\n- Biaya: Gratis\n\nPaket B (Setara SMP):\n- Untuk usia 17 tahun ke atas\n- Lokasi: Kantor Keuchik atau Dinas Pendidikan\n- Waktu belajar: Malam hari\n- Biaya: Gratis\n\nPaket C (Setara SMA):\n- Untuk usia 18 tahun ke atas\n- Lokasi: Kantor Keuchik atau Dinas Pendidikan\n- Waktu belajar: Malam hari\n- Biaya: Gratis\n\nPendaftaran:\n- Datang ke Kantor Keuchik membawa:\n  * KTP\n  * KK\n  * Ijazah terakhir (jika ada)\n  * Pas foto\n\nUjian: Dilaksanakan oleh Dinas Pendidikan Kab. Pidie Jaya.',
            ],
            [
                'kunci' => 'faq-edu-015',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke TPA?',
                'kata_kunci' => ['tpa', 'daftar', 'anak', 'pendaftaran', 'mengaji'],
                'jawaban_atau_konten' => 'Untuk mendaftarkan anak ke TPA Meunasah Gampong Udeung:\n\nSyarat:\n- Anak usia 4-6 tahun\n- Sehat jasmani dan rohani\n- Didampingi orang tua\n\nCara mendaftar:\n1. Datang ke Meunasah Gampong Udeung\n2. Bicara dengan ustadz/ustadzah TPA\n3. Isi formulir pendaftaran\n4. Serahkan fotokopi KK\n\nJadwal belajar:\n- Setiap hari setelah shalat Ashar\n- Waktu: 16.00 - 17.30 WIB\n\nBiaya: GRATIS (sukarela)\n\nMateri belajar:\n- Membaca Al-Qur\'an\n- Doa-doa harian\n- Dasar-dasar agama Islam\n- Kreasi dan aktivitas kreatif',
            ],
            [
                'kunci' => 'faq-edu-016',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada sanggar seni di gampong?',
                'kata_kunci' => ['sanggar', 'seni', 'budaya', 'tari', 'musik'],
                'jawaban_atau_konten' => 'Ya, Gampong Udeung memiliki Sanggar Seni Gampong:\n\nSanggar Seni Udeung:\n- Lokasi: Aula Kantor Keuchik\n- Jadwal: Setiap Sabtu sore\n- Waktu: 15.00 - 17.00 WIB\n\nProgram yang tersedia:\n1. Tari Saman:\n   - Untuk pemuda dan pemudi\n   - Latihan: Setiap Sabtu\n   - Pentas: Acara gampong dan festival\n\n2. Tari Ratoh Jaroe:\n   - Untuk perempuan\n   - Latihan: Setiap Sabtu\n\n3. Musik Tradisional:\n   - Rapai, Geuprang, Serune\n   - Untuk laki-laki\n\n4. Kaligrafi:\n   - Untuk semua usia\n   - Latihan: Setiap Minggu pagi\n\nBiaya: GRATIS\nPendaftaran: Datang ke Sanggar atau Kantor Keuchik\n\nSanggar terbuka untuk semua warga tanpa memandang usia.',
            ],
            [
                'kunci' => 'faq-edu-017',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara meminjam buku dari perpustakaan gampong?',
                'kata_kunci' => ['pinjam', 'buku', 'perpustakaan', 'koleksi', 'bawa pulang'],
                'jawaban_atau_konten' => 'Untuk meminjam buku dari Perpustakaan Gampong Udeung:\n\nSyarat:\n- Warga Gampong Udeung\n- Sudah terdaftar sebagai anggota perpustakaan\n- Membawa kartu anggota atau KTP\n\nCara meminjam:\n1. Datang ke Perpustakaan di Kantor Keuchik\n2. Pilih buku yang diinginkan\n3. Serahkan kartu anggota ke petugas\n4. Petugas akan mencatat peminjaman\n5. Buku bisa dibawa pulang\n\nAturan peminjaman:\n- Maksimal 3 buku per orang\n- Masa pinjam: 7 hari\n- Dapat diperpanjang 1 kali\n- Jika terlambat, dikenakan denda Rp 1.000/hari/buku\n\nJam buka perpustakaan:\nSenin-Kamis: 08.00 - 12.00 WIB\nJumat: 08.00 - 11.30 WIB',
            ],
            [
                'kunci' => 'faq-edu-018',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada les privat untuk anak sekolah?',
                'kata_kunci' => ['les', 'privat', 'anak', 'sekolah', 'belajar tambahan'],
                'jawaban_atau_konten' => 'Ya, ada beberapa opsi les privat untuk anak sekolah:\n\n1. Les Privat Mandiri:\n   - Beberapa mahasiswa dan guru membuka les privat\n   - Mata pelajaran: Matematika, IPA, IPS, Bahasa Inggris\n   - Biaya: Rp 50.000-100.000/jam\n   - Lokasi: Rumah siswa atau guru\n\n2. Kelas Belajar Gratis:\n   - Dari Karang Taruna Gampong\n   - Jadwal: Setiap hari Sabtu\n   - Waktu: 09.00 - 11.00 WIB\n   - Lokasi: Aula Kantor Keuchik\n   - Mata pelajaran: Umum\n\n3. Bimbel Online:\n   - Platform: Ruangguru, Zenius, dll\n   - Gratis atau berbayar\n   - Bisa diakses dari rumah\n\n4. Kelas Khusus Ujian:\n   - Menjelang ujian nasional\n   - Dari Dinas Pendidikan\n   - Gratis\n\nHubungi Kantor Keuchik untuk informasi les privat terbaru.',
            ],
            [
                'kunci' => 'faq-edu-019',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke PAUD?',
                'kata_kunci' => ['paud', 'daftar', 'anak', 'usia dini', 'pendidikan dini'],
                'jawaban_atau_konten' => 'Untuk mendaftarkan anak ke PAUD Tunas Gampong:\n\nSyarat:\n- Anak usia 2-4 tahun\n- Sehat jasmani\n- Didampingi orang tua\n\nCara mendaftar:\n1. Datang ke PAUD Tunas Gampong\n2. Bawa fotokopi KK\n3. Isi formulir pendaftaran\n4. Daftarkan langsung di tempat\n\nJadwal belajar:\n- Hari: Senin, Rabu, Jumat\n- Waktu: 08.00 - 10.00 WIB\n\nBiaya:\n- SPP: Rp 30.000/bulan\n- Pendaftaran: Rp 50.000 (satu kali)\n\nMateri belajar:\n- Stimulasi perkembangan motorik\n- Pengenalan warna dan bentuk\n- Bernyanyi dan bercerita\n- Bermain kreatif\n- Dasar-dasar agama',
            ],
            [
                'kunci' => 'faq-edu-020',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada perpustakaan keliling di gampong?',
                'kata_kunci' => ['perpustakaan', 'keliling', 'mobile', 'buku', 'kunjungan'],
                'jawaban_atau_konten' => 'Ya, ada layanan perpustakaan keliling (mobile library):\n\nPerpustakaan Keliling Dinas Pendidikan:\n- Penyelenggara: Dinas Pendidikan Kab. Pidie Jaya\n- Jadwal kunjungan: 2 minggu sekali\n- Hari: Setiap hari Rabu minggu kedua dan keempat\n- Lokasi: Kantor Keuchik Gampong Udeung\n- Waktu: 09.00 - 12.00 WIB\n\nFasilitas:\n- Buku bacaan untuk anak-anak dan dewasa\n- Buku pelajaran\n- Novel dan cerpen\n- Majalah\n\nCara meminjam:\n- Datang ke lokasi perpustakaan keliling\n- Pilih buku yang diinginkan\n- Daftar sebagai anggota (gratis)\n- Bisa dipinjam selama 1 minggu\n\nInformasi jadwal terbaru: Hubungi Kantor Keuchik.',
            ],
            [
                'kunci' => 'faq-edu-021',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan ijazah yang hilang?',
                'kata_kunci' => ['ijazah', 'hilang', 'kehilangan', 'surat keterangan', 'penggantian'],
                'jawaban_atau_konten' => 'Untuk mengurus ijazah yang hilang:\n\n1. Ijazah SD:\n   - Datang ke Kantor Keuchik membawa surat pengantar\n   - Bawa ke Sekolah Asal (SD Negeri Udeung)\n   - Isi formulir penggantian ijazah\n   - Lampirkan: KTP, KK, Surat Keterangan Kehilangan dari Polsek\n   - Proses: 1-2 minggu\n   - Biaya: Sesuai ketetapan sekolah\n\n2. Ijazah SMP/SMA:\n   - Datang ke sekolah asal\n   - Bawa surat pengantar dari Keuchik\n   - Bawa fotokopi ijazah (jika ada)\n   - Proses: 2-4 minggu\n\n3. Ijazah Universitas:\n   - Hubungi bagian akademik universitas\n   - Bawa surat pengantar dari Keuchik\n   - Proses: 1-2 bulan\n\nAlternatif: Bisa membuat Surat Keterangan Lulus sebagai pengganti sementara.',
            ],
            [
                'kunci' => 'faq-edu-022',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada program pendidikan untuk orang dewasa?',
                'kata_kunci' => ['pendidikan', 'dewasa', 'belajar', 'melek huruf', 'setara'],
                'jawaban_atau_konten' => 'Ya, ada beberapa program pendidikan untuk orang dewasa:\n\n1. Keaksaraan Fungsional:\n   - Untuk orang dewasa yang belum bisa baca tulis\n   - Lokasi: Aula Kantor Keuchik\n   - Jadwal: Setiap Selasa dan Kamis malam\n   - Waktu: 19.30 - 21.00 WIB\n   - Biaya: Gratis\n\n2. Pendidikan Paket A/B/C:\n   - Setara SD/SMP/SMA\n   - Lokasi: Kantor Keuchik\n   - Jadwal: Malam hari\n   - Biaya: Gratis\n\n3. Pelatihan Keterampilan:\n   - Kursus komputer\n   - Pelatihan menjahit\n   - Pelatihan memasak\n   - Pelatihan pertanian\n\n4. Pengajian Lansia:\n   - Belajar membaca Al-Qur\'an\n   - Setiap hari setelah shalat Subuh\n   - Lokasi: Meunasah\n\nPendaftaran: Datang ke Kantor Keuchik.',
            ],
            [
                'kunci' => 'faq-edu-023',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan sertifikat komputer?',
                'kata_kunci' => ['sertifikat', 'komputer', 'kompetensi', 'kursus', 'ijazah'],
                'jawaban_atau_konten' => 'Untuk mendapatkan sertifikat komputer:\n\n1. Kursus di Gampong:\n   - Ikuti kursus komputer di Aula Kantor Keuchik\n   - Selesaikan semua materi\n   - Ujian akhir\n   - Dapatkan sertifikat dari Gampong\n\n2. Uji Kompetensi di Dinas:\n   - Daftar di Dinas Ketenagakerjaan Kab. Pidie Jaya\n   - Ujian: Tes praktik dan teori\n   - Sertifikat resmi dari BNSP\n   - Biaya: Gratis atau sesuai ketetapan\n\n3. Kursus Online:\n   - Platform: Coursera, Udemy, dll\n   - Selesaikan kursus\n   - Dapatkan sertifikat digital\n\nJenis sertifikat:\n- Microsoft Office (Word, Excel, PowerPoint)\n- Penggunaan Internet\n- Dasar Pemrograman\n- Desain Grafis\n\nHubungi Kantor Keuchik untuk jadwal kursus terbaru.',
            ],
            [
                'kunci' => 'faq-edu-024',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada bantuan untuk biaya sekolah anak?',
                'kata_kunci' => ['bantuan', 'biaya', 'sekolah', 'anak', 'SPP', 'uang sekolah'],
                'jawaban_atau_konten' => 'Ya, ada beberapa bantuan biaya sekolah:\n\n1. Bantuan Pendidikan Gampong:\n   - Untuk pelajar tidak mampu\n   - Besaran: Rp 200.000-500.000/siswa/tahun\n   - Syarat: SKTM, rapor\n   - Pengajuan: Kantor Keuchik\n\n2. Kartu Indonesia Pintar (KIP):\n   - Untuk SD, SMP, SMA\n   - Bantuan: Rp 900.000 (SD), Rp 1.500.000 (SMP), Rp 2.000.000 (SMA)\n   - Syarat: Terdaftar di DTKS\n   - Pengajuan: Sekolah atau Dinas Pendidikan\n\n3. Beasiswa Prestasi:\n   - Untuk pelajar berprestasi\n   - Syarat: Ranking 1-3, prestasi akademik/non-akademik\n   - Pengajuan: Kantor Keuchik\n\n4. Bantuan Ujian Nasional:\n   - Untuk pelajar kelas 6 SD, 9 SMP, 12 SMA\n   - Berupa: Bimbel gratis, bantuan transportasi\n\nSemua bantuan GRATIS, tidak dipungut biaya.',
            ],
            [
                'kunci' => 'faq-edu-025',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke TK?',
                'kata_kunci' => ['tk', 'taman kanak', 'daftar', 'anak', 'pendidikan'],
                'jawaban_atau_konten' => 'Untuk mendaftarkan anak ke TK Gampong Udeung:\n\nSyarat:\n- Anak usia 4-6 tahun\n- Sehat jasmani\n- Sudah bisa buang air sendiri\n\nDokumen yang dibutuhkan:\n- Akta Kelahiran\n- KK\n- Surat Keterangan Sehat dari Puskesmas\n- Pas foto 2x3 (4 lembar)\n\nCara mendaftar:\n1. Datang ke TK Gampong Udeung\n2. Isi formulir pendaftaran\n3. Serahkan berkas\n4. Bayar biaya pendaftaran dan SPP\n\nBiaya:\n- Pendaftaran: Rp 100.000 (satu kali)\n- SPP: Rp 50.000/bulan\n- Uang gedung: Rp 200.000 (satu kali)\n\nJam belajar:\n- Senin-Jumat\n- 07.30 - 11.00 WIB\n\nFasilitas:\n- Ruang belajar AC\n- Taman bermain\n- Toilet bersih\n- Area parkir',
            ],
            [
                'kunci' => 'faq-edu-026',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada program magang untuk mahasiswa?',
                'kata_kunci' => ['magang', 'mahasiswa', 'praktek', 'intern', 'kuliah'],
                'jawaban_atau_konten' => 'Ya, ada program magang di Gampong Udeung:\n\nProgram Magang Gampong:\n- Untuk mahasiswa semester 5 ke atas\n- Durasi: 1-3 bulan\n- Bidang:\n  * Administrasi pemerintahan desa\n  * Pengelolaan data kependudukan\n  * Program pemberdayaan masyarakat\n  * IT dan sistem informasi\n\nSyarat:\n- Mahasiswa aktif\n- Surat pengantar dari kampus\n- CV/daftar riwayat hidup\n- Surat keterangan sehat\n\nCara mendaftar:\n1. Kirim surat permohonan ke Kantor Keuchik\n2. Lampirkan persyaratan\n3. Tunggu konfirmasi\n4. Ikuti wawancara\n\nFasilitas:\n- Surat keterangan magang\n- Sertifikat\n- Penilaian dari Keuchik\n- Pengalaman kerja\n\nBiaya: GRATIS\n\nHubungi Kantor Keuchik untuk informasi lebih lanjut.',
            ],
            [
                'kunci' => 'faq-edu-027',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke Madrasah?',
                'kata_kunci' => ['madrasah', 'ma', 'mts', 'mi', 'daftar', 'sekolah islam'],
                'jawaban_atau_konten' => 'Untuk mendaftarkan anak ke Madrasah:\n\nMadrasah Ibtidaiyah (MI) - Setara SD:\n- Lokasi: Kecamatan Bandar Baru\n- Syarat: Usia 7 tahun, Akta Kelahiran, KK\n- Pendaftaran: Mei-Juli\n- Biaya: Sesuai ketetapan madrasah\n\nMadrasah Tsanawiyah (MTs) - Setara SMP:\n- Lokasi: Kecamatan Bandar Baru\n- Syarat: Ijazah MI/SD, KK\n- Pendaftaran: Mei-Juli\n- Biaya: Sesuai ketetapan madrasah\n\nMadrasah Aliyah (MA) - Setara SMA:\n- Lokasi: Kecamatan Bandar Baru\n- Syarat: Ijazah MTs/SMP, KK\n- Pendaftaran: Mei-Juli\n- Biaya: Sesuai ketetapan madrasah\n\nKeunggulan Madrasah:\n- Pendidikan agama lebih intens\n- Hafalan Al-Qur\'an\n- Bahasa Arab dan Inggris\n- Ekstrakurikuler keagamaan\n\nSurat Pengantar: Datang ke Kantor Keuchik.',
            ],
            [
                'kunci' => 'faq-edu-028',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada pelatihan UMKM untuk ibu-ibu?',
                'kata_kunci' => ['pelatihan', 'umkm', 'ibu', 'wirausaha', 'usaha'],
                'jawaban_atau_konten' => 'Ya, ada beberapa pelatihan UMKM untuk ibu-ibu:\n\n1. Pelatihan Memasak:\n   - Materi: Resep modern, pengolahan makanan\n   - Penyelenggara: PKK Gampong\n   - Jadwal: Setiap bulan\n   - Biaya: Rp 50.000 (sudah termasuk bahan)\n\n2. Pelatihan Membatik:\n   - Materi: Teknik membatik sederhana\n   - Penyelenggara: Dinas Perindustrian\n   - Jadwal: 2 bulan sekali\n   - Gratis\n\n3. Pelatihan Kerajinan Tangan:\n   - Materi: Membuat tas, dompet, hiasan\n   - Penyelenggara: Karang Taruna\n   - Jadwal: Bulanan\n   - Biaya: Rp 30.000\n\n4. Pelatihan Pengolahan Hasil Pertanian:\n   - Materi: Membuat keripik, selai, minuman\n   - Penyelenggara: Dinas Pertanian\n   - Jadwal: 3 bulan sekali\n   - Gratis\n\n5. Pelatihan Pemasaran Online:\n   - Materi: Jualan di Shopee, Tokopedia, Instagram\n   - Penyelenggara: Dinas Kominfo\n   - Jadwal: Bulanan\n   - Gratis\n\nPendaftaran: Kantor Keuchik atau PKK Gampong.',
            ],
            [
                'kunci' => 'faq-edu-029',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan akses internet untuk belajar?',
                'kata_kunci' => ['internet', 'wifi', 'belajar', 'online', 'akses'],
                'jawaban_atau_konten' => 'Untuk mendapatkan akses internet untuk belajar:\n\n1. WiFi Gratis Gampong:\n   - Lokasi: Kantor Keuchik dan sekitarnya\n   - Waktu: 24 jam\n   - Password: Tanyakan di Kantor Keuchik\n\n2. WiFi Gratis Perpustakaan:\n   - Lokasi: Perpustakaan Gampong\n   - Waktu: Selama jam buka perpustakaan\n\n3. Internet Gratis dari Telkomsel:\n   - Program: Internet Sakti\n   - Kuota: 30GB/bulan untuk pelajar\n   - Syarat: Daftar melalui aplikasi MyTelkomsel\n\n4. WiFi IndiHome:\n   - Paket: Mulai Rp 100.000/bulan\n   - Jaringan: Stabil dan cepat\n   - Pemasangan: Gratis\n\n5. Hotspot di Warung/Warung Kopi:\n   - Beberapa warung menyediakan WiFi gratis\n   - Beli minuman untuk akses\n\nTips: Manfaatkan WiFi gratis untuk keperluan belajar, bukan untuk hiburan semata.',
            ],
            [
                'kunci' => 'faq-edu-030',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada pengajian untuk remaja masjid?',
                'kata_kunci' => ['pengajian', 'remaja', 'masjid', 'remaja masjid', 'komunitas'],
                'jawaban_atau_konten' => 'Ya, ada pengajian rutin untuk Remaja Masjid:\n\nRemaja Masjid Gampong Udeung:\n- Lokasi: Meunasah Gampong Udeung\n- Jadwal: Setiap Sabtu sore\n- Waktu: 16.00 - 17.30 WIB\n\nKegiatan:\n1. Tadarrus Al-Qur\'an\n2. Tafsir Al-Qur\'an\n3. Hafalan surat pendek\n4. Diskusi keagamaan\n5. Kegiatan sosial\n\nAnggota:\n- Pemuda dan pemudi usia 13-25 tahun\n- Terbuka untuk semua\n\nKegiatan Lainnya:\n- Studi wisata ke tempat bersejarah\n- Bakti sosial\n- Turnamen futsal antar remaja masjid\n- Perayaan hari besar Islam\n\nPendaftaran:\n- Datang langsung ke Meunasah\n- Atau hubungi koordinator remaja masjid\n\nBiaya: GRATIS\n\nManfaat:\n- Menambah ilmu agama\n- Memperluas pergaulan positif\n- Berkontribusi untuk masyarakat',
            ],
            [
                'kunci' => 'faq-edu-031',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendapatkan buku pelajaran gratis?',
                'kata_kunci' => ['buku', 'pelajaran', 'gratis', 'bantuan buku', 'pustaka'],
                'jawaban_atau_konten' => 'Untuk mendapatkan buku pelajaran gratis:\n\n1. Program Bantuan Buku Pemerintah:\n   - Untuk SD: Buku paket gratis dari Kemendikbud\n   - Untuk SMP: Buku paket gratis dari Kemendikbud\n   - Untuk SMA: Buku paket gratis dari Kemendikbud\n   - Distribusi: Melalui sekolah masing-masing\n\n2. Bantuan Buku dari Gampong:\n   - Untuk pelajar tidak mampu\n   - Syarat: SKTM dari Keuchik\n   - Pengajuan: Kantor Keuchik\n   - Buku tersedia: Matematika, IPA, IPS, Bahasa\n\n3. Perpustakaan Gampong:\n   - Pinjam buku pelajaran secara gratis\n   - Bisa dipinjam selama 1 minggu\n   - Perpanjangan 1 kali\n\n4. Buku Digital Gratis:\n   - Platform: Kemendikbud.go.id, Rumah Belajar\n   - Akses: Online\n   - Gratis untuk semua\n\n5. Donasi Buku:\n   - Beberapa lembaga donasi buku\n   - Datang ke Kantor Keuchik untuk info\n\nHubungi Kantor Keuchik untuk bantuan buku.',
            ],
            [
                'kunci' => 'faq-edu-032',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Apakah ada bimbingan belajar untuk ujian nasional?',
                'kata_kunci' => ['bimbel', 'ujian nasional', 'un', 'bimbingan', 'belajar'],
                'jawaban_atau_konten' => 'Ya, ada bimbingan belajar untuk Ujian Nasional:\n\n1. Bimbel Gratis dari Dinas Pendidikan:\n   - Untuk kelas 6 SD, 9 SMP, 12 SMA\n   - Jadwal: Setiap hari Sabtu\n   - Waktu: 08.00 - 11.00 WIB\n   - Lokasi: Aula Kantor Keuchik\n   - Materi: Semama mata pelajaran UN\n   - Biaya: Gratis\n\n2. Bimbel dari Karang Taruna:\n   - Untuk pelajar SD dan SMP\n   - Jadwal: Setiap hari Minggu\n   - Waktu: 09.00 - 11.00 WIB\n   - Lokasi: Aula Kantor Keuchik\n   - Biaya: Rp 20.000/minggu\n\n3. Bimbel Online:\n   - Platform: Ruangguru, Zenius, dll\n   - Gratis atau berbayar\n   - Bisa diakses dari rumah\n\n4. Kelas Khusus UN:\n   - Menjelang ujian nasional\n   - Dari Dinas Pendidikan\n   - Gratis\n\nTips: Mulai belajar dari 6 bulan sebelum ujian.',
            ],
            [
                'kunci' => 'faq-edu-033',
                'tipe' => 'faq',
                'pertanyaan_atau_topik' => 'Bagaimana cara mendaftarkan anak ke kursus mengaji?',
                'kata_kunci' => ['kursus', 'mengaji', 'al-quran', 'tpa', 'belajar'],
                'jawaban_atau_konten' => 'Untuk mendaftarkan anak ke kursus mengaji:\n\nTPA Meunasah Gampong Udeung:\n- Untuk anak usia 4-6 tahun\n- Jadwal: Setiap hari setelah shalat Ashar\n- Waktu: 16.00 - 17.30 WIB\n- Materi: Membaca Al-Qur\'an, doa-doa\n- Biaya: GRATIS (sukarela)\n\nPengajian Anak-anak:\n- Untuk anak usia 7-12 tahun\n- Jadwal: Setiap hari setelah shalat Maghrib\n- Waktu: 18.30 - 19.30 WIB\n- Materi: Tafsir Al-Qur\'an, hafalan surat\n- Biaya: GRATIS\n\nKursus Mengaji Privat:\n- Beberapa ustadz/ustadzah menerima privat\n- Biaya: Rp 50.000-100.000/jam\n- Lokasi: Rumah ustadz atau rumah anak\n\nCara mendaftar:\n1. Datang ke Meunasah Gampong\n2. Bicara dengan ustadz/ustadzah\n3. Isi formulir pendaftaran\n4. Serahkan fotokopi KK\n\nFasilitas:\n- Al-Qur\'an\n- Iqro\'\n- Buku doa\n- Tempat belajar nyaman',
            ],
        ];
    }
}
